/**
 * Quiz bank — M01 Welcome to the Lab: Orientation & Safety (Cur §3). 11 items.
 * Transcribed from docs/design/10-curriculum.md; every answer re-verified against
 * docs/reference/REMOVED-internal-reference.md. Options are stored in the doc's canonical display order
 * (the UI reshuffles); `order` items store options in the CORRECT order; `match` pairs are the correct pairing.
 */
import type { QuizQuestion } from '../schema';
import { resolvePeople } from '../people';

export const QUIZ_M01: QuizQuestion[] = resolvePeople([
  {
    id: "Q001",
    type: "mc",
    moduleId: "M01",
    difficulty: 1,
    checkpoint: "CP-M01.1",
    prompt: "What is mounted on the front of every touch-robot enclosure?",
    options: [
      "An emergency-stop mushroom button wired to the Mean Well",
      "A status tablet showing that robot's dashboard",
      "A second LabSim CFD used for OCR",
      "A barcode scanner for card profiles",
    ],
    answer: 1,
    explanation: "Each touch robot has a front-mounted status tablet (F089).",
    factIds: ["F089"],
    tags: ["lab.orientation", "hw.tablet"],
  },
  {
    id: "Q002",
    type: "mc",
    moduleId: "M01",
    difficulty: 1,
    checkpoint: "CP-M01.1",
    prompt: "Roughly how many rigs does Orca's Robot entity track?",
    options: [
      "400+",
      "12",
      "4",
      "40+",
    ],
    answer: 3,
    explanation: "The Robot entity tracks a pool of 40+ rigs and their status flags (F115). Only some are physically in the training room.",
    factIds: ["F115"],
    tags: ["lab.orientation", "orca.robot"],
  },
  {
    id: "Q003",
    type: "tf",
    moduleId: "M01",
    difficulty: 2,
    checkpoint: "CP-M01.1",
    prompt: "While a test is active on a robot, any engineer can press the motion buttons on its control dashboard.",
    options: ["True", "False"],
    answer: 1,
    explanation: "The global LabSim control dashboard locks out external users while tests are active (F230).",
    factIds: ["F230", "F089"],
    tags: ["lab.orientation", "hw.lockout", "hw.tablet"],
  },
  {
    id: "Q004",
    type: "mc",
    moduleId: "M01",
    difficulty: 1,
    checkpoint: "CP-M01.1",
    prompt: "What are the two toggle switches on a touch robot's POWER panel labelled?",
    options: [
      "AC and DC",
      "PI and NUC",
      "MAIN and MOTOR",
      "ON and OFF",
    ],
    answer: 2,
    explanation: "The POWER panel has two green LEDs and toggles labelled MAIN and MOTOR (F236).",
    factIds: ["F236"],
    tags: ["lab.orientation", "hw.tablet"],
  },
  {
    id: "Q005",
    type: "fill",
    moduleId: "M01",
    difficulty: 2,
    checkpoint: "CP-M01.1",
    prompt: "WALL-E's tablet header shows \"Status: OK\" and, beneath it, a board/firmware string. Type it exactly.",
    accepted: ["Brainbox v6"],
    caseInsensitive: true,
    explanation: "The tablet header shows the robot name, the LabSim logo, \"Status: OK\" and \"Brainbox v6\" (F233). Case-insensitive, single space.",
    factIds: ["F233"],
    tags: ["lab.orientation", "hw.tablet"],
  },
  {
    id: "Q006",
    type: "mc",
    moduleId: "M01",
    difficulty: 1,
    prompt: "You try to press Park All on WALL-E and the tablet shows a lock overlay. What is the most likely reason?",
    options: [
      "The MOTOR toggle is off",
      "Park All can only be issued from Orca",
      "WALL-E is Offline in Orca",
      "A test is active, so the global control dashboard locks out external users",
    ],
    answer: 3,
    explanation: "While tests are active the global LabSim control dashboard locks out external users (F230).",
    factIds: ["F230"],
    tags: ["lab.orientation", "hw.lockout"],
  },
  {
    id: "Q007",
    type: "mc",
    moduleId: "M01",
    difficulty: 1,
    prompt: "Which machines produce the lab's black plastic modular shelf fixtures?",
    options: [
      "An injection-moulding shop in Hong Kong",
      "Prusa and Bambu Lab 3D printers",
      "A CNC mill at {{jared}}'s bench",
      "Formlabs resin printers",
    ],
    answer: 1,
    explanation: "All black plastic modular shelf fixtures are printed on Prusa and Bambu Lab 3D printers (F072). Hong Kong is where the motor PCBs were printed.",
    factIds: ["F072"],
    tags: ["lab.orientation", "hw.print3d"],
  },
  {
    id: "Q008",
    type: "tf",
    moduleId: "M01",
    difficulty: 1,
    prompt: "The shelf fixtures are drafted in CAD using simple geometric shapes.",
    options: ["True", "False"],
    answer: 0,
    explanation: "Fixtures are drafted in CAD from simple geometric shapes (F073).",
    factIds: ["F073"],
    tags: ["lab.orientation", "hw.print3d"],
  },
  {
    id: "Q009",
    type: "mc",
    moduleId: "M01",
    difficulty: 1,
    prompt: "In the reference photo, what are the numbers printed along WALL-E's rack rails?",
    options: [
      "Millimetre coordinates for the gantry",
      "Robot IDs from Orca",
      "Rack-unit numbers (e.g. 29 to 40)",
      "Fuse ratings in amps",
    ],
    answer: 2,
    explanation: "The rails are marked with numbered rack units (F244).",
    factIds: ["F244"],
    tags: ["lab.orientation", "hw.rigbom"],
  },
  {
    id: "Q010",
    type: "mc",
    moduleId: "M01",
    difficulty: 1,
    prompt: "Which letters run vertically down the panel to the right of WALL-E's tablet in the reference photo?",
    options: [
      "SETI",
      "EVE",
      "TARS",
      "DATA",
    ],
    answer: 0,
    explanation: "A panel lettered SETI with USB ports for the Minix box / Raspberry Pi sits to the right (F245).",
    factIds: ["F245"],
    tags: ["lab.orientation", "hw.tablet"],
  },
  {
    id: "Q011",
    type: "tf",
    moduleId: "M01",
    difficulty: 2,
    prompt: "The robot name across the top of a status tablet is typed into the tablet by hand.",
    options: ["True", "False"],
    answer: 1,
    explanation: "The Human Readable Name is pushed from Orca to the front-mounted status tablet (F118, F089).",
    factIds: ["F089", "F118"],
    tags: ["lab.orientation", "hw.tablet", "orca.names"],
  },
]);
