/**
 * Quiz bank — M02 Know Your terminals: Device Families (Cur §3). 16 items.
 * Transcribed from docs/design/10-curriculum.md; every answer re-verified against
 * docs/reference/REMOVED-internal-reference.md. Options are stored in the doc's canonical display order
 * (the UI reshuffles); `order` items store options in the CORRECT order; `match` pairs are the correct pairing.
 */
import type { QuizQuestion } from '../schema';
import { resolvePeople } from '../people';

export const QUIZ_M02: QuizQuestion[] = resolvePeople([
  {
    id: "Q012",
    type: "mc",
    moduleId: "M02",
    difficulty: 1,
    checkpoint: "CP-M02.1",
    prompt: "What does MFD stand for?",
    options: [
      "Merchant Front Display",
      "Multi-Function Device",
      "Merchant Facing Device",
      "Main Function Display",
    ],
    answer: 2,
    explanation: "MFD = Merchant Facing Device (F054).",
    factIds: ["F054"],
    tags: ["devices", "hw.devices"],
  },
  {
    id: "Q013",
    type: "fill",
    moduleId: "M02",
    difficulty: 2,
    checkpoint: "CP-M02.1",
    prompt: "CFD stands for \"Customer ______ Device\". Type the missing word.",
    accepted: ["Facing"],
    caseInsensitive: true,
    explanation: "CFD = Customer Facing Device (F054). Case-insensitive.",
    factIds: ["F054"],
    tags: ["devices", "hw.devices"],
  },
  {
    id: "Q014",
    type: "match",
    moduleId: "M02",
    difficulty: 3,
    checkpoint: "CP-M02.1",
    prompt: "Match each device to its family or role.",
    pairs: [
      ["Station 2018", "Station series"],
      ["Mini 3", "Mini series"],
      ["Flex Pocket", "Flex series"],
      ["LabSim Compact", "Canadian-market terminal (Westers)"],
    ],
    explanation: "Station 2018 is a Station (F055); Mini 3 is a Mini (F056); Flex Pocket is a Flex (F058); the Compact targets Canada on Westers beds (F061).",
    factIds: ["F055", "F056", "F058", "F061"],
    tags: ["devices", "hw.devices"],
  },
  {
    id: "Q015",
    type: "mc",
    moduleId: "M02",
    difficulty: 1,
    checkpoint: "CP-M02.1",
    prompt: "Which three devices share exactly the same testing profile?",
    options: [
      "Flex 3, Flex 4 and Flex Pocket",
      "Mini 2, Mini 3 and Mini 4",
      "Flex 1, Flex 2 and Flex 3",
      "Station 2, Station Duo and Station Duo 2",
    ],
    answer: 0,
    explanation: "Flex 3, Flex 4 and Flex Pocket share the exact same testing profile (F059).",
    factIds: ["F059"],
    tags: ["devices", "hw.devices"],
  },
  {
    id: "Q016",
    type: "tf",
    moduleId: "M02",
    difficulty: 1,
    prompt: "The Flex 2 shares the Flex 3 testing profile.",
    options: ["True", "False"],
    answer: 1,
    explanation: "Only Flex 3, Flex 4 and Flex Pocket share the profile (F059).",
    factIds: ["F059"],
    tags: ["devices", "hw.devices"],
  },
  {
    id: "Q017",
    type: "mc",
    moduleId: "M02",
    difficulty: 1,
    checkpoint: "CP-M02.1",
    prompt: "What does the Flex Pocket omit compared with the Flex 3 and Flex 4?",
    options: [
      "The touch screen",
      "The EMV chip reader",
      "The NFC antenna",
      "The physical printer block",
    ],
    answer: 3,
    explanation: "The Pocket shares the Flex 3/4 profile but omits the physical printer block (F060).",
    factIds: ["F060"],
    tags: ["devices", "hw.devices"],
  },
  {
    id: "Q018",
    type: "mc",
    moduleId: "M02",
    difficulty: 1,
    prompt: "Which device is used as the hot-swap equivalent for the printerless Station Duo 2?",
    options: [
      "Station 2",
      "Flex Pocket",
      "Mini 3",
      "Mini 2",
    ],
    answer: 2,
    explanation: "The Mini 3 is the hot-swap equivalent for the printerless Duo 2 (F057).",
    factIds: ["F057"],
    tags: ["devices", "hw.devices"],
  },
  {
    id: "Q019",
    type: "tf",
    moduleId: "M02",
    difficulty: 1,
    prompt: "The Station Duo 2 has a built-in printer.",
    options: ["True", "False"],
    answer: 1,
    explanation: "The Duo 2 is printerless, which is why a Mini 3 can hot-swap for it (F057).",
    factIds: ["F057"],
    tags: ["devices", "hw.devices"],
  },
  {
    id: "Q020",
    type: "mc",
    moduleId: "M02",
    difficulty: 1,
    prompt: "Which terminal is the target for the Canadian market on the Westers test beds?",
    options: [
      "Station 2018",
      "Flex Pocket",
      "Mini 4",
      "LabSim Compact",
    ],
    answer: 3,
    explanation: "The LabSim Compact targets Canada and is used on Westers test beds (F061).",
    factIds: ["F061"],
    tags: ["devices", "hw.devices"],
  },
  {
    id: "Q021",
    type: "mc",
    moduleId: "M02",
    difficulty: 1,
    prompt: "Which pair are listed as upcoming devices?",
    options: [
      "Compact and Flex Pocket",
      "Station 2018 and Flex 1",
      "Station Duo 3 and Mini 4",
      "Flex 4 and Mini 3",
    ],
    answer: 2,
    explanation: "Duo 3 and Mini 4 are upcoming (F062).",
    factIds: ["F062"],
    tags: ["devices", "hw.devices"],
  },
  {
    id: "Q022",
    type: "mc",
    moduleId: "M02",
    difficulty: 1,
    prompt: "Which of these is NOT a LabSim target device in the reference?",
    options: [
      "Station 2018",
      "Station Mini",
      "Station 2",
      "Station Duo 2",
    ],
    answer: 1,
    explanation: "The Station series is Station 2018, Station 2 and Station Duo (Duo 1, Duo 2, upcoming Duo 3) (F055). \"Station Mini\" does not exist.",
    factIds: ["F055"],
    tags: ["devices", "hw.devices"],
  },
  {
    id: "Q023",
    type: "mc",
    moduleId: "M02",
    difficulty: 1,
    prompt: "How many Flex models are listed, counting the Pocket?",
    options: [
      "4",
      "6",
      "5",
      "3",
    ],
    answer: 2,
    explanation: "Flex 1, Flex 2, Flex 3, Flex 4 and Flex Pocket (F058).",
    factIds: ["F058"],
    tags: ["devices", "hw.devices"],
  },
  {
    id: "Q024",
    type: "mc",
    moduleId: "M02",
    difficulty: 1,
    prompt: "Which list is the Mini series?",
    options: [
      "Mini 3, Mini 4, Mini Pocket",
      "Mini 1, Mini 2, Mini 3",
      "Mini 2, Mini 3, Mini 4 (upcoming)",
      "Mini 2, Mini Duo, Mini 3",
    ],
    answer: 2,
    explanation: "The Mini series is Mini 2, Mini 3 and the upcoming Mini 4 (F056).",
    factIds: ["F056"],
    tags: ["devices", "hw.devices"],
  },
  {
    id: "Q025",
    type: "fill",
    moduleId: "M02",
    difficulty: 2,
    prompt: "In the reference photo, MEGATRON's screens carry which environment label? Type it exactly.",
    accepted: ["DEV1"],
    caseInsensitive: true,
    explanation: "The labels read MEGATRON MFD DEV1 / MEGATRON CFD DEV1; OPTIMUS carries STG (F237).",
    factIds: ["F237"],
    tags: ["devices", "hw.devices"],
  },
  {
    id: "Q026",
    type: "mc",
    moduleId: "M02",
    difficulty: 1,
    prompt: "What are the black USB dongles with green LEDs between the tethered screens?",
    options: [
      "Collis probes",
      "Raspberry Pi cameras",
      "Inline fuses",
      "SmartStripe Probe dongles",
    ],
    answer: 3,
    explanation: "The reference photo shows USB \"SmartStripe Probe\" dongles between the screens (F238). Collis probes are grey boxes on ribbon cables.",
    factIds: ["F238"],
    tags: ["devices", "hw.devices"],
  },
  {
    id: "Q027",
    type: "mc",
    moduleId: "M02",
    difficulty: 1,
    prompt: "What do the black 3D-printed docks below the tethered screens hold?",
    options: [
      "White LabSim connectivity hubs (Ethernet, USB, power)",
      "Collis probe ribbon spools",
      "Mean Well transformers",
      "Spare Raspberry Pis",
    ],
    answer: 0,
    explanation: "The docks hold LabSim connectivity hubs labelled per device, e.g. MEGATRON MFD (F239).",
    factIds: ["F239"],
    tags: ["devices", "hw.devices"],
  },
]);
