/**
 * Quiz bank — M03 Power Distribution: Don't Fry the terminals (Cur §3). 12 items.
 * Transcribed from docs/design/10-curriculum.md; every answer re-verified against
 * docs/reference/REMOVED-internal-reference.md. Options are stored in the doc's canonical display order
 * (the UI reshuffles); `order` items store options in the CORRECT order; `match` pairs are the correct pairing.
 */
import type { QuizQuestion } from '../schema';
import { resolvePeople } from '../people';

export const QUIZ_M03: QuizQuestion[] = resolvePeople([
  {
    id: "Q028",
    type: "mc",
    moduleId: "M03",
    difficulty: 1,
    checkpoint: "CP-M03.1",
    prompt: "What does the Mean Well transformer output?",
    options: [
      "12V DC for the NUCs",
      "18V AC for the terminals",
      "5V DC at 10A for the Pis",
      "A central 24V DC rail",
    ],
    answer: 3,
    explanation: "Mean Well converts 120V AC wall power into a central 24V DC rail (F074).",
    factIds: ["F074"],
    tags: ["power.rails"],
  },
  {
    id: "Q029",
    type: "fill",
    moduleId: "M03",
    difficulty: 2,
    prompt: "Wall power entering the Mean Well is ___ V AC. Type the number.",
    accepted: ["120"],
    caseInsensitive: true,
    explanation: "120V AC enters the Mean Well (F074, F227).",
    factIds: ["F074", "F227"],
    tags: ["power.rails", "power.fuses"],
  },
  {
    id: "Q030",
    type: "mc",
    moduleId: "M03",
    difficulty: 1,
    checkpoint: "CP-M03.1",
    prompt: "Which line powers the Windows Intel NUCs?",
    options: [
      "18V from an AC strip",
      "5V DC, 10A",
      "12V DC",
      "24V DC straight from the rail",
    ],
    answer: 2,
    explanation: "A step-down regulator provides 12V DC for the NUCs (F085).",
    factIds: ["F085"],
    tags: ["power.rails"],
  },
  {
    id: "Q031",
    type: "mc",
    moduleId: "M03",
    difficulty: 1,
    checkpoint: "CP-M03.1",
    prompt: "Which line powers the Raspberry Pis?",
    options: [
      "12V DC, 10A",
      "5V DC, 10A",
      "5V DC, 2A",
      "24V DC",
    ],
    answer: 1,
    explanation: "Pis run from a 5V DC, 10-Amp step-down line (F086).",
    factIds: ["F086"],
    tags: ["power.rails"],
  },
  {
    id: "Q032",
    type: "fill",
    moduleId: "M03",
    difficulty: 2,
    prompt: "The Raspberry Pi line is 5V DC at ___ amps. Type the number.",
    accepted: ["10", "ten"],
    caseInsensitive: true,
    explanation: "5V DC, 10A powers the Pis (F086).",
    factIds: ["F086"],
    tags: ["power.rails"],
  },
  {
    id: "Q033",
    type: "order",
    moduleId: "M03",
    difficulty: 3,
    checkpoint: "CP-M03.1",
    prompt: "Put the power chain in order from the wall to the Pis.",
    options: [
      "120V AC wall power",
      "Mean Well transformer",
      "Central 24V DC rail",
      "Step-down regulator",
      "Inline fuse on the 5V 10A line",
      "Raspberry Pi",
    ],
    answer: -1,
    explanation: "120V AC → Mean Well → 24V DC rail → step-down regulators (12V / 5V 10A) protected by inline fuses → loads (F227).",
    factIds: ["F227", "F074", "F085", "F086"],
    tags: ["power.rails", "power.fuses"],
  },
  {
    id: "Q034",
    type: "tf",
    moduleId: "M03",
    difficulty: 1,
    prompt: "Inline fuses protect the DC lines that feed the NUCs and Pis.",
    options: ["True", "False"],
    answer: 0,
    explanation: "The 12V and 5V lines are protected by inline fuses (F087, F227).",
    factIds: ["F087"],
    tags: ["power.rails", "power.fuses"],
  },
  {
    id: "Q035",
    type: "mc",
    moduleId: "M03",
    difficulty: 1,
    checkpoint: "CP-M03.1",
    prompt: "What voltage do LabSim devices draw?",
    options: [
      "5V",
      "An irregular 18V",
      "12V",
      "24V",
    ],
    answer: 1,
    explanation: "LabSim devices draw an irregular 18V (F228).",
    factIds: ["F228"],
    tags: ["power.rails", "power.18v"],
  },
  {
    id: "Q036",
    type: "mc",
    moduleId: "M03",
    difficulty: 1,
    prompt: "Where must LabSim terminals and Collis probes be plugged in?",
    options: [
      "The 5V 10A Pi line",
      "The central 24V DC rail",
      "Commercial AC power strips",
      "The 12V NUC line",
    ],
    answer: 2,
    explanation: "Both bypass the custom DC rails and plug into commercial AC power strips (F229).",
    factIds: ["F229"],
    tags: ["power.rails", "power.18v"],
  },
  {
    id: "Q037",
    type: "tf",
    moduleId: "M03",
    difficulty: 1,
    prompt: "Collis probes are powered from the 24V rail so they share a ground with the robot.",
    options: ["True", "False"],
    answer: 1,
    explanation: "Collis probes, like LabSim terminals, bypass the DC rails and use commercial AC strips (F229).",
    factIds: ["F229"],
    tags: ["power.rails", "power.18v"],
  },
  {
    id: "Q038",
    type: "mc",
    moduleId: "M03",
    difficulty: 2,
    prompt: "Why do LabSim devices bypass the lab's custom DC rails?",
    options: [
      "They draw an irregular 18V, so the rails risk frying components",
      "LabSim devices are powered over USB from the Pi",
      "corporate policy forbids it",
      "The rails are reserved for the GPU blade",
    ],
    answer: 0,
    explanation: "LabSim devices draw an irregular 18V, so they and the Collis probes use AC strips to prevent frying components (F228, F229).",
    factIds: ["F228", "F229"],
    tags: ["power.rails", "power.18v"],
  },
  {
    id: "Q039",
    type: "match",
    moduleId: "M03",
    difficulty: 3,
    prompt: "Match each item to its power source.",
    pairs: [
      ["Raspberry Pi", "5V DC 10A line"],
      ["Intel NUC", "12V DC line"],
      ["LabSim terminal", "Commercial AC power strip"],
      ["Mean Well transformer", "120V AC wall power"],
    ],
    explanation: "Pis 5V 10A (F086), NUCs 12V (F085), terminals on AC strips (F229), Mean Well fed by 120V AC (F074).",
    factIds: ["F085", "F086", "F229", "F074"],
    tags: ["power.rails", "power.18v"],
  },
]);
