/**
 * Quiz bank — M04 Touch Robot Mechanics & the Status Tablet (Cur §3). 23 items.
 * Transcribed from docs/design/10-curriculum.md; every answer re-verified against
 * docs/reference/REMOVED-internal-reference.md. Options are stored in the doc's canonical display order
 * (the UI reshuffles); `order` items store options in the CORRECT order; `match` pairs are the correct pairing.
 */
import type { QuizQuestion } from '../schema';
import { resolvePeople } from '../people';

export const QUIZ_M04: QuizQuestion[] = resolvePeople([
  {
    id: "Q040",
    type: "mc",
    moduleId: "M04",
    difficulty: 1,
    checkpoint: "CP-M04.1",
    prompt: "Which Motion Control button group contains \"Park All\"?",
    options: [
      "Solenoid",
      "Steppers",
      "Park",
      "Phone",
    ],
    answer: 2,
    explanation: "Park holds Park All / XY / X / Y (F235).",
    factIds: ["F235"],
    tags: ["robots.mechanics", "hw.tablet"],
  },
  {
    id: "Q041",
    type: "match",
    moduleId: "M04",
    difficulty: 3,
    checkpoint: "CP-M04.1",
    prompt: "Match each tablet button group to its buttons.",
    pairs: [
      ["Steppers", "Enable / Disable"],
      ["Park", "Park All / XY / X / Y"],
      ["Solenoid", "Down / Up / Lower / Raise"],
      ["Phone", "Forward / Back / Push Power Button"],
    ],
    explanation: "From the WALL-E Motion Control tab (F235). Dip and Tap each have In / Out.",
    factIds: ["F235"],
    tags: ["robots.mechanics", "hw.tablet"],
  },
  {
    id: "Q042",
    type: "mc",
    moduleId: "M04",
    difficulty: 1,
    checkpoint: "CP-M04.1",
    prompt: "You push WALL-E's carriage by hand. What happens?",
    options: [
      "The banner turns red and Orca sets Connection Failed",
      "The solenoid fires automatically",
      "Nothing, because the steppers are passive",
      "Its magnetic lock breaks and the top status banner turns yellow",
    ],
    answer: 3,
    explanation: "Manually moving an arm breaks its magnetic lock and turns the banner yellow (F231).",
    factIds: ["F231"],
    tags: ["robots.mechanics", "hw.motion"],
  },
  {
    id: "Q043",
    type: "mc",
    moduleId: "M04",
    difficulty: 1,
    checkpoint: "CP-M04.1",
    prompt: "What does Park All do?",
    options: [
      "Sets the robot to Offline in Orca",
      "Disables the steppers so the gantry can be pushed freely",
      "Drives the steppers back to the physical limit switches at (0,0), clears errors and turns the banner green",
      "Parks only the dip arm",
    ],
    answer: 2,
    explanation: "Park All homes the steppers to the limit switches at (0,0), clearing errors (green banner) (F232).",
    factIds: ["F232"],
    tags: ["robots.mechanics", "hw.motion"],
  },
  {
    id: "Q044",
    type: "tf",
    moduleId: "M04",
    difficulty: 1,
    prompt: "After a successful Park All, the status banner turns green.",
    options: ["True", "False"],
    answer: 0,
    explanation: "Park All clears errors and turns the banner green (F232).",
    factIds: ["F232"],
    tags: ["robots.mechanics", "hw.motion"],
  },
  // Correction vs Cur §3: accept "0, 0" / "(0, 0)" too (spacing)
  {
    id: "Q045",
    type: "fill",
    moduleId: "M04",
    difficulty: 2,
    prompt: "Park All homes the gantry to which coordinate? Type it as x,y.",
    accepted: ["0,0", "(0,0)", "0, 0", "(0, 0)"],
    caseInsensitive: true,
    explanation: "Park All drives the steppers to the limit switches at (0,0) (F232, F082).",
    factIds: ["F232", "F082"],
    tags: ["robots.mechanics", "hw.motion", "hw.rigbom"],
  },
  {
    id: "Q046",
    type: "mc",
    moduleId: "M04",
    difficulty: 1,
    prompt: "What physically defines a touch robot's (0,0) origin?",
    options: [
      "The webcam's calibration image",
      "The Offsets field in Orca",
      "The physical limit switches",
      "The tablet's Park XY button",
    ],
    answer: 2,
    explanation: "Physical limit switches are calibrated to (0,0) (F082).",
    factIds: ["F082"],
    tags: ["robots.mechanics", "hw.rigbom", "hw.motion"],
  },
  {
    id: "Q047",
    type: "mc",
    moduleId: "M04",
    difficulty: 1,
    checkpoint: "CP-M04.1",
    prompt: "What physically taps the screen on a touch robot?",
    options: [
      "The plunger of a remote-firing solenoid",
      "A capacitive stylus on a belt",
      "An ADB input tap from the Pi",
      "A servo-driven finger",
    ],
    answer: 0,
    explanation: "Rigs use remote-firing solenoids whose plunger drops (F080).",
    factIds: ["F080"],
    tags: ["robots.mechanics", "hw.rigbom"],
  },
  {
    id: "Q048",
    type: "mc",
    moduleId: "M04",
    difficulty: 1,
    prompt: "What precision do the rig stepper motors move with?",
    options: [
      "Whole pixels",
      "About 5 mm",
      "About 1 cm",
      "Sub-millimetre",
    ],
    answer: 3,
    explanation: "The rigs use sub-millimetre stepper motors (F079).",
    factIds: ["F079"],
    tags: ["robots.mechanics", "hw.rigbom"],
  },
  {
    id: "Q049",
    type: "mc",
    moduleId: "M04",
    difficulty: 2,
    prompt: "Which description fits the custom motor-controller PCBs?",
    options: [
      "25-pin boards printed in Hong Kong",
      "40-pin GPIO HATs bought from the Pi Foundation",
      "USB-C boards made by Mean Well",
      "9-pin boards printed in-house on the Prusa",
    ],
    answer: 0,
    explanation: "Custom 25-pin motor-controller PCBs, printed in Hong Kong (F083, F084).",
    factIds: ["F083", "F084"],
    tags: ["robots.mechanics", "hw.rigbom"],
  },
  {
    id: "Q050",
    type: "fill",
    moduleId: "M04",
    difficulty: 2,
    prompt: "The custom motor-controller PCBs use a ___-pin connector. Type the number.",
    accepted: ["25"],
    caseInsensitive: true,
    explanation: "Custom 25-pin motor controller PCBs (F083).",
    factIds: ["F083"],
    tags: ["robots.mechanics", "hw.rigbom"],
  },
  {
    id: "Q051",
    type: "mc",
    moduleId: "M04",
    difficulty: 1,
    prompt: "How long are the aluminium rails cut for a touch robot?",
    options: [
      "20 ft",
      "5 ft",
      "1 m",
      "10 ft",
    ],
    answer: 3,
    explanation: "Touch robots use 10 ft cut aluminium rails (F090).",
    factIds: ["F090"],
    tags: ["robots.mechanics", "hw.rigbom"],
  },
  {
    id: "Q052",
    type: "mc",
    moduleId: "M04",
    difficulty: 1,
    prompt: "About how much wiring goes into one touch robot?",
    options: [
      "13 ft",
      "130 ft",
      "30 ft",
      "300 ft",
    ],
    answer: 1,
    explanation: "About 130 ft of wiring per touch robot (F091).",
    factIds: ["F091"],
    tags: ["robots.mechanics", "hw.rigbom"],
  },
  {
    id: "Q053",
    type: "mc",
    moduleId: "M04",
    difficulty: 1,
    prompt: "About how many manual solder points does one touch robot have?",
    options: [
      "About 300",
      "About 3,000",
      "About 130",
      "About 30",
    ],
    answer: 0,
    explanation: "~300 manual solder points per touch robot (F092).",
    factIds: ["F092"],
    tags: ["robots.mechanics", "hw.rigbom"],
  },
  {
    id: "Q054",
    type: "mc",
    moduleId: "M04",
    difficulty: 1,
    prompt: "A touch robot uses 200+ nuts and bolts in which diameters?",
    options: [
      "2.5 mm and 5 mm",
      "3 mm and 6 mm",
      "8 mm only",
      "2 mm and 4 mm",
    ],
    answer: 0,
    explanation: "200+ nuts and bolts in 2.5 mm and 5 mm diameters (F093).",
    factIds: ["F093"],
    tags: ["robots.mechanics", "hw.rigbom"],
  },
  {
    id: "Q055",
    type: "mc",
    moduleId: "M04",
    difficulty: 1,
    prompt: "Which of these is NOT a tab on the status tablet?",
    options: [
      "Motion Control",
      "Robot Control",
      "Robot",
      "Health Check",
    ],
    answer: 3,
    explanation: "The tabs are Robot, Robot Control and Motion Control (F234).",
    factIds: ["F234"],
    tags: ["robots.mechanics", "hw.tablet"],
  },
  {
    id: "Q056",
    type: "mc",
    moduleId: "M04",
    difficulty: 1,
    prompt: "Which motor drives the gantry axes in the reference photo?",
    options: [
      "A NEMA-34 stepper on a lead screw",
      "A brushed DC gear motor",
      "A NEMA-17 stepper with a GT2 pulley",
      "A hobby servo",
    ],
    answer: 2,
    explanation: "The gantry uses a NEMA-17 stepper with a GT2 pulley on 2020 extrusion with V-slot wheels (F240).",
    factIds: ["F240"],
    tags: ["robots.mechanics", "hw.rigbom"],
  },
  {
    id: "Q057",
    type: "mc",
    moduleId: "M04",
    difficulty: 1,
    prompt: "What carries the emulated card into the Flex's chip slot?",
    options: [
      "The blue push-pull solenoid",
      "A rotating dip arm (sector gear) holding a flat white ribbon card",
      "A technician, by hand",
      "The Phone carriage",
    ],
    answer: 1,
    explanation: "A black rotating dip arm (sector gear marked 63) carries the white ribbon card (Collis insert) into the slot (F241).",
    factIds: ["F241"],
    tags: ["robots.mechanics", "hw.rigbom"],
  },
  {
    id: "Q058",
    type: "order",
    moduleId: "M04",
    difficulty: 3,
    prompt: "Order the solenoid tap cycle seen in the Flex 3 video.",
    options: [
      "Gantry moves the head over the target button",
      "Plunger drops and taps",
      "Plunger lifts",
      "Gantry moves to the next button",
      "Plunger drops and taps again",
    ],
    answer: -1,
    explanation: "The video shows move → drop → lift → move → tap again (F243).",
    factIds: ["F243", "F080"],
    tags: ["robots.mechanics", "hw.rigbom"],
  },
  {
    id: "Q059",
    type: "tf",
    moduleId: "M04",
    difficulty: 1,
    prompt: "Each rig arm is held in place by a magnetic lock.",
    options: ["True", "False"],
    answer: 0,
    explanation: "Rigs have magnetic locks; moving an arm by hand breaks the lock (F081, F231).",
    factIds: ["F081"],
    tags: ["robots.mechanics", "hw.rigbom", "hw.motion"],
  },
  {
    id: "Q060",
    type: "mc",
    moduleId: "M04",
    difficulty: 1,
    prompt: "What on a rig provides the camera stream used for monitoring and OCR?",
    options: [
      "A webcam mounted on the rig",
      "The LabSim device's own camera",
      "A camera built into the Raspberry Pi board",
      "The status tablet's front camera",
    ],
    answer: 0,
    explanation: "Rigs carry webcams (F088), served by the Pi as camera streams.",
    factIds: ["F088"],
    tags: ["robots.mechanics", "hw.rigbom", "vision.camera"],
  },
  {
    id: "Q061",
    type: "tf",
    moduleId: "M04",
    difficulty: 1,
    prompt: "In the side-view photo, the Flex lies flat on the shelf with no fixture.",
    options: ["True", "False"],
    answer: 1,
    explanation: "The Flex sits in an angled black 3D-printed cradle, next to the grey Collis probe box (F242).",
    factIds: ["F242"],
    tags: ["robots.mechanics", "hw.rigbom"],
  },
  {
    id: "Q062",
    type: "order",
    moduleId: "M04",
    difficulty: 3,
    prompt: "Order the recovery after someone pushes a robot arm by hand.",
    options: [
      "Arm moved by hand",
      "Magnetic lock breaks",
      "Status banner turns yellow",
      "Engineer presses Park All",
      "Steppers drive to the limit switches at (0,0)",
      "Banner turns green",
    ],
    answer: -1,
    explanation: "Moving the arm breaks the lock (yellow); Park All homes to (0,0) and clears it (green) (F231, F232).",
    factIds: ["F231", "F232"],
    tags: ["robots.mechanics", "hw.motion"],
  },
]);
