/**
 * Quiz bank — M05 The Robot Pi: Raspberry Pi, Linux & Wine (Cur §3). 15 items.
 * Transcribed from docs/design/10-curriculum.md; every answer re-verified against
 * docs/reference/REMOVED-internal-reference.md. Options are stored in the doc's canonical display order
 * (the UI reshuffles); `order` items store options in the CORRECT order; `match` pairs are the correct pairing.
 */
import type { QuizQuestion } from '../schema';
import { resolvePeople } from '../people';

export const QUIZ_M05: QuizQuestion[] = resolvePeople([
  {
    id: "Q063",
    type: "mc",
    moduleId: "M05",
    difficulty: 1,
    checkpoint: "CP-M05.1",
    prompt: "What is the Robot Controller on each shelf?",
    options: [
      "The GPU server blade",
      "A Raspberry Pi",
      "An Intel NUC",
      "A Minix box",
    ],
    answer: 1,
    explanation: "A Raspberry Pi operates as the Robot Pi / Robot Controller on each shelf (F064).",
    factIds: ["F064"],
    tags: ["pi.controller", "hw.pi"],
  },
  {
    id: "Q064",
    type: "mc",
    moduleId: "M05",
    difficulty: 1,
    prompt: "About how much does one lab Raspberry Pi cost?",
    options: [
      "$1,500",
      "$5",
      "$500",
      "$50",
    ],
    answer: 3,
    explanation: "The Pis are ~$50 units (F063).",
    factIds: ["F063"],
    tags: ["pi.controller", "hw.pi"],
  },
  {
    id: "Q065",
    type: "mc",
    moduleId: "M05",
    difficulty: 1,
    checkpoint: "CP-M05.1",
    prompt: "Which of these is NOT a duty of the Robot Pi?",
    options: [
      "Wine card-programming emulation",
      "Camera streams",
      "Hosting Orca's MySQL database",
      "ADB routing",
    ],
    answer: 2,
    explanation: "The Pi handles ADB routing, camera streams, steppers, solenoids and Wine card programming (F065). MySQL lives with Orca on the blade's VM.",
    factIds: ["F065"],
    tags: ["pi.controller", "hw.pi"],
  },
  {
    id: "Q066",
    type: "mc",
    moduleId: "M05",
    difficulty: 1,
    prompt: "Which set of jobs does the Robot Pi handle?",
    options: [
      "ADB routing, camera streams, stepper motors, solenoids and Wine card programming",
      "Status banner colours only",
      "Jenkins builds, MySQL and Ollama",
      "Callus, Collis probes and Gort cloning",
    ],
    answer: 0,
    explanation: "The Pi's duties per the reference (F065).",
    factIds: ["F065"],
    tags: ["pi.controller", "hw.pi"],
  },
  {
    id: "Q067",
    type: "mc",
    moduleId: "M05",
    difficulty: 1,
    checkpoint: "CP-M05.1",
    prompt: "Which operating system runs on the Pi controllers?",
    options: [
      "macOS",
      "Linux",
      "Windows 10 IoT",
      "Android",
    ],
    answer: 1,
    explanation: "Linux is deployed on the lab's Raspberry Pi controllers (F019).",
    factIds: ["F019"],
    tags: ["pi.controller", "hw.pi"],
  },
  {
    id: "Q068",
    type: "mc",
    moduleId: "M05",
    difficulty: 1,
    prompt: "Why run Linux on the Pis?",
    options: [
      "LabSim devices only accept ADB from Linux",
      "It isolates hardware control loops from the corporate Windows machines",
      "Jenkins agents only run on Linux",
      "Linux unlocks the GPUs",
    ],
    answer: 1,
    explanation: "Linux on the Pis isolates the hardware control loops from corporate Windows machines (F020).",
    factIds: ["F020"],
    tags: ["pi.controller", "hw.pi"],
  },
  {
    id: "Q069",
    type: "mc",
    moduleId: "M05",
    difficulty: 1,
    checkpoint: "CP-M05.1",
    prompt: "What is Wine used for on the Pi?",
    options: [
      "Hosting Callus",
      "Running Jenkins agents",
      "Emulating the Windows-only card-programming software",
      "Running Tesseract OCR",
    ],
    answer: 2,
    explanation: "Wine emulates the Windows-only card-programming software layers on the Pi's Linux (F021). Callus runs on Windows/Minix boxes.",
    factIds: ["F021"],
    tags: ["pi.controller", "cards.wine"],
  },
  {
    id: "Q070",
    type: "tf",
    moduleId: "M05",
    difficulty: 1,
    prompt: "Wine is a compatibility layer that lets Windows-only software run on the Pi's Linux.",
    options: ["True", "False"],
    answer: 0,
    explanation: "Wine runs on the Pi Linux environments to emulate Windows-only card-programming layers (F021).",
    factIds: ["F021"],
    tags: ["pi.controller", "cards.wine"],
  },
  {
    id: "Q071",
    type: "mc",
    moduleId: "M05",
    difficulty: 1,
    checkpoint: "CP-M05.1",
    prompt: "Why was hardware control moved off the Intel NUCs?",
    options: [
      "The NUCs were too expensive",
      "Windows could not run ADB",
      "The NUCs drew an irregular 18V",
      "corporate security-monitoring packages exhausted the NUCs' disk space",
    ],
    answer: 3,
    explanation: "Aggressive corporate security monitoring packages filled the NUC disks (F067).",
    factIds: ["F067"],
    tags: ["pi.controller", "hw.nuc"],
  },
  {
    id: "Q072",
    type: "mc",
    moduleId: "M05",
    difficulty: 1,
    prompt: "Where did hardware control move after the NUC disk problem?",
    options: [
      "Raspberry Pis",
      "Minix boxes",
      "Google Cloud",
      "VMs on the GPU blade",
    ],
    answer: 0,
    explanation: "Physical hardware control migrated off the NUCs onto Raspberry Pis (F068).",
    factIds: ["F068"],
    tags: ["pi.controller", "hw.nuc"],
  },
  {
    id: "Q073",
    type: "mc",
    moduleId: "M05",
    difficulty: 1,
    prompt: "Which machines are the lab's local Windows execution boxes?",
    options: [
      "The status tablets",
      "Raspberry Pis",
      "The Jenkins VM",
      "Intel NUC and Minix boxes",
    ],
    answer: 3,
    explanation: "Intel NUC (ASUS NUC) and Minix boxes are the local Windows machines (F066).",
    factIds: ["F066"],
    tags: ["pi.controller", "hw.nuc"],
  },
  {
    id: "Q074",
    type: "order",
    moduleId: "M05",
    difficulty: 3,
    prompt: "Order the history of hardware control in the lab.",
    options: [
      "Hardware control runs on Windows Intel NUCs",
      "corporate security-monitoring packages fill the NUC disks",
      "Hardware control migrates to Raspberry Pis running Linux",
    ],
    answer: -1,
    explanation: "NUCs → corporate disk exhaustion → migration to Pis (F066, F067, F068).",
    factIds: ["F066", "F067", "F068"],
    tags: ["pi.controller", "hw.nuc"],
  },
  {
    id: "Q075",
    type: "tf",
    moduleId: "M05",
    difficulty: 1,
    prompt: "Minix boxes in the lab run Linux, like the Pis.",
    options: ["True", "False"],
    answer: 1,
    explanation: "Minix boxes, like the NUCs, are local Windows execution machines (F066).",
    factIds: ["F066"],
    tags: ["pi.controller", "hw.nuc"],
  },
  {
    id: "Q076",
    type: "tf",
    moduleId: "M05",
    difficulty: 2,
    prompt: "The Pi controllers run Windows so they can execute the card-programming software natively.",
    options: ["True", "False"],
    answer: 1,
    explanation: "The Pis run Linux (F019) and use Wine to emulate the Windows-only card-programming layers (F021).",
    factIds: ["F019", "F021"],
    tags: ["pi.controller", "hw.pi", "cards.wine"],
  },
  {
    id: "Q077",
    type: "fill",
    moduleId: "M05",
    difficulty: 2,
    prompt: "Each shelf has one of these acting as its Robot Controller. Type the two-word name.",
    accepted: ["Raspberry Pi"],
    caseInsensitive: true,
    explanation: "A Raspberry Pi operates as the Robot Pi / Robot Controller on each shelf (F064). Case-insensitive.",
    factIds: ["F064"],
    tags: ["pi.controller", "hw.pi"],
  },
]);
