/**
 * Quiz bank — M06 Orca Architecture & the Five Robot Statuses (Cur §3). 41 items.
 * Transcribed from docs/design/10-curriculum.md; every answer re-verified against
 * docs/reference/REMOVED-internal-reference.md. Options are stored in the doc's canonical display order
 * (the UI reshuffles); `order` items store options in the CORRECT order; `match` pairs are the correct pairing.
 */
import type { QuizQuestion } from '../schema';
import { resolvePeople } from '../people';

export const QUIZ_M06: QuizQuestion[] = resolvePeople([
  {
    id: "Q078",
    type: "mc",
    moduleId: "M06",
    difficulty: 1,
    checkpoint: "CP-M06.1",
    prompt: "In the lab's architecture, which pairing is correct?",
    options: [
      "The Pi is the Controller; Orca is the Executor",
      "Jenkins is the Controller; Orca is the Executor",
      "uia-remote is the Controller; Jenkins is the Executor",
      "Orca is the Controller; Jenkins is the Executor",
    ],
    answer: 3,
    explanation: "Orchestrator acts as the Controller while Jenkins acts as the Executor (F098).",
    factIds: ["F098"],
    tags: ["orca.status", "arch.roles"],
  },
  {
    id: "Q079",
    type: "fill",
    moduleId: "M06",
    difficulty: 2,
    checkpoint: "CP-M06.1",
    prompt: "\"Orca\" is short for which system? Type its full name.",
    accepted: ["Orchestrator", "Orchestrator (Orca)"],
    caseInsensitive: true,
    explanation: "Orca is the Orchestrator (F036). Case-insensitive.",
    factIds: ["F036"],
    tags: ["orca.status", "arch.roles"],
  },
  {
    id: "Q080",
    type: "mc",
    moduleId: "M06",
    difficulty: 2,
    prompt: "How is Orca built?",
    options: [
      "A Node.js app in Docker",
      "Go microservices on GCP",
      "An on-premise Spring Boot monolith",
      "A Jenkins plugin",
    ],
    answer: 2,
    explanation: "Orca is an on-premise Spring Boot monolith (F037, F002).",
    factIds: ["F037", "F002"],
    tags: ["orca.status", "arch.stack"],
  },
  {
    id: "Q081",
    type: "mc",
    moduleId: "M06",
    difficulty: 1,
    prompt: "Which framework provides Orca's backend and REST API endpoints?",
    options: [
      "Express",
      "Django",
      "Spring Boot",
      "Ruby on Rails",
    ],
    answer: 2,
    explanation: "Spring Boot is the backend framework for the Orchestrator monolith and its REST endpoints (F002).",
    factIds: ["F002"],
    tags: ["orca.status", "arch.stack"],
  },
  {
    id: "Q082",
    type: "mc",
    moduleId: "M06",
    difficulty: 2,
    prompt: "What did JHipster generate for Orca?",
    options: [
      "Only the MySQL database",
      "The frontend UI, the Spring Boot REST endpoints and the MySQL schemas",
      "The Jenkins pipelines",
      "The uia-remote page objects",
    ],
    answer: 1,
    explanation: "JHipster auto-generated the frontend, REST endpoints and MySQL schemas (F004).",
    factIds: ["F003", "F004"],
    tags: ["orca.status", "arch.stack"],
  },
  {
    id: "Q083",
    type: "tf",
    moduleId: "M06",
    difficulty: 1,
    prompt: "JHipster scaffolds an application through an interactive setup questionnaire.",
    options: ["True", "False"],
    answer: 0,
    explanation: "JHipster scaffolded Orca via an interactive setup questionnaire (F003).",
    factIds: ["F003"],
    tags: ["orca.status", "arch.stack"],
  },
  {
    id: "Q084",
    type: "mc",
    moduleId: "M06",
    difficulty: 1,
    checkpoint: "CP-M06.1",
    prompt: "Which database engine backs Orca?",
    options: [
      "MySQL",
      "PostgreSQL",
      "SQLite",
      "MongoDB",
    ],
    answer: 0,
    explanation: "MySQL backs Orchestrator (F013).",
    factIds: ["F013"],
    tags: ["orca.status", "arch.stack"],
  },
  {
    id: "Q085",
    type: "mc",
    moduleId: "M06",
    difficulty: 1,
    prompt: "Where does Orca run today?",
    options: [
      "On a Raspberry Pi",
      "On Google Cloud in Docker",
      "On a local on-premise lab VM",
      "On an engineer's laptop",
    ],
    answer: 2,
    explanation: "Orca runs on an on-premise lab VM; Docker/GCP is the plan (F023).",
    factIds: ["F023"],
    tags: ["orca.status", "arch.stack", "arch.infra"],
  },
  {
    id: "Q086",
    type: "mc",
    moduleId: "M06",
    difficulty: 1,
    checkpoint: "CP-M06.1",
    prompt: "How often does Orca ping the Robot Controller on every Pi?",
    options: [
      "Every 30 seconds",
      "Only when a job starts",
      "Every hour",
      "Every 5 minutes",
    ],
    answer: 3,
    explanation: "A synchronized background thread pings every Pi every 5 minutes (F099).",
    factIds: ["F099"],
    tags: ["orca.status", "orca.healthcheck"],
  },
  {
    id: "Q087",
    type: "fill",
    moduleId: "M06",
    difficulty: 2,
    prompt: "Orca's health-check interval, in minutes. Type the number.",
    accepted: ["5", "five"],
    caseInsensitive: true,
    explanation: "Every 5 minutes (F099).",
    factIds: ["F099"],
    tags: ["orca.status", "orca.healthcheck"],
  },
  {
    id: "Q088",
    type: "mc",
    moduleId: "M06",
    difficulty: 1,
    checkpoint: "CP-M06.1",
    prompt: "Which of these is NOT one of the 5 robot statuses?",
    options: [
      "Busy",
      "Reserved",
      "Connection Failed",
      "Offline",
    ],
    answer: 0,
    explanation: "The five are Available, Unavailable, Offline, Connection Failed and Reserved (F100).",
    factIds: ["F100"],
    tags: ["orca.status"],
  },
  {
    id: "Q089",
    type: "fill",
    moduleId: "M06",
    difficulty: 2,
    prompt: "How many robot operational statuses does Orca have? Type the number.",
    accepted: ["5", "five"],
    caseInsensitive: true,
    explanation: "Exactly 5 (F100).",
    factIds: ["F100"],
    tags: ["orca.status"],
  },
  {
    id: "Q090",
    type: "mc",
    moduleId: "M06",
    difficulty: 1,
    prompt: "Which status lets general pipelines check out the robot?",
    options: [
      "Available",
      "Reserved",
      "Offline",
      "Unavailable",
    ],
    answer: 0,
    explanation: "Available means online, healthy and open to general checkouts (F101).",
    factIds: ["F101"],
    tags: ["orca.status"],
  },
  {
    id: "Q091",
    type: "mc",
    moduleId: "M06",
    difficulty: 1,
    checkpoint: "CP-M06.1",
    prompt: "How can a pipeline use a robot that is Unavailable?",
    options: [
      "It can't; Unavailable robots are never used",
      "Set DEVICE_TYPE to match the robot",
      "Ask {{jared}} to Park All",
      "Pass the robot's exact unique name in the job parameters",
    ],
    answer: 3,
    explanation: "General pipelines are blocked unless the exact unique name is passed (F102).",
    factIds: ["F102"],
    tags: ["orca.status", "orca.status.unavailable"],
  },
  {
    id: "Q092",
    type: "mc",
    moduleId: "M06",
    difficulty: 1,
    prompt: "Why do PayCore standalone rigs sit in Unavailable?",
    options: [
      "They have no Raspberry Pi",
      "They are broken",
      "They only accept Canadian cards",
      "So general tests do not overwrite their merchant profiles",
    ],
    answer: 3,
    explanation: "Unavailable isolates specialised rigs like PayCore standalone setups (F103).",
    factIds: ["F103"],
    tags: ["orca.status", "orca.status.unavailable"],
  },
  {
    id: "Q093",
    type: "tf",
    moduleId: "M06",
    difficulty: 1,
    prompt: "After an explicitly named job finishes on an Unavailable robot, the engineer must set it back to Unavailable by hand.",
    options: ["True", "False"],
    answer: 1,
    explanation: "Orca automatically resets the flag back to Unavailable (F104).",
    factIds: ["F104"],
    tags: ["orca.status", "orca.status.unavailable"],
  },
  {
    id: "Q094",
    type: "mc",
    moduleId: "M06",
    difficulty: 1,
    prompt: "{{jared}} is physically building BAYMAX and assembling its data profiles. Which status should it have?",
    options: [
      "Reserved",
      "Offline",
      "Unavailable",
      "Connection Failed",
    ],
    answer: 1,
    explanation: "Offline is the manual placeholder while a rig is being built or profiled (F105).",
    factIds: ["F105"],
    tags: ["orca.status", "orca.status.offline"],
  },
  {
    id: "Q095",
    type: "tf",
    moduleId: "M06",
    difficulty: 1,
    prompt: "Orca still pings Offline robots every 5 minutes.",
    options: ["True", "False"],
    answer: 1,
    explanation: "Orca bypasses 5-minute health checks for Offline units (F106).",
    factIds: ["F106"],
    tags: ["orca.status", "orca.status.offline", "orca.healthcheck"],
  },
  {
    id: "Q096",
    type: "mc",
    moduleId: "M06",
    difficulty: 1,
    prompt: "What sets a robot to Connection Failed?",
    options: [
      "The status banner turning yellow",
      "Any failed Jenkins build",
      "The 5-minute REST ping to its Pi drops or returns a non-200 response",
      "An engineer selects it manually",
    ],
    answer: 2,
    explanation: "Connection Failed is triggered automatically by a dropped or non-200 health ping (F107).",
    factIds: ["F107"],
    tags: ["orca.status", "orca.status.connfailed", "orca.healthcheck"],
  },
  {
    id: "Q097",
    type: "tf",
    moduleId: "M06",
    difficulty: 1,
    prompt: "A health ping that returns HTTP 502 puts the robot into Connection Failed even though the Pi answered.",
    options: ["True", "False"],
    answer: 0,
    explanation: "Any non-200 response triggers Connection Failed, not just a dropped connection (F107).",
    factIds: ["F107"],
    tags: ["orca.status", "orca.status.connfailed", "orca.healthcheck"],
  },
  {
    id: "Q098",
    type: "tf",
    moduleId: "M06",
    difficulty: 1,
    prompt: "A Connection Failed robot can still be checked out if its LabSim device is powered on.",
    options: ["True", "False"],
    answer: 1,
    explanation: "Orca blocks Connection Failed rigs from checkouts (F108).",
    factIds: ["F108"],
    tags: ["orca.status", "orca.status.connfailed"],
  },
  {
    id: "Q099",
    type: "mc",
    moduleId: "M06",
    difficulty: 1,
    prompt: "Where do you read the exact endpoint and error text for a Connection Failed robot?",
    options: [
      "The status tablet",
      "A GitHub issue",
      "The Notes section in Orca's UI",
      "The Jenkins console",
    ],
    answer: 2,
    explanation: "Orca opens a Notes section logging the endpoint attempted and the error (F109).",
    factIds: ["F109"],
    tags: ["orca.status", "orca.status.connfailed", "orca.notes"],
  },
  {
    id: "Q100",
    type: "mc",
    moduleId: "M06",
    difficulty: 1,
    prompt: "Which is a typical cause of Connection Failed?",
    options: [
      "A Minix box running Callus services went offline",
      "theme is not set to avocado",
      "Someone pushed a robot arm by hand",
      "A Pigeon JSON file is missing a comma",
    ],
    answer: 0,
    explanation: "Typical causes are a crashed Pi board or a Minix box running Callus going offline (F110).",
    factIds: ["F110"],
    tags: ["orca.status", "orca.status.connfailed"],
  },
  {
    id: "Q101",
    type: "mc",
    moduleId: "M06",
    difficulty: 1,
    checkpoint: "CP-M06.1",
    prompt: "Who receives Connection Failed escalations?",
    options: [
      "{{jared}}",
      "{{tate}}",
      "{{david}}",
      "{{morgan}}",
    ],
    answer: 0,
    explanation: "Connection Failed is escalated to {{jared}} for hardware intervention (F111).",
    factIds: ["F111"],
    tags: ["orca.status", "orca.status.connfailed", "people.roles"],
  },
  {
    id: "Q102",
    type: "mc",
    moduleId: "M06",
    difficulty: 1,
    prompt: "You are running tests locally from your workstation on EVE. Which status should EVE have?",
    options: [
      "Available",
      "Reserved",
      "Unavailable",
      "Offline",
    ],
    answer: 1,
    explanation: "Reserved is set manually by an engineer running tests locally (F112).",
    factIds: ["F112"],
    tags: ["orca.status", "orca.status.reserved"],
  },
  {
    id: "Q103",
    type: "mc",
    moduleId: "M06",
    difficulty: 1,
    prompt: "What does Reserved block?",
    options: [
      "Nothing; it is just a label",
      "Jenkins pipelines and health-check overrides",
      "Only health checks",
      "Only the tablet buttons",
    ],
    answer: 1,
    explanation: "Reserved blocks both Jenkins pipelines and health-check overrides (F113).",
    factIds: ["F113"],
    tags: ["orca.status", "orca.status.reserved"],
  },
  {
    id: "Q104",
    type: "match",
    moduleId: "M06",
    difficulty: 3,
    prompt: "Match each situation to the status it calls for.",
    pairs: [
      ["Healthy rig, open to any pipeline", "Available"],
      ["PayCore standalone rig, named jobs only", "Unavailable"],
      ["Rig still being physically built", "Offline"],
      ["Health ping returned non-200", "Connection Failed"],
      ["You are testing locally from your desk", "Reserved"],
    ],
    explanation: "Available means the robot is online, healthy and open to general pipeline checkouts. Unavailable is a strictly reserved state: general pipelines cannot check the robot out unless an engineer passes the robot's exact unique name in the job parameters. Unavailable isolates specialised rigs (such as PayCore standalone setups) so general tests do not overwrite their merchant profiles. Offline is a manual placeholder state used while engineers physically build a rig or assemble data profiles. Connection Failed is set automatically when the 5-minute REST ping to the Pi drops or returns a non-200 HTTP response. Reserved is set manually by an engineer who is running tests locally from their workstation. (F101, F102, F103, F105, F107, F112)",
    factIds: ["F101", "F102", "F105", "F107", "F112"],
    tags: ["orca.status", "orca.status.unavailable", "orca.status.offline", "orca.status.connfailed", "orca.healthcheck", "orca.status.reserved"],
  },
  {
    id: "Q105",
    type: "mc",
    moduleId: "M06",
    difficulty: 1,
    prompt: "Which component checks out a robot from Orca for a CI run?",
    options: [
      "The Raspberry Pi",
      "Jenkins",
      "The status tablet",
      "Callus",
    ],
    answer: 1,
    explanation: "Jenkins checks out a robot from Orca (F095).",
    factIds: ["F095"],
    tags: ["orca.status", "arch.flow", "jenkins.checkout"],
  },
  {
    id: "Q106",
    type: "mc",
    moduleId: "M06",
    difficulty: 1,
    prompt: "How does a running test ask for a screen tap or a card action?",
    options: [
      "A Jenkins environment variable",
      "REST calls to Orca (xy_touch, card swipe / dip / tap)",
      "SSH straight to the Pi",
      "Pressing buttons on the tablet",
    ],
    answer: 1,
    explanation: "Test runners call Orca over REST for xy_touch and card actions (F096).",
    factIds: ["F096"],
    tags: ["orca.status", "arch.flow", "orca.xytouch"],
  },
  {
    id: "Q107",
    type: "mc",
    moduleId: "M06",
    difficulty: 1,
    prompt: "Which chain is correct for card emulation?",
    options: [
      "Jenkins → Collis probe → Callus → Orca",
      "Pi → Wine → Collis probe → GPU blade",
      "Windows/Minix box running Callus → ribbon cable → Collis probe → LabSim card reader",
      "Orca → SmartStripe Probe → Pi → card reader",
    ],
    answer: 2,
    explanation: "The Callus box drives the Collis probe over a ribbon cable into the device's reader (F097).",
    factIds: ["F097"],
    tags: ["orca.status", "arch.flow", "cards.callus"],
  },
  {
    id: "Q108",
    type: "mc",
    moduleId: "M06",
    difficulty: 1,
    prompt: "Who built the custom robot-list filtering UI in Orca?",
    options: [
      "{{tate}}",
      "{{david}}",
      "{{jared}}",
      "{{morgan}}",
    ],
    answer: 0,
    explanation: "{{tate}} created the Robot list's custom UI filtering (F116).",
    factIds: ["F116"],
    tags: ["orca.status", "orca.robot", "people.roles"],
  },
  {
    id: "Q109",
    type: "mc",
    moduleId: "M06",
    difficulty: 1,
    prompt: "Orca sits between which two things?",
    options: [
      "GitHub and IntelliJ IDEA",
      "Jenkins pipelines and the physical lab robots",
      "Ollama and Tesseract",
      "Wall power and the Pis",
    ],
    answer: 1,
    explanation: "Orca is the central Controller between Jenkins pipelines and physical robots (F038).",
    factIds: ["F038"],
    tags: ["orca.status", "arch.roles"],
  },
  {
    id: "Q110",
    type: "mc",
    moduleId: "M06",
    difficulty: 1,
    prompt: "What does Jenkins inject into the test runner (uia-remote or Pigeon)?",
    options: [
      "Runtime environment variables",
      "Card definition files",
      "MySQL schemas",
      "Wine",
    ],
    answer: 0,
    explanation: "Jenkins triggers the pipeline and injects env vars into the test runner (F094).",
    factIds: ["F094"],
    tags: ["orca.status", "arch.flow"],
  },
  {
    id: "Q111",
    type: "tf",
    moduleId: "M06",
    difficulty: 1,
    prompt: "Orca's backend is written in Go.",
    options: ["True", "False"],
    answer: 1,
    explanation: "Java is the primary language for Orca and uia-remote; Go is used for the Terminal SDK (F001, F008).",
    factIds: ["F001"],
    tags: ["orca.status", "arch.stack"],
  },
  {
    id: "Q112",
    type: "order",
    moduleId: "M06",
    difficulty: 3,
    prompt: "Order a CI card-dip test from start to card read.",
    options: [
      "Jenkins triggers the pipeline and injects env vars",
      "Jenkins checks out a robot from Orca",
      "The test runner calls Orca's REST card-dip endpoint",
      "Callus on the Windows/Minix box loads the virtual card",
      "The Collis probe presents the card to the LabSim reader",
    ],
    answer: -1,
    explanation: "Jenkins (Executor) → Orca (Controller) → Callus → Collis → reader (F094–F098).",
    factIds: ["F094", "F095", "F096", "F097", "F098"],
    tags: ["orca.status", "arch.flow", "jenkins.checkout", "orca.xytouch", "cards.callus", "arch.roles"],
  },
  {
    id: "Q113",
    type: "mc",
    moduleId: "M06",
    difficulty: 2,
    prompt: "Which system is the Controller sitting between Jenkins pipelines and the physical robots?",
    options: [
      "Orca (Orchestrator)",
      "Callus",
      "Laz Automation",
      "Ubi Platform",
    ],
    answer: 0,
    explanation: "Orca, the Orchestrator, is the central Controller (F036, F038).",
    factIds: ["F036", "F038"],
    tags: ["orca.status", "arch.roles"],
  },
  {
    id: "Q114",
    type: "tf",
    moduleId: "M06",
    difficulty: 1,
    prompt: "Orca is a set of cloud microservices running on GCP.",
    options: ["True", "False"],
    answer: 1,
    explanation: "Orca is an on-premise Spring Boot monolith (F037); GCP is only a planned target (F022).",
    factIds: ["F037"],
    tags: ["orca.status", "arch.stack"],
  },
  {
    id: "Q115",
    type: "mc",
    moduleId: "M06",
    difficulty: 2,
    prompt: "You ran a job with ROBOT_NAME=rosie on ROSIE (Unavailable). The job just finished. What is ROSIE's status now?",
    options: [
      "Available",
      "Unavailable: Orca reset it automatically",
      "Reserved",
      "Offline",
    ],
    answer: 1,
    explanation: "Once an explicitly named job finishes, Orca resets the flag back to Unavailable (F104).",
    factIds: ["F104", "F102"],
    tags: ["orca.status", "orca.status.unavailable"],
  },
  {
    id: "Q116",
    type: "mc",
    moduleId: "M06",
    difficulty: 2,
    prompt: "For which status does Orca skip the 5-minute health check?",
    options: [
      "Offline",
      "Available",
      "Unavailable",
      "Reserved",
    ],
    answer: 0,
    explanation: "Orca bypasses health checks for Offline units (F106).",
    factIds: ["F106", "F105"],
    tags: ["orca.status", "orca.status.offline", "orca.healthcheck"],
  },
  {
    id: "Q117",
    type: "order",
    moduleId: "M06",
    difficulty: 3,
    prompt: "Order what happens when a Pi stops answering.",
    options: [
      "The 5-minute health ping drops or returns non-200",
      "Orca sets Connection Failed and blocks checkouts",
      "Orca's Notes section logs the endpoint attempted and the error text",
      "The engineer escalates to {{jared}} for hardware intervention",
    ],
    answer: -1,
    explanation: "Connection Failed is set automatically when the 5-minute REST ping to the Pi drops or returns a non-200 HTTP response. A Connection Failed robot is blocked from checkouts. Connection Failed opens a Notes section in the Orca UI logging the exact endpoint attempted and the error text. Connection Failed robots are escalated to {{jared}} for hardware intervention. (F107, F108, F109, F111)",
    factIds: ["F107", "F108", "F109", "F111"],
    tags: ["orca.status", "orca.status.connfailed", "orca.healthcheck", "orca.notes", "people.roles"],
  },
  {
    id: "Q118",
    type: "tf",
    moduleId: "M06",
    difficulty: 2,
    prompt: "Reserved only stops health checks; Jenkins can still check the robot out.",
    options: ["True", "False"],
    answer: 1,
    explanation: "Reserved blocks both Jenkins pipelines and health-check overrides (F113).",
    factIds: ["F113", "F112"],
    tags: ["orca.status", "orca.status.reserved"],
  },
]);
