/**
 * Quiz bank — M07 Orca Entities: Robot, Device, Device Type, URLs, Tethering & Offsets (Cur §3). 25 items.
 * Transcribed from docs/design/10-curriculum.md; every answer re-verified against
 * docs/reference/REMOVED-internal-reference.md. Options are stored in the doc's canonical display order
 * (the UI reshuffles); `order` items store options in the CORRECT order; `match` pairs are the correct pairing.
 */
import type { QuizQuestion } from '../schema';
import { resolvePeople } from '../people';

export const QUIZ_M07: QuizQuestion[] = resolvePeople([
  {
    id: "Q119",
    type: "mc",
    moduleId: "M07",
    difficulty: 1,
    checkpoint: "CP-M07.1",
    prompt: "How many core database schemas (JHipster entities) does Orca have?",
    options: [
      "7",
      "4",
      "12",
      "5",
    ],
    answer: 0,
    explanation: "Orca has 7 core database schemas (F114).",
    factIds: ["F114"],
    tags: ["orca.entities", "arch.stack"],
  },
  {
    id: "Q120",
    type: "mc",
    moduleId: "M07",
    difficulty: 1,
    prompt: "Which of these is NOT one of Orca's core schemas?",
    options: [
      "Merchant Config entity",
      "Screen Compare Image entity",
      "Jenkins Job entity",
      "Card Profile entity",
    ],
    answer: 2,
    explanation: "The 7 are Robot, Robot Creation & Configuration, Robot Capabilities, Merchant Config, Screens & Screen Locations, Card Profile and Screen Compare Image (F114).",
    factIds: ["F114"],
    tags: ["orca.entities", "arch.stack"],
  },
  {
    id: "Q121",
    type: "mc",
    moduleId: "M07",
    difficulty: 1,
    checkpoint: "CP-M07.1",
    prompt: "What is a robot's \"Name\" field in Orca?",
    options: [
      "The Pi's IP address",
      "The system identifier",
      "The display string shown on the tablet",
      "The LabSim device's serial number",
    ],
    answer: 1,
    explanation: "Name is the system identifier; Human Readable Name is the display string (F117).",
    factIds: ["F117"],
    tags: ["orca.entities", "orca.names"],
  },
  {
    id: "Q122",
    type: "mc",
    moduleId: "M07",
    difficulty: 1,
    checkpoint: "CP-M07.1",
    prompt: "Where does a robot's Human Readable Name appear?",
    options: [
      "In the GitHub repo name",
      "On the physical status tablet on the front of the enclosure",
      "As the Pi's hostname",
      "Only in the Jenkins console",
    ],
    answer: 1,
    explanation: "The Human Readable Name is pushed to the front-mounted status tablet (F118).",
    factIds: ["F118"],
    tags: ["orca.entities", "orca.names", "hw.tablet"],
  },
  {
    id: "Q123",
    type: "mc",
    moduleId: "M07",
    difficulty: 2,
    checkpoint: "CP-M07.1",
    prompt: "{{jared}} swaps JOHNNY-5's Flex 1 for a Flex 2. What is the right Orca change?",
    options: [
      "Create a new Device for the Flex 2 and relink Robot Device, keeping the old Device for rollback",
      "Change JOHNNY-5's Offsets",
      "Edit the existing Device and change its type to FLEX_2",
      "Delete JOHNNY-5 and recreate it",
    ],
    answer: 0,
    explanation: "Robot Device links to a separate Device entity so upgrades leave legacy configs intact for rollback (F119, F120).",
    factIds: ["F119", "F120"],
    tags: ["orca.entities", "orca.device"],
  },
  {
    id: "Q124",
    type: "tf",
    moduleId: "M07",
    difficulty: 1,
    prompt: "Because Robot and Device are decoupled, a hardware upgrade leaves legacy configurations intact for quick rollbacks.",
    options: ["True", "False"],
    answer: 0,
    explanation: "That is exactly why they are decoupled (F120).",
    factIds: ["F120"],
    tags: ["orca.entities", "orca.device"],
  },
  {
    id: "Q125",
    type: "mc",
    moduleId: "M07",
    difficulty: 1,
    prompt: "What does the Robot Device field point to?",
    options: [
      "A camera stream",
      "A separate Device entity",
      "A Jenkins job",
      "A Gort card file",
    ],
    answer: 1,
    explanation: "Robot Device links to a separate Device entity (F119).",
    factIds: ["F119"],
    tags: ["orca.entities", "orca.device"],
  },
  {
    id: "Q126",
    type: "mc",
    moduleId: "M07",
    difficulty: 1,
    prompt: "What does the Device Type enum store?",
    options: [
      "Card Track Data",
      "The Pi's IP address",
      "Device dimensions, layout metrics and internal string definitions",
      "Merchant credentials",
    ],
    answer: 2,
    explanation: "Device Type is an enum of dimensions, layout metrics and internal strings (F121).",
    factIds: ["F121"],
    tags: ["orca.entities", "orca.devicetype"],
  },
  {
    id: "Q127",
    type: "mc",
    moduleId: "M07",
    difficulty: 1,
    checkpoint: "CP-M07.1",
    prompt: "Why must Jenkins pipeline env vars like DEVICE_TYPE be in ALL CAPS?",
    options: [
      "They must match Orca's Device Type enum string definitions",
      "Jenkins rejects lower-case parameters",
      "It is only a style convention",
      "Linux environment variables are case-insensitive",
    ],
    answer: 0,
    explanation: "The Device Type enum dictates that env vars must be all-caps (F122).",
    factIds: ["F122"],
    tags: ["orca.entities", "orca.devicetype", "jenkins.envvars"],
  },
  {
    id: "Q128",
    type: "fill",
    moduleId: "M07",
    difficulty: 2,
    illustrative: true,
    prompt: "Type the DEVICE_TYPE value Jenkins needs for a Flex 3 in this sim (enum spelling).",
    accepted: ["FLEX_3"],
    caseInsensitive: false,
    explanation: "All caps, matching the Device Type enum (F122). Case-sensitive. (Enum spelling FLEX_3 is the sim's illustrative enum.)",
    factIds: ["F122"],
    tags: ["orca.entities", "orca.devicetype", "jenkins.envvars"],
  },
  {
    id: "Q129",
    type: "mc",
    moduleId: "M07",
    difficulty: 1,
    prompt: "The Robot ADB Service URL routes to which component?",
    options: [
      "The Jenkins VM",
      "Orca's MySQL",
      "The Pi controller",
      "The LabSim device directly on port 5555",
    ],
    answer: 2,
    explanation: "It is the Robot ADB Service URL routing to the Pi controller (F123).",
    factIds: ["F123"],
    tags: ["orca.entities", "orca.urls"],
  },
  {
    id: "Q130",
    type: "mc",
    moduleId: "M07",
    difficulty: 1,
    prompt: "A robot's Camera Stream URL is…",
    options: [
      "Always shared across all 40+ rigs",
      "Only configured for CFDs",
      "Stored in Gort",
      "Either dedicated per Pi or shared across 4 rigs",
    ],
    answer: 3,
    explanation: "Camera streams are dedicated per Pi or shared across 4 rigs (F124).",
    factIds: ["F124"],
    tags: ["orca.entities", "orca.urls", "vision.camera"],
  },
  {
    id: "Q131",
    type: "mc",
    moduleId: "M07",
    difficulty: 1,
    prompt: "Besides the ADB Service and Camera Stream URLs, which hardware-specific URLs are mapped per robot?",
    options: [
      "Health, Park and Reset",
      "Dip, Tap and Swipe",
      "PIN, Sign and Tip",
      "Print, Scan and Email",
    ],
    answer: 1,
    explanation: "URL Mappings store hardware-specific Dip, Tap and Swipe URLs (F125).",
    factIds: ["F125"],
    tags: ["orca.entities", "orca.urls"],
  },
  {
    id: "Q132",
    type: "mc",
    moduleId: "M07",
    difficulty: 1,
    checkpoint: "CP-M07.1",
    prompt: "In Orca, what makes a pipeline treat a rig as tethered?",
    options: [
      "The camera URL is shared",
      "The Human Readable Name contains \"MFD\"",
      "The device type is STATION_DUO",
      "The MFD field is populated",
    ],
    answer: 3,
    explanation: "If MFD is populated, the pipeline treats the rig as tethered (F128).",
    factIds: ["F128"],
    tags: ["orca.entities", "orca.tethered"],
  },
  {
    id: "Q133",
    type: "mc",
    moduleId: "M07",
    difficulty: 2,
    prompt: "Which is an example of a nested/tethered setup modelled in Orca?",
    options: [
      "A Flex 3 with a Collis probe",
      "Two Flex Pockets sharing a camera",
      "A Station 2 tethered to a Mini 2",
      "A Pi with a webcam",
    ],
    answer: 2,
    explanation: "Tethered configs populate MFD/CFD relations, e.g. Station 2 + Mini 2, or nested Mini 3s (F126, F127).",
    factIds: ["F126", "F127"],
    tags: ["orca.entities", "orca.tethered"],
  },
  {
    id: "Q134",
    type: "tf",
    moduleId: "M07",
    difficulty: 1,
    prompt: "USB Tethered Device Configuration populates MFD and CFD relations for nested setups.",
    options: ["True", "False"],
    answer: 0,
    explanation: "That is the purpose of the USB Tethered Device Configuration (F126).",
    factIds: ["F126"],
    tags: ["orca.entities", "orca.tethered"],
  },
  {
    id: "Q135",
    type: "mc",
    moduleId: "M07",
    difficulty: 1,
    prompt: "What were Offsets originally for?",
    options: [
      "Time-zone corrections for the health check",
      "Legacy millimetre adjustments compensating for imprecise physical limit switches",
      "ADB port offsets from 5555",
      "Pixel offsets for OCR boxes",
    ],
    answer: 1,
    explanation: "Offsets compensated for imprecise limit switches (F129).",
    factIds: ["F129"],
    tags: ["orca.entities", "orca.offsets"],
  },
  {
    id: "Q136",
    type: "mc",
    moduleId: "M07",
    difficulty: 1,
    prompt: "Why are Offsets now mostly deprecated?",
    options: [
      "{{tate}} removed the column",
      "Orca moved to GCP",
      "UI Automator 2.3 replaced them",
      "{{jared}} calibrated the lab hardware to a true (0,0) origin",
    ],
    answer: 3,
    explanation: "{{jared}}'s true (0,0) calibration made Offsets mostly deprecated (F130).",
    factIds: ["F130"],
    tags: ["orca.entities", "orca.offsets", "people.roles"],
  },
  {
    id: "Q137",
    type: "tf",
    moduleId: "M07",
    difficulty: 2,
    illustrative: true,
    prompt: "On a correctly calibrated rig, a non-zero legacy Offset is a likely cause of taps landing off-target.",
    options: ["True", "False"],
    answer: 0,
    explanation: "With hardware calibrated to true (0,0), leftover offsets shift taps; the field is mostly deprecated (F129, F130). (Lesson scenario illustrative.)",
    factIds: ["F130", "F129"],
    tags: ["orca.entities", "orca.offsets", "people.roles"],
  },
  {
    id: "Q138",
    type: "mc",
    moduleId: "M07",
    difficulty: 1,
    prompt: "What does the Robot entity track?",
    options: [
      "Only robots that are Available",
      "Jenkins build history",
      "The pool of 40+ rigs and their operational status flags",
      "Card profiles per robot",
    ],
    answer: 2,
    explanation: "Robot entity: 40+ rigs and status flags (F115).",
    factIds: ["F115"],
    tags: ["orca.entities", "orca.robot"],
  },
  {
    id: "Q139",
    type: "mc",
    moduleId: "M07",
    difficulty: 1,
    prompt: "Which of these is NOT stored in Orca's MySQL database?",
    options: [
      "Screen-coordinate tables",
      "Merchant profiles",
      "Jenkins build console logs",
      "Hardware states",
    ],
    answer: 2,
    explanation: "MySQL stores hardware states, merchant profiles and screen coordinates (F014). Build logs stay in Jenkins.",
    factIds: ["F014"],
    tags: ["orca.entities", "arch.stack"],
  },
  {
    id: "Q140",
    type: "match",
    moduleId: "M07",
    difficulty: 3,
    prompt: "Match each robot naming field to its purpose.",
    pairs: [
      ["Name", "System identifier used by Orca and pipelines"],
      ["Human Readable Name", "Display string pushed to the status tablet"],
    ],
    explanation: "A robot has a Name (system identifier) and a Human Readable Name (display string). The Human Readable Name is pushed to the physical status tablet mounted on the front of the lab enclosure. (F117, F118)",
    factIds: ["F117", "F118"],
    tags: ["orca.entities", "orca.names", "hw.tablet"],
  },
  {
    id: "Q141",
    type: "tf",
    moduleId: "M07",
    difficulty: 1,
    prompt: "Device Type is a free-text field, so any spelling works.",
    options: ["True", "False"],
    answer: 1,
    explanation: "Device Type is an enum of dimensions, layout metrics and internal strings (F121), which is why env vars must be ALL CAPS (F122).",
    factIds: ["F121"],
    tags: ["orca.entities", "orca.devicetype"],
  },
  {
    id: "Q142",
    type: "match",
    moduleId: "M07",
    difficulty: 3,
    prompt: "Match each URL mapping to what it does.",
    pairs: [
      ["Robot ADB Service URL", "Routes ADB to the Pi controller"],
      ["Camera Stream URL", "Webcam feed, dedicated per Pi or shared across 4 rigs"],
      ["Dip / Tap / Swipe URLs", "Hardware-specific card actions"],
    ],
    explanation: "URL Mappings store the Robot ADB Service URL, which routes to the Pi controller. The Camera Stream URL is either dedicated per Pi or shared across 4 rigs. URL Mappings also store the hardware-specific Dip, Tap and Swipe URLs. (F123, F124, F125)",
    factIds: ["F123", "F124", "F125"],
    tags: ["orca.entities", "orca.urls", "vision.camera"],
  },
  {
    id: "Q143",
    type: "tf",
    moduleId: "M07",
    difficulty: 2,
    prompt: "If OPTIMUS's MFD field is empty, pipelines will not treat OPTIMUS as tethered.",
    options: ["True", "False"],
    answer: 0,
    explanation: "The pipeline treats the rig as tethered only if MFD is populated (F128).",
    factIds: ["F128", "F126"],
    tags: ["orca.entities", "orca.tethered"],
  },
]);
