/**
 * Quiz bank — M08 Capabilities, Merchant Config, Laz & Ubi (Cur §3). 23 items.
 * Transcribed from docs/design/10-curriculum.md; every answer re-verified against
 * docs/reference/REMOVED-internal-reference.md. Options are stored in the doc's canonical display order
 * (the UI reshuffles); `order` items store options in the CORRECT order; `match` pairs are the correct pairing.
 */
import type { QuizQuestion } from '../schema';
import { resolvePeople } from '../people';

export const QUIZ_M08: QuizQuestion[] = resolvePeople([
  {
    id: "Q144",
    type: "mc",
    moduleId: "M08",
    difficulty: 1,
    checkpoint: "CP-M08.1",
    prompt: "Which entity controls how Orca matches pipeline requests to physical hardware?",
    options: [
      "Card Profile",
      "Screens",
      "Merchant Config",
      "Robot Capabilities",
    ],
    answer: 3,
    explanation: "The Robot Capabilities entity does the matching (F131).",
    factIds: ["F131"],
    tags: ["orca.capabilities"],
  },
  {
    id: "Q145",
    type: "mc",
    moduleId: "M08",
    difficulty: 1,
    checkpoint: "CP-M08.1",
    prompt: "In dynamic JSON lookups, where are the capabilities defined?",
    options: [
      "On the status tablet",
      "Hardcoded in the pipeline script",
      "In config.properties",
      "As JSON metadata inside individual test definitions, parsed at runtime",
    ],
    answer: 3,
    explanation: "Dynamic lookups read JSON metadata from each test definition at runtime (F132).",
    factIds: ["F132"],
    tags: ["orca.capabilities"],
  },
  {
    id: "Q146",
    type: "mc",
    moduleId: "M08",
    difficulty: 1,
    checkpoint: "CP-M08.1",
    prompt: "Which lookup style do traditional UI Automator suites use?",
    options: [
      "Ubi Platform routing",
      "Dynamic JSON metadata in each test",
      "Non-dynamic: capabilities hardcoded inside the pipeline script",
      "Laz OOBE profiles",
    ],
    answer: 2,
    explanation: "Traditional UIA suites hardcode capabilities in the pipeline script (F134).",
    factIds: ["F134"],
    tags: ["orca.capabilities"],
  },
  {
    id: "Q147",
    type: "match",
    moduleId: "M08",
    difficulty: 3,
    prompt: "Match each lookup style to its user and location.",
    pairs: [
      ["Dynamic JSON lookup", "SDK frameworks; JSON metadata in the test definition"],
      ["Non-dynamic lookup", "Traditional UI Automator suites; hardcoded in the pipeline script"],
    ],
    explanation: "F132 vs F134.",
    factIds: ["F132", "F134"],
    tags: ["orca.capabilities"],
  },
  {
    id: "Q148",
    type: "mc",
    moduleId: "M08",
    difficulty: 1,
    prompt: "Who oversees the SDK frameworks that use dynamic JSON capability lookups?",
    options: [
      "{{jared}}",
      "{{tate}}",
      "{{morgan}}",
      "{{david}}",
    ],
    answer: 3,
    explanation: "{{david}} oversees them (F133).",
    factIds: ["F133"],
    tags: ["orca.capabilities", "people.roles"],
  },
  {
    id: "Q149",
    type: "tf",
    moduleId: "M08",
    difficulty: 1,
    prompt: "Contact Canada automation scripts on the Westers test beds use only dynamic lookups.",
    options: ["True", "False"],
    answer: 1,
    explanation: "Both lookup methods are used interchangeably for Contact Canada scripts (F135).",
    factIds: ["F135"],
    tags: ["orca.capabilities"],
  },
  {
    id: "Q150",
    type: "mc",
    moduleId: "M08",
    difficulty: 1,
    prompt: "What data format do Orca's runtime capability lookups use?",
    options: [
      "JSON",
      "CSV",
      "YAML",
      "XML",
    ],
    answer: 0,
    explanation: "JSON is used for runtime capability lookups (F011).",
    factIds: ["F011"],
    tags: ["orca.capabilities", "arch.stack"],
  },
  {
    id: "Q151",
    type: "mc",
    moduleId: "M08",
    difficulty: 2,
    checkpoint: "CP-M08.1",
    prompt: "The Merchant Config table doesn't show App Secret. Why, and what do you do?",
    options: [
      "It is not stored in Orca at all",
      "The table has display limits; click Edit on the row to see every field",
      "It is hidden for security; ask {{tate}} to query MySQL",
      "Export the table to CSV",
    ],
    answer: 1,
    explanation: "Due to UI table display limits you must click Edit on a row (F137).",
    factIds: ["F136", "F137"],
    tags: ["orca.capabilities", "orca.merchant"],
  },
  {
    id: "Q152",
    type: "mc",
    moduleId: "M08",
    difficulty: 1,
    prompt: "What does the Merchant Config entity store?",
    options: [
      "Gort card files",
      "Robot health history",
      "Merchant account parameters",
      "Button coordinates",
    ],
    answer: 2,
    explanation: "Merchant Config stores merchant account parameters (F136).",
    factIds: ["F136"],
    tags: ["orca.capabilities", "orca.merchant"],
  },
  {
    id: "Q153",
    type: "mc",
    moduleId: "M08",
    difficulty: 1,
    checkpoint: "CP-M08.1",
    prompt: "Which three fields did {{tate}} add to Merchant Config?",
    options: [
      "Client ID, Token, Region",
      "Merchant ID, PIN, Serial",
      "App ID, App Secret, API Key",
      "Username, Password, MFA Code",
    ],
    answer: 2,
    explanation: "{{tate}} extended Merchant Config with App ID, App Secret and API Key (F138).",
    factIds: ["F138"],
    tags: ["orca.capabilities", "orca.merchant", "people.roles"],
  },
  {
    id: "Q154",
    type: "mc",
    moduleId: "M08",
    difficulty: 1,
    prompt: "Why were App ID, App Secret and API Key added?",
    options: [
      "So the tablet can display them",
      "So Tesseract can read them",
      "So pipelines can export them as runtime environment variables for the Go SDK",
      "So Laz can type them into the setup wizard",
    ],
    answer: 2,
    explanation: "Pipelines export them as env vars for the Go SDK (F139).",
    factIds: ["F139"],
    tags: ["orca.capabilities", "orca.merchant", "go.sdk"],
  },
  {
    id: "Q155",
    type: "tf",
    moduleId: "M08",
    difficulty: 2,
    prompt: "{{tate}} added App ID, App Secret and API Key to Merchant Config so the Go SDK pipelines could receive them as environment variables.",
    options: ["True", "False"],
    answer: 0,
    explanation: "{{tate}} extended Merchant Config with App ID, App Secret and API Key fields. Pipelines export App ID, App Secret and API Key as runtime environment variables for the Go SDK. (F138, F139)",
    factIds: ["F138", "F139"],
    tags: ["orca.capabilities", "orca.merchant", "people.roles", "go.sdk"],
  },
  {
    id: "Q156",
    type: "mc",
    moduleId: "M08",
    difficulty: 2,
    prompt: "How is the Terminal SDK supported and tested?",
    options: [
      "Only through uia-remote page objects",
      "Only on GCP",
      "Through Laz OOBE runs",
      "Custom extensions in Orca; tested through Pigeon and mobile runners",
    ],
    answer: 3,
    explanation: "Go SDK support via custom Orca extensions, tested through Pigeon and mobile runners (F008, F009).",
    factIds: ["F008", "F009"],
    tags: ["orca.capabilities", "go.sdk"],
  },
  {
    id: "Q157",
    type: "mc",
    moduleId: "M08",
    difficulty: 1,
    prompt: "Which language is the Terminal SDK written in?",
    options: [
      "Java",
      "Python",
      "Kotlin",
      "Go (Golang)",
    ],
    answer: 3,
    explanation: "Go is used for the Terminal SDK (F008).",
    factIds: ["F008"],
    tags: ["orca.capabilities", "go.sdk"],
  },
  {
    id: "Q158",
    type: "mc",
    moduleId: "M08",
    difficulty: 1,
    checkpoint: "CP-M08.1",
    prompt: "What is Laz Automation?",
    options: [
      "A card emulator",
      "A lazy-loading Java library",
      "A Jenkins plugin for skipping builds",
      "An automated provisioning framework running a zero-touch OOBE routine",
    ],
    answer: 3,
    explanation: "Laz runs a zero-touch Out-of-Box Experience routine (F046).",
    factIds: ["F046"],
    tags: ["orca.capabilities", "laz.oobe"],
  },
  {
    id: "Q159",
    type: "fill",
    moduleId: "M08",
    difficulty: 2,
    prompt: "OOBE stands for Out-of-___ Experience. Type the missing word.",
    accepted: ["Box"],
    caseInsensitive: true,
    explanation: "Out-of-Box Experience (F046). Case-insensitive.",
    factIds: ["F046"],
    tags: ["orca.capabilities", "laz.oobe"],
  },
  {
    id: "Q160",
    type: "mc",
    moduleId: "M08",
    difficulty: 1,
    prompt: "Which is NOT part of Laz's OOBE routine?",
    options: [
      "Re-flashing the Pi's Linux image",
      "Wiping local caches",
      "De-provisioning the hardware",
      "Stepping through the setup wizard",
    ],
    answer: 0,
    explanation: "Laz de-provisions, wipes caches, steps the wizard and swaps merchants (F047).",
    factIds: ["F047"],
    tags: ["orca.capabilities", "laz.oobe"],
  },
  {
    id: "Q161",
    type: "mc",
    moduleId: "M08",
    difficulty: 1,
    prompt: "When can Laz swap merchants?",
    options: [
      "Only overnight",
      "Never; merchants are fixed per robot",
      "Only by hand on the tablet",
      "Mid-suite",
    ],
    answer: 3,
    explanation: "Laz swaps merchants mid-suite (F047).",
    factIds: ["F047"],
    tags: ["orca.capabilities", "laz.oobe"],
  },
  {
    id: "Q162",
    type: "order",
    moduleId: "M08",
    difficulty: 3,
    prompt: "Order Laz's OOBE merchant swap.",
    options: [
      "De-provision the hardware",
      "Wipe local caches",
      "Step through the setup wizard",
      "Device comes up on the new merchant",
    ],
    answer: -1,
    explanation: "F047 (order of the reference's list).",
    factIds: ["F047"],
    tags: ["orca.capabilities", "laz.oobe"],
  },
  {
    id: "Q163",
    type: "mc",
    moduleId: "M08",
    difficulty: 1,
    prompt: "Which internal platform routes jobs that dynamically switch merchant configurations?",
    options: [
      "Ubi Platform",
      "Callus",
      "Gort",
      "LSTR",
    ],
    answer: 0,
    explanation: "Ubi Platform is used when jobs dynamically switch merchant configs (F051).",
    factIds: ["F051"],
    tags: ["orca.capabilities", "ubi.routing"],
  },
  {
    id: "Q164",
    type: "tf",
    moduleId: "M08",
    difficulty: 1,
    prompt: "Merchant Config works alongside Laz Automation for dynamic OOBE merchant switching.",
    options: ["True", "False"],
    answer: 0,
    explanation: "Merchant Config works alongside Laz Automation for dynamic OOBE merchant switching. (F140)",
    factIds: ["F140"],
    tags: ["orca.capabilities", "orca.merchant", "laz.oobe"],
  },
  {
    id: "Q165",
    type: "tf",
    moduleId: "M08",
    difficulty: 1,
    prompt: "The Robot Capabilities entity decides which physical robot a pipeline request is matched to.",
    options: ["True", "False"],
    answer: 0,
    explanation: "The Robot Capabilities entity controls how Orca matches pipeline requests to physical hardware. (F131)",
    factIds: ["F131"],
    tags: ["orca.capabilities"],
  },
  {
    id: "Q166",
    type: "fill",
    moduleId: "M08",
    difficulty: 2,
    prompt: "Merchant Config's table hides some columns. Which button do you click on a row to see every field? Type it.",
    accepted: ["Edit"],
    caseInsensitive: true,
    explanation: "Click Edit on the row (F137). Case-insensitive.",
    factIds: ["F137"],
    tags: ["orca.capabilities", "orca.merchant"],
  },
]);
