/**
 * Quiz bank — M09 Screens, Screen Locations & xy_touch (ADB Bots vs Physical Bots) (Cur §3). 22 items.
 * Transcribed from docs/design/10-curriculum.md; every answer re-verified against
 * docs/reference/REMOVED-internal-reference.md. Options are stored in the doc's canonical display order
 * (the UI reshuffles); `order` items store options in the CORRECT order; `match` pairs are the correct pairing.
 */
import type { QuizQuestion } from '../schema';
import { resolvePeople } from '../people';

export const QUIZ_M09: QuizQuestion[] = resolvePeople([
  {
    id: "Q167",
    type: "mc",
    moduleId: "M09",
    difficulty: 1,
    checkpoint: "CP-M09.1",
    prompt: "What does the Screens entity map?",
    options: [
      "Exact button coordinates in millimetres",
      "Discrete UI layouts within a transaction flow, relative to the target device architecture",
      "Webcam images of each screen",
      "Card files for each screen",
    ],
    answer: 1,
    explanation: "Screens map layouts in a flow per device architecture, e.g. a cash-discount tender prompt (F141).",
    factIds: ["F141"],
    tags: ["orca.screens"],
  },
  {
    id: "Q168",
    type: "mc",
    moduleId: "M09",
    difficulty: 1,
    checkpoint: "CP-M09.1",
    prompt: "Screen Locations store button positions in which unit?",
    options: [
      "Density-independent pixels (dp)",
      "Millimetres",
      "Pixels",
      "Inches",
    ],
    answer: 1,
    explanation: "Relative X and Y in millimetres (F142).",
    factIds: ["F142"],
    tags: ["orca.screens"],
  },
  {
    id: "Q169",
    type: "tf",
    moduleId: "M09",
    difficulty: 1,
    prompt: "A cash-discount tender selection prompt is an example of a Screen in Orca.",
    options: ["True", "False"],
    answer: 0,
    explanation: "The reference uses exactly that example (F141).",
    factIds: ["F141"],
    tags: ["orca.screens"],
  },
  {
    id: "Q170",
    type: "mc",
    moduleId: "M09",
    difficulty: 1,
    checkpoint: "CP-M09.1",
    prompt: "What does a script pass to Orca's xy_touch endpoint?",
    options: [
      "Raw pixel X and Y",
      "A card profile name",
      "A screen name and a button string",
      "The robot's serial number and a PIN",
    ],
    answer: 2,
    explanation: "Scripts call xy_touch with a screen name and a button string (F143).",
    factIds: ["F143"],
    tags: ["orca.screens", "orca.xytouch"],
  },
  {
    id: "Q171",
    type: "mc",
    moduleId: "M09",
    difficulty: 1,
    prompt: "After the xy_touch lookup, what does the Pi fire?",
    options: [
      "Always an ADB touch",
      "Either an electronic ADB touch or a physical mechanical probe tap",
      "Always a physical tap",
      "A GIMP selection",
    ],
    answer: 1,
    explanation: "Orca instructs the Pi to fire an ADB touch or a physical probe tap (F144).",
    factIds: ["F144"],
    tags: ["orca.screens", "orca.xytouch"],
  },
  {
    id: "Q172",
    type: "order",
    moduleId: "M09",
    difficulty: 3,
    checkpoint: "CP-M09.1",
    prompt: "Order an xy_touch from script to screen.",
    options: [
      "Test runner calls Orca's xy_touch with a screen name and button",
      "Orca looks up the button's millimetre coordinates",
      "Orca instructs the Raspberry Pi",
      "The Pi fires an ADB touch or a physical probe tap",
    ],
    answer: -1,
    explanation: "The test runner calls Orca over REST for xy_touch and for card swipe / dip / tap. Scripts call Orca's xy_touch REST endpoint with a screen name and a button string. For xy_touch, Orca looks up the millimetre coordinates and instructs the Pi to fire either an electronic ADB touch or a physical mechanical probe tap. (F096, F143, F144)",
    factIds: ["F143", "F144", "F096"],
    tags: ["orca.screens", "orca.xytouch", "arch.flow"],
  },
  {
    id: "Q173",
    type: "mc",
    moduleId: "M09",
    difficulty: 1,
    prompt: "Can an ADB bot enter a PIN?",
    options: [
      "Yes, if Offsets are set",
      "Only on the Compact",
      "No; ADB bots are purely programmatic and cannot physically touch the screen or enter PINs",
      "Yes, with adb shell input text",
    ],
    answer: 2,
    explanation: "ADB bots are purely programmatic: they cannot physically touch the screen or enter PINs. (F217)",
    factIds: ["F217"],
    tags: ["orca.screens", "bots.types"],
  },
  {
    id: "Q174",
    type: "mc",
    moduleId: "M09",
    difficulty: 1,
    checkpoint: "CP-M09.1",
    prompt: "ADB bots are restricted to which merchant configurations?",
    options: [
      "PayCore standalone merchants",
      "Station Duo merchants only",
      "Configurations that bypass PIN security",
      "Canadian merchants only",
    ],
    answer: 2,
    explanation: "ADB bots only run merchant configs that bypass PIN security (F218).",
    factIds: ["F218"],
    tags: ["orca.screens", "bots.types"],
  },
  {
    id: "Q175",
    type: "mc",
    moduleId: "M09",
    difficulty: 1,
    prompt: "Why does a Canadian payment workflow need a physical bot?",
    options: [
      "The Compact has no ADB at all",
      "Westers beds have no Pis",
      "Interac cards cannot be emulated",
      "Canadian flows mandate physical PIN entry",
    ],
    answer: 3,
    explanation: "Physical bots are required for Canadian flows, which mandate physical PIN entry (F220).",
    factIds: ["F220"],
    tags: ["orca.screens", "bots.types", "bots.pin"],
  },
  {
    id: "Q176",
    type: "mc",
    moduleId: "M09",
    difficulty: 1,
    prompt: "Besides Canadian PIN flows, what else requires a physical/interactive bot?",
    options: [
      "Every MFD",
      "Any device with a printer",
      "Every Flex",
      "ADB-blind displays",
    ],
    answer: 3,
    explanation: "Physical bots are required for ADB-blind displays (F221).",
    factIds: ["F221"],
    tags: ["orca.screens", "bots.types"],
  },
  {
    id: "Q177",
    type: "mc",
    moduleId: "M09",
    difficulty: 1,
    prompt: "What do physical/interactive bots have that ADB bots lack?",
    options: [
      "An Orca record",
      "A Raspberry Pi",
      "Mechanical touch probes",
      "An ADB connection",
    ],
    answer: 2,
    explanation: "Physical bots are equipped with mechanical touch probes (F219).",
    factIds: ["F219"],
    tags: ["orca.screens", "bots.types"],
  },
  {
    id: "Q178",
    type: "tf",
    moduleId: "M09",
    difficulty: 2,
    prompt: "TARS (an ADB bot) is a good choice for a Canadian Interac PIN test.",
    options: ["True", "False"],
    answer: 1,
    explanation: "ADB bots cannot enter PINs (F217) and Canadian flows require physical PIN entry on a physical bot (F219, F220).",
    factIds: ["F217", "F219", "F220"],
    tags: ["orca.screens", "bots.types", "bots.pin"],
  },
  {
    id: "Q179",
    type: "mc",
    moduleId: "M09",
    difficulty: 1,
    prompt: "What did adding the \"scan for receipt\" QR code do to the receipt screen?",
    options: [
      "Shifted the buttons down by a few millimetres",
      "Moved the buttons up by 10 pixels",
      "Renamed every button",
      "Removed the Print button",
    ],
    answer: 0,
    explanation: "The QR feature shifted buttons down a few mm (F213).",
    factIds: ["F213"],
    tags: ["orca.screens", "receipt.qr"],
  },
  {
    id: "Q180",
    type: "mc",
    moduleId: "M09",
    difficulty: 1,
    checkpoint: "CP-M09.1",
    prompt: "How long were the lab's coordinates broken after the QR change?",
    options: [
      "2 weeks",
      "4 hours",
      "48 hours",
      "5 minutes",
    ],
    answer: 2,
    explanation: "Ruler-measured coordinates were broken for 48 hours (F214).",
    factIds: ["F214"],
    tags: ["orca.screens", "receipt.qr", "people.roles"],
  },
  {
    id: "Q181",
    type: "mc",
    moduleId: "M09",
    difficulty: 1,
    prompt: "Who merged the coordinate PR that ended the QR breakage?",
    options: [
      "{{david}}",
      "{{morgan}}",
      "{{jared}}",
      "{{tate}}",
    ],
    answer: 2,
    explanation: "{{jared}} merged the coordinate PR (F214).",
    factIds: ["F214"],
    tags: ["orca.screens", "receipt.qr", "people.roles"],
  },
  {
    id: "Q182",
    type: "tf",
    moduleId: "M09",
    difficulty: 1,
    prompt: "Before the QR incident, the lab's screen coordinates had been measured with a ruler.",
    options: ["True", "False"],
    answer: 0,
    explanation: "The shift broke \"ruler-measured coordinates\" (F214).",
    factIds: ["F214"],
    tags: ["orca.screens", "receipt.qr", "people.roles"],
  },
  {
    id: "Q183",
    type: "mc",
    moduleId: "M09",
    difficulty: 1,
    prompt: "What did the QR feature add to the receipt menu?",
    options: [
      "A conditional 5th menu option",
      "A pop-up dialog",
      "A 6th option",
      "A permanent 4th option",
    ],
    answer: 0,
    explanation: "It introduced a conditional 5th option (F215).",
    factIds: ["F215"],
    tags: ["orca.screens", "receipt.maps"],
  },
  {
    id: "Q184",
    type: "mc",
    moduleId: "M09",
    difficulty: 1,
    checkpoint: "CP-M09.1",
    prompt: "How does Orca now handle receipt screens?",
    options: [
      "One map per merchant",
      "Separate coordinate maps for 4-option and 5-option receipt screens across every device profile",
      "An OCR check before every tap",
      "One map plus an Offset when the QR shows",
    ],
    answer: 1,
    explanation: "Orca maintains separate 4- and 5-option maps per device profile (F216).",
    factIds: ["F216"],
    tags: ["orca.screens", "receipt.maps"],
  },
  {
    id: "Q185",
    type: "fill",
    moduleId: "M09",
    difficulty: 2,
    prompt: "Orca keeps separate receipt coordinate maps for 4 options and for ___ options. Type the number.",
    accepted: ["5", "five"],
    caseInsensitive: true,
    explanation: "4-option and 5-option maps (F215, F216).",
    factIds: ["F216", "F215"],
    tags: ["orca.screens", "receipt.maps"],
  },
  {
    id: "Q186",
    type: "mc",
    moduleId: "M09",
    difficulty: 2,
    prompt: "Screen Location millimetre coordinates line up with the physical screen because the gantry's origin is set by…",
    options: [
      "The webcam's auto-focus",
      "Limit switches calibrated to (0,0)",
      "The device's ADB density",
      "Tablet calibration on boot",
    ],
    answer: 1,
    explanation: "Limit switches define (0,0) (F082); coordinates are relative mm (F142).",
    factIds: ["F082", "F142"],
    tags: ["orca.screens", "hw.rigbom", "hw.motion"],
  },
  {
    id: "Q187",
    type: "mc",
    moduleId: "M09",
    difficulty: 2,
    prompt: "Why did robots across the lab start missing buttons when the receipt QR feature shipped?",
    options: [
      "Jenkins lost its environment variables",
      "The QR code blinded the webcams",
      "Buttons shifted down a few millimetres, invalidating the ruler-measured coordinates",
      "The Pis crashed under the new firmware",
    ],
    answer: 2,
    explanation: "Adding a \"scan for receipt\" QR code feature shifted buttons down by a few millimetres. The QR shift broke ruler-measured coordinates across the lab for 48 hours until {{jared}} merged a coordinate PR. (F213, F214)",
    factIds: ["F213", "F214"],
    tags: ["orca.screens", "receipt.qr", "people.roles"],
  },
  {
    id: "Q188",
    type: "tf",
    moduleId: "M09",
    difficulty: 2,
    prompt: "DATA (an ADB bot) can safely be put on a merchant that requires PIN entry.",
    options: ["True", "False"],
    answer: 1,
    explanation: "ADB bots cannot enter PINs (F217), so they are restricted to merchants that bypass PIN security (F218).",
    factIds: ["F218", "F217"],
    tags: ["orca.screens", "bots.types"],
  },
]);
