/**
 * Quiz bank — M11 Jenkins: The Executor (Cur §3). 11 items.
 * Transcribed from docs/design/10-curriculum.md; every answer re-verified against
 * docs/reference/REMOVED-internal-reference.md. Options are stored in the doc's canonical display order
 * (the UI reshuffles); `order` items store options in the CORRECT order; `match` pairs are the correct pairing.
 */
import type { QuizQuestion } from '../schema';
import { resolvePeople } from '../people';

export const QUIZ_M11: QuizQuestion[] = resolvePeople([
  {
    id: "Q214",
    type: "mc",
    moduleId: "M11",
    difficulty: 1,
    checkpoint: "CP-M11.1",
    prompt: "What is Jenkins' role name in the lab architecture?",
    options: [
      "Executor",
      "Router",
      "Runner",
      "Controller",
    ],
    answer: 0,
    explanation: "Jenkins is the CI/CD execution engine, the Executor (F015).",
    factIds: ["F015"],
    tags: ["jenkins", "jenkins.envvars", "arch.roles"],
  },
  {
    id: "Q215",
    type: "mc",
    moduleId: "M11",
    difficulty: 1,
    checkpoint: "CP-M11.1",
    prompt: "Which two things does Jenkins do for a test pipeline?",
    options: [
      "Triggers it and injects runtime environment variables",
      "Stores coordinates and card profiles",
      "Pings the Pis and parks robots",
      "Compiles device firmware",
    ],
    answer: 0,
    explanation: "Jenkins triggers test pipelines and injects runtime environment variables into them. (F016)",
    factIds: ["F016"],
    tags: ["jenkins", "jenkins.envvars"],
  },
  {
    id: "Q216",
    type: "mc",
    moduleId: "M11",
    difficulty: 1,
    checkpoint: "CP-M11.1",
    prompt: "How are legacy Jenkins jobs organised?",
    options: [
      "By platform: Java jobs separated from iOS jobs",
      "By date created",
      "By team",
      "By robot name",
    ],
    answer: 0,
    explanation: "Jenkins organises legacy jobs by platform, separating Java jobs from iOS jobs. (F017)",
    factIds: ["F017"],
    tags: ["jenkins", "jenkins.folders"],
  },
  {
    id: "Q217",
    type: "mc",
    moduleId: "M11",
    difficulty: 1,
    checkpoint: "CP-M11.1",
    prompt: "During a CI run, where do the config.properties values come from?",
    options: [
      "Orca pushes the file to the device",
      "The status tablet",
      "A committed config.properties file per robot",
      "Jenkins injects them dynamically",
    ],
    answer: 3,
    explanation: "Jenkins injects these dynamically during CI (F189).",
    factIds: ["F189"],
    tags: ["jenkins", "uia.config"],
  },
  {
    id: "Q218",
    type: "tf",
    moduleId: "M11",
    difficulty: 1,
    prompt: "DEVICE_TYPE=flex_3 works fine because Orca lower-cases the enum.",
    options: ["True", "False"],
    answer: 1,
    explanation: "Env vars must be ALL CAPS to match the Device Type enum (F122).",
    factIds: ["F122"],
    tags: ["jenkins", "orca.devicetype", "jenkins.envvars"],
  },
  {
    id: "Q219",
    type: "mc",
    moduleId: "M11",
    difficulty: 1,
    prompt: "Before a CI test touches hardware, what does Jenkins do with Orca?",
    options: [
      "Checks out a robot",
      "Copies Orca's database",
      "Sets the robot Offline",
      "Reserves the robot permanently",
    ],
    answer: 0,
    explanation: "Jenkins checks out a robot from Orca (F095).",
    factIds: ["F095"],
    tags: ["jenkins", "arch.flow", "jenkins.checkout"],
  },
  {
    id: "Q220",
    type: "mc",
    moduleId: "M11",
    difficulty: 1,
    checkpoint: "CP-M11.1",
    illustrative: true,
    prompt: "A Jenkins job must run on ROSIE, which is Unavailable. What must the job parameters contain?",
    options: [
      "ROSIE's exact unique robot name (e.g. ROBOT_NAME=rosie)",
      "DEVICE_TYPE=FLEX_POCKET only",
      "Nothing; Jenkins ignores Unavailable",
      "FORCE=true",
    ],
    answer: 0,
    explanation: "Unavailable robots only accept jobs that pass their exact unique name (F102). (Parameter name ROBOT_NAME is illustrative.)",
    factIds: ["F102"],
    tags: ["jenkins", "orca.status.unavailable"],
  },
  {
    id: "Q221",
    type: "mc",
    moduleId: "M11",
    difficulty: 2,
    prompt: "Which runtime environment variables does a Go SDK pipeline export from Merchant Config?",
    options: [
      "Offsets X and Y",
      "Serial, theme and kernelType",
      "Track Data and card path",
      "App ID, App Secret and API Key",
    ],
    answer: 3,
    explanation: "Pipelines export App ID / App Secret / API Key as env vars for the Go SDK (F139).",
    factIds: ["F139", "F016"],
    tags: ["jenkins", "orca.merchant", "go.sdk", "jenkins.envvars"],
  },
  {
    id: "Q222",
    type: "mc",
    moduleId: "M11",
    difficulty: 1,
    prompt: "Into which components does Jenkins inject environment variables?",
    options: [
      "The Raspberry Pis",
      "MySQL",
      "The test runners (uia-remote or Pigeon)",
      "The status tablets",
    ],
    answer: 2,
    explanation: "In the execution flow, Jenkins triggers the pipeline and injects environment variables into the test runner (uia-remote or Pigeon). (F094)",
    factIds: ["F094"],
    tags: ["jenkins", "arch.flow"],
  },
  {
    id: "Q223",
    type: "mc",
    moduleId: "M11",
    difficulty: 1,
    prompt: "Which Pigeon/Jenkins runner is rarely touched, even though its Go SDK testing is active?",
    options: [
      "REST",
      "iOS",
      "Windows",
      "Android",
    ],
    answer: 1,
    explanation: "The iOS test runner is rarely touched, though iOS Go testing is active (F203).",
    factIds: ["F203"],
    tags: ["jenkins", "pigeon.lstr"],
  },
  {
    id: "Q224",
    type: "fill",
    moduleId: "M11",
    difficulty: 2,
    prompt: "Fill the gap: \"Orca is the Controller; Jenkins is the ________.\"",
    accepted: ["Executor"],
    caseInsensitive: true,
    explanation: "Jenkins = Executor (F015, F098). Case-insensitive.",
    factIds: ["F015", "F098"],
    tags: ["jenkins", "jenkins.envvars", "arch.roles"],
  },
]);
