/**
 * Quiz bank — M12 ADB on Port 5444 (Cur §3). 8 items.
 * Transcribed from docs/design/10-curriculum.md; every answer re-verified against
 * docs/reference/REMOVED-internal-reference.md. Options are stored in the doc's canonical display order
 * (the UI reshuffles); `order` items store options in the CORRECT order; `match` pairs are the correct pairing.
 */
import type { QuizQuestion } from '../schema';
import { resolvePeople } from '../people';

export const QUIZ_M12: QuizQuestion[] = resolvePeople([
  // Correction vs Cur §3: explanation: 8080 marked illustrative; 5037 clarified as the local ADB server port
  {
    id: "Q225",
    type: "mc",
    moduleId: "M12",
    difficulty: 1,
    checkpoint: "CP-M12.1",
    prompt: "Which TCP port does the lab's ADB use?",
    options: [
      "5037",
      "5444",
      "5555",
      "8080",
    ],
    answer: 1,
    explanation: "The lab runs ADB over port 5444 (F026). 5555 is the standard ADB default (F199); 5037 is the port of the workstation's own ADB server; 8080 is the sim's Orca/Jenkins HTTP port (illustrative).",
    factIds: ["F026"],
    tags: ["adb.port"],
  },
  {
    id: "Q226",
    type: "fill",
    moduleId: "M12",
    difficulty: 2,
    checkpoint: "CP-M12.1",
    prompt: "Complete the command: adb connect 10.42.30.32:____",
    accepted: ["5444"],
    caseInsensitive: true,
    explanation: "Lab ADB uses 5444 (F026).",
    factIds: ["F026"],
    tags: ["adb.port"],
  },
  {
    id: "Q227",
    type: "mc",
    moduleId: "M12",
    difficulty: 1,
    checkpoint: "CP-M12.1",
    prompt: "What is the standard ADB default TCP port?",
    options: [
      "5555",
      "22",
      "5037",
      "5444",
    ],
    answer: 0,
    explanation: "Standard ADB defaults to 5555 (F199).",
    factIds: ["F199"],
    tags: ["adb.port", "uia.config"],
  },
  {
    id: "Q228",
    type: "mc",
    moduleId: "M12",
    difficulty: 1,
    checkpoint: "CP-M12.1",
    prompt: "Which ADB capability lets you find a button's bounds on screen?",
    options: [
      "adb reboot",
      "logcat",
      "Inspecting the XML UI hierarchy (uiautomator dump)",
      "adb install",
    ],
    answer: 2,
    explanation: "ADB inspects XML UI hierarchies to locate elements (F024).",
    factIds: ["F024"],
    tags: ["adb.port", "adb.usage"],
  },
  {
    id: "Q229",
    type: "mc",
    moduleId: "M12",
    difficulty: 1,
    prompt: "Which command dispatches a programmatic tap at X,Y?",
    options: [
      "adb push tap X Y",
      "adb shell click X Y",
      "adb shell input tap X Y",
      "adb tap X Y",
    ],
    answer: 2,
    explanation: "ADB dispatches programmatic touch events, e.g. input tap (F025).",
    factIds: ["F025"],
    tags: ["adb.port", "adb.usage"],
  },
  {
    id: "Q230",
    type: "tf",
    moduleId: "M12",
    difficulty: 1,
    prompt: "ADB is a command-line tool.",
    options: ["True", "False"],
    answer: 0,
    explanation: "Android Debug Bridge is a command-line tool (F024).",
    factIds: ["F024"],
    tags: ["adb.port", "adb.usage"],
  },
  {
    id: "Q231",
    type: "order",
    moduleId: "M12",
    difficulty: 3,
    checkpoint: "CP-M12.1",
    prompt: "Order the steps to tap the Register icon on TARS with ADB.",
    options: [
      "adb connect 10.42.30.32:5444",
      "adb shell uiautomator dump",
      "Read the Register node's bounds in the XML",
      "adb shell input tap at the bounds' centre",
    ],
    answer: -1,
    explanation: "Connect on 5444 (F026), dump the XML hierarchy (F024), then dispatch a tap (F025).",
    factIds: ["F025", "F024"],
    tags: ["adb.port", "adb.usage"],
  },
  {
    id: "Q232",
    type: "tf",
    moduleId: "M12",
    difficulty: 2,
    prompt: "In the lab, \"adb connect 10.42.30.32\" with no port will reach the device because ADB defaults to 5444.",
    options: ["True", "False"],
    answer: 1,
    explanation: "ADB defaults to 5555 (F199); lab devices listen on 5444 (F026), so the bare connect is refused.",
    factIds: ["F026", "F199"],
    tags: ["adb.port", "uia.config"],
  },
]);
