/**
 * Quiz bank — M13 uia-remote: Structure & the Page Object Model (Cur §3). 42 items.
 * Transcribed from docs/design/10-curriculum.md; every answer re-verified against
 * docs/reference/REMOVED-internal-reference.md. Options are stored in the doc's canonical display order
 * (the UI reshuffles); `order` items store options in the CORRECT order; `match` pairs are the correct pairing.
 */
import type { QuizQuestion } from '../schema';
import { resolvePeople } from '../people';

export const QUIZ_M13: QuizQuestion[] = resolvePeople([
  {
    id: "Q233",
    type: "mc",
    moduleId: "M13",
    difficulty: 1,
    checkpoint: "CP-M13.1",
    prompt: "Which framework powers uia-remote?",
    options: [
      "Espresso",
      "Selenium",
      "Android UI Automator",
      "Appium",
    ],
    answer: 2,
    explanation: "UI Automator is Google's native instrumentation framework used inside uia-remote (F005).",
    factIds: ["F005"],
    tags: ["uia.pom"],
  },
  {
    id: "Q234",
    type: "mc",
    moduleId: "M13",
    difficulty: 1,
    checkpoint: "CP-M13.1",
    prompt: "Which UI Automator version does uia-remote use?",
    options: [
      "1.0",
      "3.0",
      "2.2",
      "2.3",
    ],
    answer: 3,
    explanation: "Version 2.3 specifically (F006).",
    factIds: ["F006"],
    tags: ["uia.pom", "uia.v23"],
  },
  // Correction vs Cur §3: accept "v2.3"
  {
    id: "Q235",
    type: "fill",
    moduleId: "M13",
    difficulty: 2,
    prompt: "Type the UI Automator version that added native dual-screen element tracking.",
    accepted: ["2.3", "v2.3"],
    caseInsensitive: true,
    explanation: "UIA 2.3 adds native dual-screen element location tracking (F006, F007).",
    factIds: ["F006", "F007"],
    tags: ["uia.pom", "uia.v23"],
  },
  {
    id: "Q236",
    type: "mc",
    moduleId: "M13",
    difficulty: 1,
    prompt: "uia-remote's project layout mirrors which build-structure standard?",
    options: [
      "Make",
      "Bazel",
      "Apache Maven",
      "Ant",
    ],
    answer: 2,
    explanation: "The Android project layout mirrors Apache Maven (F010).",
    factIds: ["F010"],
    tags: ["uia.pom", "uia.layout"],
  },
  {
    id: "Q237",
    type: "mc",
    moduleId: "M13",
    difficulty: 1,
    prompt: "What is the team's primary IDE?",
    options: [
      "Android Studio",
      "VS Code",
      "Eclipse",
      "IntelliJ IDEA",
    ],
    answer: 3,
    explanation: "IntelliJ IDEA (F027).",
    factIds: ["F027"],
    tags: ["uia.pom", "tools.intellij"],
  },
  {
    id: "Q238",
    type: "mc",
    moduleId: "M13",
    difficulty: 1,
    prompt: "Which of these is NOT something the team uses IntelliJ IDEA for?",
    options: [
      "Executing test suites",
      "Importing repositories",
      "Drawing bounding boxes on device screenshots",
      "Configuring local properties",
    ],
    answer: 2,
    explanation: "IntelliJ imports repos, configures local properties and runs suites (F028); bounding boxes are drawn in GIMP (F030).",
    factIds: ["F028"],
    tags: ["uia.pom", "tools.intellij"],
  },
  {
    id: "Q239",
    type: "mc",
    moduleId: "M13",
    difficulty: 1,
    prompt: "Under which path is uia-remote's source organised?",
    options: [
      "tests/ at the repo root",
      "runners/",
      "src/main/java only",
      "app/src/",
    ],
    answer: 3,
    explanation: "Standard Android/Maven structure under app/src/ (F163).",
    factIds: ["F163"],
    tags: ["uia.pom", "uia.layout"],
  },
  {
    id: "Q240",
    type: "mc",
    moduleId: "M13",
    difficulty: 1,
    checkpoint: "CP-M13.1",
    prompt: "Which folder do QA engineers never modify?",
    options: [
      "androidTest",
      "pageobjects",
      "main",
      "test",
    ],
    answer: 2,
    explanation: "main is reserved for production/application registration code (F164).",
    factIds: ["F164"],
    tags: ["uia.pom", "uia.layout"],
  },
  {
    id: "Q241",
    type: "mc",
    moduleId: "M13",
    difficulty: 1,
    checkpoint: "CP-M13.1",
    prompt: "Where does the multi-device execution runner live?",
    options: [
      "test",
      "testactions",
      "main",
      "androidTest",
    ],
    answer: 0,
    explanation: "test holds local unit tests and the multi-device runner scripts (F165).",
    factIds: ["F165"],
    tags: ["uia.pom", "uia.layout"],
  },
  {
    id: "Q242",
    type: "mc",
    moduleId: "M13",
    difficulty: 1,
    prompt: "What lives in androidTest?",
    options: [
      "Local unit tests that run on the laptop only",
      "Production registration code",
      "Jenkins pipeline scripts",
      "Instrumented tests that execute on Android hardware",
    ],
    answer: 3,
    explanation: "androidTest houses instrumented tests on Android hardware (F166).",
    factIds: ["F166"],
    tags: ["uia.pom", "uia.layout"],
  },
  {
    id: "Q243",
    type: "match",
    moduleId: "M13",
    difficulty: 3,
    checkpoint: "CP-M13.1",
    prompt: "Match each location to its contents.",
    pairs: [
      ["androidTest/databases", "Database connection and query logic"],
      ["androidTest/pageobjects", "Page Object Model classes for device screens"],
      ["androidTest/testactions", "Test classes and assertions that chain page-object methods"],
      ["test", "Local unit tests and the multi-device runner"],
    ],
    explanation: "The androidTest package databases holds database connection and query logic. The androidTest package pageobjects holds the Page Object Model classes representing individual device screens. The androidTest package testactions holds test classes and logical assertions that string page-object methods together. app/src/test houses local unit tests and the multi-device execution runner scripts. (F167, F168, F169, F165)",
    factIds: ["F167", "F168", "F169", "F165"],
    tags: ["uia.pom", "uia.packages", "uia.layout"],
  },
  {
    id: "Q244",
    type: "fill",
    moduleId: "M13",
    difficulty: 2,
    prompt: "androidTest is split into how many packages? Type the number.",
    accepted: ["3", "three"],
    caseInsensitive: true,
    explanation: "databases, pageobjects, testactions (F166).",
    factIds: ["F166"],
    tags: ["uia.pom", "uia.layout"],
  },
  {
    id: "Q245",
    type: "mc",
    moduleId: "M13",
    difficulty: 1,
    prompt: "You write TaxTest, which strings HomeScreen and RegisterHomeScreen methods together with assertions. Which package?",
    options: [
      "testactions",
      "pageobjects",
      "main",
      "databases",
    ],
    answer: 0,
    explanation: "testactions holds test classes and assertions (F169).",
    factIds: ["F169"],
    tags: ["uia.pom", "uia.packages"],
  },
  {
    id: "Q246",
    type: "mc",
    moduleId: "M13",
    difficulty: 1,
    prompt: "You create LockScreen.java, a class representing one device screen. Which package?",
    options: [
      "testactions",
      "pageobjects",
      "test",
      "databases",
    ],
    answer: 1,
    explanation: "pageobjects holds POM classes for screens (F168).",
    factIds: ["F168"],
    tags: ["uia.pom", "uia.packages"],
  },
  {
    id: "Q247",
    type: "mc",
    moduleId: "M13",
    difficulty: 1,
    prompt: "By design, how many Android devices can UI Automator talk to at once?",
    options: [
      "Unlimited",
      "One",
      "Four",
      "Two",
    ],
    answer: 1,
    explanation: "Google designed UI Automator to talk to only one device at a time (F170).",
    factIds: ["F170"],
    tags: ["uia.pom", "uia.multidevice"],
  },
  {
    id: "Q248",
    type: "mc",
    moduleId: "M13",
    difficulty: 1,
    checkpoint: "CP-M13.1",
    prompt: "How does uia-remote control an MFD and a CFD in one test?",
    options: [
      "An ADB broadcast reaches both devices at once",
      "The runner in test targets methods sequentially across device handles: Device A runs Method X, focus shifts to Device B for Method Y, then loops back",
      "Two UI Automator instances run in parallel threads",
      "OCR reads the CFD",
    ],
    answer: 1,
    explanation: "Multi-device trick: screen definitions live in androidTest, the runner lives in test, and the runner targets methods sequentially across device handles (Device A / MFD runs Method X, focus shifts to Device B / CFD for Method Y, then loops back). (F171)",
    factIds: ["F171"],
    tags: ["uia.pom", "uia.multidevice"],
  },
  {
    id: "Q249",
    type: "tf",
    moduleId: "M13",
    difficulty: 2,
    prompt: "uia-remote's multi-device trick keeps the screen definitions in androidTest and the runner in test.",
    options: ["True", "False"],
    answer: 0,
    explanation: "Multi-device trick: screen definitions live in androidTest, the runner lives in test, and the runner targets methods sequentially across device handles (Device A / MFD runs Method X, focus shifts to Device B / CFD for Method Y, then loops back). (F171)",
    factIds: ["F171", "F170"],
    tags: ["uia.pom", "uia.multidevice"],
  },
  {
    id: "Q250",
    type: "mc",
    moduleId: "M13",
    difficulty: 1,
    prompt: "In uia-remote, what gets its own Java class?",
    options: [
      "Each physical device",
      "Every screen, pop-up or window",
      "Only full-screen apps",
      "Each test run",
    ],
    answer: 1,
    explanation: "Every screen, pop-up or window has its own class, e.g. HomeScreen, LockScreen, NavigationBar, RegisterHomeScreen (F172).",
    factIds: ["F172"],
    tags: ["uia.pom"],
  },
  {
    id: "Q251",
    type: "tf",
    moduleId: "M13",
    difficulty: 1,
    prompt: "NavigationBar is a valid example of a uia-remote screen class.",
    options: ["True", "False"],
    answer: 0,
    explanation: "The reference lists HomeScreen, LockScreen, NavigationBar and RegisterHomeScreen (F172).",
    factIds: ["F172"],
    tags: ["uia.pom"],
  },
  {
    id: "Q252",
    type: "mc",
    moduleId: "M13",
    difficulty: 1,
    prompt: "Every screen class extends which class?",
    options: [
      "BaseTest",
      "Activity",
      "UiDevice",
      "TestCase",
    ],
    answer: 0,
    explanation: "Every screen class extends BaseTest. (F173)",
    factIds: ["F173"],
    tags: ["uia.pom"],
  },
  {
    id: "Q253",
    type: "mc",
    moduleId: "M13",
    difficulty: 1,
    prompt: "What does BaseTest provide?",
    options: [
      "Global setup, teardown and instance variables",
      "Database queries",
      "The multi-device runner",
      "Element locators",
    ],
    answer: 0,
    explanation: "BaseTest provides global setup, teardown and instance variables. (F174)",
    factIds: ["F174"],
    tags: ["uia.pom"],
  },
  {
    id: "Q254",
    type: "mc",
    moduleId: "M13",
    difficulty: 1,
    prompt: "What goes in Zone 1 of a screen class?",
    options: [
      "config.properties values",
      "Element locators: UI elements unique to that view",
      "Assertions",
      "Helper and action methods",
    ],
    answer: 1,
    explanation: "Zone 1 of a screen class holds the Element Locators: declared UI elements unique to that view. (F175)",
    factIds: ["F175"],
    tags: ["uia.pom"],
  },
  {
    id: "Q255",
    type: "mc",
    moduleId: "M13",
    difficulty: 1,
    prompt: "Where are device-specific behaviours abstracted in a screen class?",
    options: [
      "The testactions package",
      "config.properties",
      "Zone 1 locators",
      "Zone 2 helper/action methods",
    ],
    answer: 3,
    explanation: "Zone 2 of a screen class holds the Helper/Action Methods, where device-specific behaviours are abstracted. (F176)",
    factIds: ["F176"],
    tags: ["uia.pom"],
  },
  {
    id: "Q256",
    type: "match",
    moduleId: "M13",
    difficulty: 3,
    prompt: "Match each zone to its contents.",
    pairs: [
      ["Zone 1", "Element locators unique to the view"],
      ["Zone 2", "Helper/action methods, including device-specific behaviour"],
    ],
    explanation: "Zone 1 of a screen class holds the Element Locators: declared UI elements unique to that view. Zone 2 of a screen class holds the Helper/Action Methods, where device-specific behaviours are abstracted. (F175, F176)",
    factIds: ["F175", "F176"],
    tags: ["uia.pom"],
  },
  {
    id: "Q257",
    type: "mc",
    moduleId: "M13",
    difficulty: 1,
    checkpoint: "CP-M13.1",
    prompt: "On a Flex, open(\"Register\") scrolls…",
    options: [
      "Diagonally",
      "Horizontally",
      "Vertically",
      "Not at all",
    ],
    answer: 2,
    explanation: "Vertical on Flex; horizontal on Mini or Station (F177).",
    factIds: ["F177"],
    tags: ["uia.pom", "uia.scroll"],
  },
  {
    id: "Q258",
    type: "tf",
    moduleId: "M13",
    difficulty: 1,
    prompt: "On a Mini or a Station, open(String appName) scrolls horizontally.",
    options: ["True", "False"],
    answer: 0,
    explanation: "open(String appName) uses vertical scrolling on Flex devices and horizontal scrolling on Mini or Station devices. (F177)",
    factIds: ["F177"],
    tags: ["uia.pom", "uia.scroll"],
  },
  {
    id: "Q259",
    type: "mc",
    moduleId: "M13",
    difficulty: 1,
    prompt: "What problem does waitForScreen() prevent?",
    options: [
      "ADB port collisions",
      "OCR typos",
      "The wrong theme loading",
      "UI Automator clicking buttons that have not finished rendering",
    ],
    answer: 3,
    explanation: "waitForScreen() pauses until all elements render (F178).",
    factIds: ["F178"],
    tags: ["uia.pom", "uia.sync"],
  },
  {
    id: "Q260",
    type: "mc",
    moduleId: "M13",
    difficulty: 1,
    prompt: "What does isScreenPresent() return?",
    options: [
      "A list of elements",
      "A screenshot",
      "A boolean: whether that screen is currently in focus",
      "Nothing (void)",
    ],
    answer: 2,
    explanation: "isScreenPresent() returns a boolean indicating whether that specific screen is currently in focus. (F179)",
    factIds: ["F179"],
    tags: ["uia.pom", "uia.sync"],
  },
  {
    id: "Q261",
    type: "mc",
    moduleId: "M13",
    difficulty: 1,
    checkpoint: "CP-M13.1",
    prompt: "Which two methods are mandatory on every screen class?",
    options: [
      "setUp() and tearDown()",
      "open() and close()",
      "findElement() and click()",
      "waitForScreen() and isScreenPresent()",
    ],
    answer: 3,
    explanation: "waitForScreen() and isScreenPresent() are mandatory on every screen class. (F180)",
    factIds: ["F180"],
    tags: ["uia.pom", "uia.sync"],
  },
  {
    id: "Q262",
    type: "tf",
    moduleId: "M13",
    difficulty: 2,
    prompt: "A new screen class that only implements waitForScreen() meets the uia-remote rules.",
    options: ["True", "False"],
    answer: 1,
    explanation: "Both waitForScreen() and isScreenPresent() are mandatory (F180).",
    factIds: ["F180", "F179"],
    tags: ["uia.pom", "uia.sync"],
  },
  {
    id: "Q263",
    type: "mc",
    moduleId: "M13",
    difficulty: 2,
    prompt: "What does uia-remote automate?",
    options: [
      "Only REST endpoints",
      "Only iOS apps",
      "Only standalone Flex devices",
      "Both standalone devices and tethered multi-device setups across native LabSim apps",
    ],
    answer: 3,
    explanation: "uia-remote is the team's modern Java / UI Automator test repository. uia-remote automates both standalone devices and tethered multi-device setups across native LabSim apps. (F039, F040)",
    factIds: ["F039", "F040"],
    tags: ["uia.pom", "arch.repos"],
  },
  {
    id: "Q264",
    type: "tf",
    moduleId: "M13",
    difficulty: 1,
    prompt: "uia-remote is the team's modern Java / UI Automator repository.",
    options: ["True", "False"],
    answer: 0,
    explanation: "uia-remote is the team's modern Java / UI Automator test repository. (F039)",
    factIds: ["F039"],
    tags: ["uia.pom", "arch.repos"],
  },
  {
    id: "Q265",
    type: "mc",
    moduleId: "M13",
    difficulty: 1,
    prompt: "Why was uia-remote created?",
    options: [
      "Pigeon was too slow",
      "No prior framework could automate native tethered setups (Station-to-Mini, Mini-to-Mini, Station Duo)",
      "Jenkins required a new framework",
      "To replace Orca",
    ],
    answer: 1,
    explanation: "The presenter ({{morgan}} in-game) created uia-remote because no prior framework could automate native tethered setups: Station-to-Mini, Mini-to-Mini and Station Duo. (F159)",
    factIds: ["F159"],
    tags: ["uia.pom", "uia.history", "people.roles"],
  },
  {
    id: "Q266",
    type: "mc",
    moduleId: "M13",
    difficulty: 1,
    prompt: "What is the primary programming language for Orca and uia-remote?",
    options: [
      "Python",
      "Go",
      "Kotlin",
      "Java",
    ],
    answer: 3,
    explanation: "Java (Oracle Java) powers both (F001).",
    factIds: ["F001"],
    tags: ["uia.pom", "arch.stack"],
  },
  {
    id: "Q267",
    type: "mc",
    moduleId: "M13",
    difficulty: 1,
    prompt: "Where are the team's repositories hosted for branches and pull requests?",
    options: [
      "Perforce",
      "GitHub",
      "Bitbucket",
      "GitLab",
    ],
    answer: 1,
    explanation: "GitHub hosts Gort, uia-remote and pigeon (F018).",
    factIds: ["F018"],
    tags: ["uia.pom", "arch.repos", "tools.github"],
  },
  {
    id: "Q268",
    type: "tf",
    moduleId: "M13",
    difficulty: 1,
    prompt: "Android UI Automator is Google's native Android instrumentation framework.",
    options: ["True", "False"],
    answer: 0,
    explanation: "UI Automator is Google's native instrumentation framework, used inside uia-remote (F005).",
    factIds: ["F005"],
    tags: ["uia.pom"],
  },
  {
    id: "Q269",
    type: "tf",
    moduleId: "M13",
    difficulty: 1,
    prompt: "Android Studio is the team's primary IDE.",
    options: ["True", "False"],
    answer: 1,
    explanation: "IntelliJ IDEA is the primary IDE (F027).",
    factIds: ["F027"],
    tags: ["uia.pom", "tools.intellij"],
  },
  {
    id: "Q270",
    type: "tf",
    moduleId: "M13",
    difficulty: 1,
    prompt: "uia-remote can only automate standalone devices; tethered setups still need Pigeon.",
    options: ["True", "False"],
    answer: 1,
    explanation: "uia-remote automates both standalone and tethered multi-device setups (F040).",
    factIds: ["F040"],
    tags: ["uia.pom", "arch.repos"],
  },
  {
    id: "Q271",
    type: "tf",
    moduleId: "M13",
    difficulty: 2,
    prompt: "QA engineers routinely add new page objects under app/src/main.",
    options: ["True", "False"],
    answer: 1,
    explanation: "main is never modified by QA (F164); page objects go in androidTest/pageobjects (F168) under app/src/ (F163).",
    factIds: ["F163", "F164", "F168"],
    tags: ["uia.pom", "uia.layout", "uia.packages"],
  },
  {
    id: "Q272",
    type: "mc",
    moduleId: "M13",
    difficulty: 1,
    prompt: "Where does database connection and query logic live in uia-remote?",
    options: [
      "main",
      "androidTest/databases",
      "androidTest/pageobjects",
      "test",
    ],
    answer: 1,
    explanation: "The androidTest package databases holds database connection and query logic. (F167)",
    factIds: ["F167"],
    tags: ["uia.pom", "uia.packages"],
  },
  {
    id: "Q273",
    type: "fill",
    moduleId: "M13",
    difficulty: 2,
    prompt: "Every screen class extends which base class? Type its name exactly.",
    accepted: ["BaseTest"],
    caseInsensitive: false,
    explanation: "F173. Case-sensitive.",
    factIds: ["F173"],
    tags: ["uia.pom"],
  },
  {
    id: "Q274",
    type: "tf",
    moduleId: "M13",
    difficulty: 1,
    prompt: "waitForScreen() pauses execution until all UI elements finish rendering.",
    options: ["True", "False"],
    answer: 0,
    explanation: "waitForScreen() pauses execution threads until all UI elements finish rendering, so UI Automator never clicks unrendered buttons. (F178)",
    factIds: ["F178"],
    tags: ["uia.pom", "uia.sync"],
  },
]);
