/**
 * Quiz bank — M14 config.properties & the Tethered Tax Test (Cur §3). 33 items.
 * Transcribed from docs/design/10-curriculum.md; every answer re-verified against
 * docs/reference/REMOVED-internal-reference.md. Options are stored in the doc's canonical display order
 * (the UI reshuffles); `order` items store options in the CORRECT order; `match` pairs are the correct pairing.
 */
import type { QuizQuestion } from '../schema';
import { resolvePeople } from '../people';

export const QUIZ_M14: QuizQuestion[] = resolvePeople([
  {
    id: "Q275",
    type: "mc",
    moduleId: "M14",
    difficulty: 1,
    checkpoint: "CP-M14.1",
    prompt: "Running locally from a laptop, how do you configure the test target?",
    options: [
      "Orca pushes the file to your laptop",
      "Edit config.properties manually",
      "Jenkins injects it for you",
      "Set it on the status tablet",
    ],
    answer: 1,
    explanation: "Locally, engineers configure config.properties manually (F188).",
    factIds: ["F188"],
    tags: ["uia.config"],
  },
  {
    id: "Q276",
    type: "fill",
    moduleId: "M14",
    difficulty: 2,
    checkpoint: "CP-M14.1",
    prompt: "Which value must runType have for multi-device testing? Type it exactly.",
    accepted: ["tethered"],
    caseInsensitive: false,
    explanation: "runType=tethered (F190). Case-sensitive.",
    factIds: ["F190"],
    tags: ["uia.config"],
  },
  {
    id: "Q277",
    type: "mc",
    moduleId: "M14",
    difficulty: 1,
    prompt: "What does merchantFacingDeviceIp hold?",
    options: [
      "Orca's IP",
      "The local network IP of the MFD terminal",
      "The Pi's IP",
      "The CFD's IP",
    ],
    answer: 1,
    explanation: "merchantFacingDeviceIp is the local network IP of the MFD terminal. (F191)",
    factIds: ["F191"],
    tags: ["uia.config"],
  },
  {
    id: "Q278",
    type: "mc",
    moduleId: "M14",
    difficulty: 1,
    prompt: "What does customerFacingDeviceIp hold?",
    options: [
      "The local network IP of the CFD terminal",
      "The webcam's IP",
      "The Callus box's IP",
      "The MFD's IP",
    ],
    answer: 0,
    explanation: "customerFacingDeviceIp is the local network IP of the CFD terminal. (F192)",
    factIds: ["F192"],
    tags: ["uia.config"],
  },
  {
    id: "Q279",
    type: "mc",
    moduleId: "M14",
    difficulty: 1,
    checkpoint: "CP-M14.1",
    prompt: "On a Station Duo, how are the MFD and CFD IPs set?",
    options: [
      "MFD set to 127.0.0.1",
      "CFD set to the Pi's IP",
      "CFD left blank",
      "Both to the exact same IP address",
    ],
    answer: 3,
    explanation: "On a Station Duo both IPs are the exact same address (F193).",
    factIds: ["F193"],
    tags: ["uia.config"],
  },
  {
    id: "Q280",
    type: "tf",
    moduleId: "M14",
    difficulty: 1,
    prompt: "On a Station Duo you leave customerFacingDeviceIp empty because the CFD isn't on ADB.",
    options: ["True", "False"],
    answer: 1,
    explanation: "Both IPs are set to the same address (F193).",
    factIds: ["F193"],
    tags: ["uia.config"],
  },
  {
    id: "Q281",
    type: "mc",
    moduleId: "M14",
    difficulty: 1,
    prompt: "What is serial in config.properties?",
    options: [
      "The robot's Orca name",
      "The Jenkins build number",
      "The Pi's serial number",
      "The hardware serial number of the primary terminal",
    ],
    answer: 3,
    explanation: "serial is the hardware serial number of the primary terminal. (F194)",
    factIds: ["F194"],
    tags: ["uia.config"],
  },
  {
    id: "Q282",
    type: "mc",
    moduleId: "M14",
    difficulty: 1,
    prompt: "Which values does deviceType take in config.properties?",
    options: [
      "avocado or classic",
      "FLEX_3, MINI_3, STATION_2",
      "Mini, Flex or Station (the form factor)",
      "5444 or 5555",
    ],
    answer: 2,
    explanation: "deviceType is the form factor (Mini, Flex, Station) governing layout/scroll logic (F195).",
    factIds: ["F195"],
    tags: ["uia.config"],
  },
  {
    id: "Q283",
    type: "mc",
    moduleId: "M14",
    difficulty: 2,
    prompt: "What does config.properties' deviceType govern?",
    options: [
      "The tablet colour",
      "Which port ADB uses",
      "Layout and scroll logic",
      "The merchant account",
    ],
    answer: 2,
    explanation: "deviceType governs layout/scroll logic, e.g. vertical vs horizontal scrolling in open() (F195, F177).",
    factIds: ["F195", "F177"],
    tags: ["uia.config", "uia.scroll"],
  },
  {
    id: "Q284",
    type: "fill",
    moduleId: "M14",
    difficulty: 2,
    checkpoint: "CP-M14.1",
    prompt: "theme is locked to which value? Type it exactly.",
    accepted: ["avocado"],
    caseInsensitive: false,
    explanation: "theme=avocado; legacy toggles are deprecated (F196). Case-sensitive.",
    factIds: ["F196"],
    tags: ["uia.config"],
  },
  {
    id: "Q285",
    type: "tf",
    moduleId: "M14",
    difficulty: 1,
    prompt: "Legacy theme toggles are still supported; avocado is merely the default.",
    options: ["True", "False"],
    answer: 1,
    explanation: "theme is locked strictly to avocado; legacy toggles are deprecated (F196).",
    factIds: ["F196"],
    tags: ["uia.config"],
  },
  {
    id: "Q286",
    type: "fill",
    moduleId: "M14",
    difficulty: 2,
    checkpoint: "CP-M14.1",
    prompt: "kernelType is locked to which value? Type it exactly.",
    accepted: ["CPA"],
    caseInsensitive: false,
    explanation: "kernelType=CPA (F197). Case-sensitive.",
    factIds: ["F197"],
    tags: ["uia.config"],
  },
  {
    id: "Q287",
    type: "mc",
    moduleId: "M14",
    difficulty: 1,
    prompt: "What do CPA and SPA stand for?",
    options: [
      "CPA = Core Payments Application; it replaces SPA = Secure Processor Application",
      "CPA = Customer Payment Adapter; SPA = Secure PIN Agent",
      "CPA = Card Processing Agent; SPA = Standard Payment API",
      "CPA = LabSim Pay App; SPA = Single Page App",
    ],
    answer: 0,
    explanation: "kernelType is locked strictly to CPA (Core Payments Application), which replaces the legacy SPA (Secure Processor Application). (F197)",
    factIds: ["F197"],
    tags: ["uia.config"],
  },
  {
    id: "Q288",
    type: "fill",
    moduleId: "M14",
    difficulty: 2,
    checkpoint: "CP-M14.1",
    prompt: "portNumber is locked to which value? Type the number.",
    accepted: ["5444"],
    caseInsensitive: true,
    explanation: "portNumber=5444 (F198).",
    factIds: ["F198"],
    tags: ["uia.config", "adb.port"],
  },
  {
    id: "Q289",
    type: "mc",
    moduleId: "M14",
    difficulty: 2,
    prompt: "Which config.properties line is correct for the lab?",
    options: [
      "portNumber=8080",
      "portNumber=5037",
      "portNumber=5555",
      "portNumber=5444",
    ],
    answer: 3,
    explanation: "Locked to 5444 (F198); 5555 is the ADB default (F199).",
    factIds: ["F198", "F199"],
    tags: ["uia.config", "adb.port"],
  },
  {
    id: "Q290",
    type: "mc",
    moduleId: "M14",
    difficulty: 1,
    checkpoint: "CP-M14.1",
    prompt: "Why is the lab not on port 5555?",
    options: [
      "Jenkins already uses 5555",
      "corporate blocks 5555",
      "The ADB default caused office collisions where scripts connected to and controlled coworkers' desk devices",
      "The Pis cannot open 5555",
    ],
    answer: 2,
    explanation: "Using 5555 caused severe office port collisions in which automated scripts connected to and controlled coworkers' desk devices. (F200)",
    factIds: ["F200"],
    tags: ["uia.config", "adb.port"],
  },
  {
    id: "Q291",
    type: "tf",
    moduleId: "M14",
    difficulty: 1,
    prompt: "Port 5555 caused collisions in which automated scripts controlled coworkers' desk devices.",
    options: ["True", "False"],
    answer: 0,
    explanation: "Using 5555 caused severe office port collisions in which automated scripts connected to and controlled coworkers' desk devices. (F200)",
    factIds: ["F200"],
    tags: ["uia.config", "adb.port"],
  },
  {
    id: "Q292",
    type: "mc",
    moduleId: "M14",
    difficulty: 1,
    prompt: "Which is NOT among the additional config.properties keys described?",
    options: [
      "The active robot's registration name",
      "Device unlock passcodes",
      "Backend testing environment targets",
      "GPU count",
    ],
    answer: 3,
    explanation: "Extras are unlock passcodes, backend env targets and the robot's registration name (F201).",
    factIds: ["F201"],
    tags: ["uia.config"],
  },
  {
    id: "Q293",
    type: "tf",
    moduleId: "M14",
    difficulty: 1,
    prompt: "During CI, engineers must commit config.properties with the right IPs for each robot.",
    options: ["True", "False"],
    answer: 1,
    explanation: "Jenkins injects these values dynamically during CI runs (F189).",
    factIds: ["F189"],
    tags: ["uia.config"],
  },
  {
    id: "Q294",
    type: "mc",
    moduleId: "M14",
    difficulty: 1,
    prompt: "How does every uia-remote test begin and end?",
    options: [
      "It starts on LockScreen and ends on RegisterHomeScreen",
      "It starts from the last screen and ends anywhere",
      "It reboots both devices",
      "It starts explicitly from HomeScreen; a teardown forces the hardware back to HomeScreen",
    ],
    answer: 3,
    explanation: "Every test starts explicitly from HomeScreen, and a teardown routine forces the hardware back to HomeScreen at completion. (F182)",
    factIds: ["F182"],
    tags: ["uia.config", "uia.taxtest"],
  },
  {
    id: "Q295",
    type: "tf",
    moduleId: "M14",
    difficulty: 1,
    prompt: "A teardown routine forces the hardware back to HomeScreen at the end of every test.",
    options: ["True", "False"],
    answer: 0,
    explanation: "Every test starts explicitly from HomeScreen, and a teardown routine forces the hardware back to HomeScreen at completion. (F182)",
    factIds: ["F182"],
    tags: ["uia.config", "uia.taxtest"],
  },
  {
    id: "Q296",
    type: "order",
    moduleId: "M14",
    difficulty: 3,
    checkpoint: "CP-M14.1",
    prompt: "Order the Tax test.",
    options: [
      "MFD_O1: open Register, add \"Tax Item 5\", click \"Review Order\"",
      "Orca routes to Callus to load a simulated swipe card",
      "CFD_O1: assert subtotal, calculated tax and grand total",
      "MFD_O2: click \"Pay\" and \"Charge\"",
      "Payment prompt finalised on the Customer display",
    ],
    answer: -1,
    explanation: "Tax test Step 1 (MFD_O1): on the Merchant display, open the Register app, add \"Tax Item 5\" and click \"Review Order\". In Tax test Step 1 a backend call goes to Orchestrator, which routes to the Callers/Collos (Callus) microservice to load a simulated swipe card. Tax test Step 2 (CFD_O1): control shifts to the Customer display, which asserts subtotal, calculated tax and grand total. Tax test Step 3 (MFD_O2): control returns to the Merchant display to click \"Pay\" and \"Charge\". Tax test Step 4: the payment prompt is finalised on the Customer display. (F183, F184, F185, F186, F187)",
    factIds: ["F183", "F184", "F185", "F186", "F187"],
    tags: ["uia.config", "uia.taxtest", "cards.callus"],
  },
  {
    id: "Q297",
    type: "fill",
    moduleId: "M14",
    difficulty: 2,
    prompt: "Which item does the Tax test add in Step 1? Type it exactly.",
    accepted: ["Tax Item 5"],
    caseInsensitive: true,
    explanation: "MFD_O1 adds \"Tax Item 5\" (F183).",
    factIds: ["F183"],
    tags: ["uia.config", "uia.taxtest"],
  },
  {
    id: "Q298",
    type: "mc",
    moduleId: "M14",
    difficulty: 1,
    prompt: "In MFD_O1, which button is clicked after adding the item?",
    options: [
      "Charge",
      "Review Order",
      "Print",
      "Pay",
    ],
    answer: 1,
    explanation: "Open Register, add Tax Item 5, click \"Review Order\" (F183).",
    factIds: ["F183"],
    tags: ["uia.config", "uia.taxtest"],
  },
  {
    id: "Q299",
    type: "mc",
    moduleId: "M14",
    difficulty: 1,
    prompt: "In Tax test Step 1, Orca routes the backend call to which service to load a simulated swipe card?",
    options: [
      "Ubi",
      "Ollama",
      "Laz",
      "Callers/Collos (Callus)",
    ],
    answer: 3,
    explanation: "In Tax test Step 1 a backend call goes to Orchestrator, which routes to the Callers/Collos (Callus) microservice to load a simulated swipe card. (F184)",
    factIds: ["F184"],
    tags: ["uia.config", "uia.taxtest", "cards.callus"],
  },
  {
    id: "Q300",
    type: "mc",
    moduleId: "M14",
    difficulty: 1,
    prompt: "What does CFD_O1 assert?",
    options: [
      "Subtotal, calculated tax and grand total",
      "Tip amount",
      "The receipt QR code",
      "PIN entry",
    ],
    answer: 0,
    explanation: "Tax test Step 2 (CFD_O1): control shifts to the Customer display, which asserts subtotal, calculated tax and grand total. (F185)",
    factIds: ["F185"],
    tags: ["uia.config", "uia.taxtest"],
  },
  {
    id: "Q301",
    type: "mc",
    moduleId: "M14",
    difficulty: 1,
    prompt: "Which buttons are clicked in MFD_O2?",
    options: [
      "\"Pay\" and \"Charge\"",
      "\"Tender\" and \"Done\"",
      "\"Charge\" and \"Print\"",
      "\"Review Order\" and \"Pay\"",
    ],
    answer: 0,
    explanation: "Tax test Step 3 (MFD_O2): control returns to the Merchant display to click \"Pay\" and \"Charge\". (F186)",
    factIds: ["F186"],
    tags: ["uia.config", "uia.taxtest"],
  },
  {
    id: "Q302",
    type: "mc",
    moduleId: "M14",
    difficulty: 1,
    prompt: "Where is the payment prompt finalised in Step 4?",
    options: [
      "In Orca",
      "On the Customer display",
      "On the Merchant display",
      "On the status tablet",
    ],
    answer: 1,
    explanation: "Tax test Step 4: the payment prompt is finalised on the Customer display. (F187)",
    factIds: ["F187"],
    tags: ["uia.config", "uia.taxtest"],
  },
  {
    id: "Q303",
    type: "mc",
    moduleId: "M14",
    difficulty: 1,
    prompt: "What does the Tax test file begin with?",
    options: [
      "An @Ignore annotation",
      "A plain-text documentation header explaining the test's intent",
      "A random seed",
      "A dump of config.properties",
    ],
    answer: 1,
    explanation: "The Tax test begins with a plain-text documentation header explaining the test's intent. (F181)",
    factIds: ["F181"],
    tags: ["uia.config", "uia.taxtest"],
  },
  {
    id: "Q304",
    type: "match",
    moduleId: "M14",
    difficulty: 3,
    prompt: "Match each config.properties key to its locked or expected value for MEGATRON.",
    pairs: [
      ["runType", "tethered"],
      ["theme", "avocado"],
      ["kernelType", "CPA"],
      ["portNumber", "5444"],
    ],
    explanation: "F190, F196, F197, F198. (MEGATRON's IPs are covered separately.)",
    factIds: ["F190", "F196", "F197", "F198"],
    tags: ["uia.config", "adb.port"],
  },
  {
    id: "Q305",
    type: "mc",
    moduleId: "M14",
    difficulty: 2,
    prompt: "In the Tax test, which device shows the subtotal, tax and total to be asserted?",
    options: [
      "The CFD (Customer Facing Device)",
      "The status tablet",
      "The MFD (Merchant Facing Device)",
      "The Collis probe",
    ],
    answer: 0,
    explanation: "CFD_O1 asserts on the Customer display (F185); CFD = Customer Facing Device (F054).",
    factIds: ["F054", "F185"],
    tags: ["uia.config", "hw.devices", "uia.taxtest"],
  },
  {
    id: "Q306",
    type: "tf",
    moduleId: "M14",
    difficulty: 2,
    prompt: "When you run TaxTest from your laptop, Jenkins injects config.properties for you.",
    options: ["True", "False"],
    answer: 1,
    explanation: "Locally you edit config.properties manually (F188); Jenkins injects values only during CI (F189).",
    factIds: ["F188", "F189"],
    tags: ["uia.config"],
  },
  {
    id: "Q307",
    type: "tf",
    moduleId: "M14",
    difficulty: 2,
    prompt: "merchantFacingDeviceIp holds the local network IP of the CFD terminal.",
    options: ["True", "False"],
    answer: 1,
    explanation: "merchantFacingDeviceIp is the MFD's IP (F191); the CFD's IP goes in customerFacingDeviceIp (F192).",
    factIds: ["F191", "F192"],
    tags: ["uia.config"],
  },
]);
