/**
 * Quiz bank — M15 Pigeon (LSTR) & Legacy JSON (Cur §3). 23 items.
 * Transcribed from docs/design/10-curriculum.md; every answer re-verified against
 * docs/reference/REMOVED-internal-reference.md. Options are stored in the doc's canonical display order
 * (the UI reshuffles); `order` items store options in the CORRECT order; `match` pairs are the correct pairing.
 */
import type { QuizQuestion } from '../schema';
import { resolvePeople } from '../people';

export const QUIZ_M15: QuizQuestion[] = resolvePeople([
  {
    id: "Q308",
    type: "mc",
    moduleId: "M15",
    difficulty: 1,
    checkpoint: "CP-M15.1",
    prompt: "What is Pigeon's other name?",
    options: [
      "LSTR",
      "Gort",
      "Laz",
      "Lester",
    ],
    answer: 0,
    explanation: "Pigeon (LSTR) (F041).",
    factIds: ["F041"],
    tags: ["pigeon", "pigeon.lstr"],
  },
  {
    id: "Q309",
    type: "fill",
    moduleId: "M15",
    difficulty: 2,
    checkpoint: "CP-M15.1",
    prompt: "LSTR stands for Language Specific Test ______. Type the missing word.",
    accepted: ["Runner"],
    caseInsensitive: true,
    explanation: "Language Specific Test Runner (F044). Case-insensitive.",
    factIds: ["F044"],
    tags: ["pigeon", "pigeon.lstr"],
  },
  {
    id: "Q310",
    type: "mc",
    moduleId: "M15",
    difficulty: 1,
    prompt: "The name \"Pigeon\" is a play on words on…",
    options: [
      "The carrier-pigeon RFC",
      "Homing pigeons carrying messages",
      "Pidgin language",
      "Pig Latin",
    ],
    answer: 2,
    explanation: "The name \"Pigeon\" is a play on words on \"pidgin language\". (F042)",
    factIds: ["F042"],
    tags: ["pigeon", "pigeon.lstr"],
  },
  {
    id: "Q311",
    type: "mc",
    moduleId: "M15",
    difficulty: 1,
    checkpoint: "CP-M15.1",
    prompt: "Pigeon evolved from which framework?",
    options: [
      "Laz",
      "JHipster",
      "Lester",
      "Callus",
    ],
    answer: 2,
    explanation: "Pigeon evolved from the Lester framework. (F043)",
    factIds: ["F043"],
    tags: ["pigeon", "pigeon.lstr"],
  },
  {
    id: "Q312",
    type: "mc",
    moduleId: "M15",
    difficulty: 2,
    checkpoint: "CP-M15.1",
    prompt: "Which platforms have dedicated LSTR runners?",
    options: [
      "REST and Go only",
      "Linux and macOS",
      "REST, Android, Windows and iOS",
      "Android only",
    ],
    answer: 2,
    explanation: "Pigeon parses raw JSON test payloads across REST, Android, Windows and iOS. LSTR has dedicated runners for REST, Android, Windows and iOS. (F045, F202)",
    factIds: ["F045", "F202"],
    tags: ["pigeon", "pigeon.lstr", "pigeon.json"],
  },
  {
    id: "Q313",
    type: "fill",
    moduleId: "M15",
    difficulty: 2,
    prompt: "How many dedicated LSTR runners are there? Type the number.",
    accepted: ["4", "four"],
    caseInsensitive: true,
    explanation: "REST, Android, Windows, iOS (F202).",
    factIds: ["F202"],
    tags: ["pigeon", "pigeon.lstr"],
  },
  {
    id: "Q314",
    type: "tf",
    moduleId: "M15",
    difficulty: 1,
    prompt: "The iOS runner is rarely touched, but iOS Go testing is active.",
    options: ["True", "False"],
    answer: 0,
    explanation: "The iOS test runner is rarely touched, although iOS Go testing is active. (F203)",
    factIds: ["F203"],
    tags: ["pigeon", "pigeon.lstr"],
  },
  {
    id: "Q315",
    type: "mc",
    moduleId: "M15",
    difficulty: 1,
    prompt: "How does Pigeon handle a high-level command like \"card swipe\"?",
    options: [
      "The runner abstracts it into platform-specific SDK payment requests or physical robot actions",
      "It skips it on REST",
      "It always sends an ADB tap",
      "It asks the engineer to swipe by hand",
    ],
    answer: 0,
    explanation: "High-level commands (such as \"card swipe\") are abstracted by the runner into platform-specific SDK payment requests or physical robot actions. (F204)",
    factIds: ["F204"],
    tags: ["pigeon", "pigeon.abstraction"],
  },
  {
    id: "Q316",
    type: "mc",
    moduleId: "M15",
    difficulty: 1,
    checkpoint: "CP-M15.1",
    prompt: "Which is NOT a top-level part of a Pigeon JSON test?",
    options: [
      "Supported platforms",
      "Test name",
      "Connection type",
      "A Java page-object class",
    ],
    answer: 3,
    explanation: "A Pigeon test specifies name, connection type, platforms and an actions array (F205).",
    factIds: ["F205"],
    tags: ["pigeon", "pigeon.json"],
  },
  {
    id: "Q317",
    type: "order",
    moduleId: "M15",
    difficulty: 3,
    prompt: "Order the fields as they appear in the reference's description of a Pigeon JSON test.",
    options: [
      "Test name",
      "Connection type",
      "Supported platforms",
      "Array of test actions",
    ],
    answer: -1,
    explanation: "A Pigeon JSON test specifies the test name, connection type, supported platforms and an array of test actions. (F205)",
    factIds: ["F205"],
    tags: ["pigeon", "pigeon.json"],
  },
  {
    id: "Q318",
    type: "mc",
    moduleId: "M15",
    difficulty: 1,
    prompt: "How many platforms can a versatile Pigeon test target at once?",
    options: [
      "1",
      "4 to 5",
      "2",
      "10 or more",
    ],
    answer: 1,
    explanation: "Versatile Pigeon tests can target 4 to 5 platforms at once. (F206)",
    factIds: ["F206"],
    tags: ["pigeon", "pigeon.json"],
  },
  {
    id: "Q319",
    type: "mc",
    moduleId: "M15",
    difficulty: 1,
    prompt: "What do Pigeon test actions do?",
    options: [
      "Park robots",
      "Compile Java classes",
      "Render page objects",
      "Create requests, pass parameters and store output variables",
    ],
    answer: 3,
    explanation: "Pigeon test actions create requests, pass parameters and store output variables. (F207)",
    factIds: ["F207"],
    tags: ["pigeon", "pigeon.json"],
  },
  {
    id: "Q320",
    type: "mc",
    moduleId: "M15",
    difficulty: 1,
    checkpoint: "CP-M15.1",
    prompt: "A Pigeon test fails to parse. What tooling catches the error for you?",
    options: [
      "IntelliJ's Pigeon JSON inspection",
      "Jenkins auto-fixes it",
      "None: Pigeon has no JSON linter, so you hunt missing commas/brackets by hand",
      "Orca validates the JSON on upload",
    ],
    answer: 2,
    explanation: "Pigeon has no JSON linter, so missing commas or brackets must be hunted down manually. (F208)",
    factIds: ["F208"],
    tags: ["pigeon", "pigeon.nolint"],
  },
  {
    id: "Q321",
    type: "mc",
    moduleId: "M15",
    difficulty: 1,
    prompt: "How do engineers cope with the missing linter?",
    options: [
      "They avoid JSON entirely",
      "They let Ollama write them",
      "They write tests in YAML",
      "They copy-paste working JSON blocks instead of writing syntax from scratch",
    ],
    answer: 3,
    explanation: "Engineers survive the missing linter by copy-pasting working JSON blocks rather than writing syntax from scratch. (F209)",
    factIds: ["F209"],
    tags: ["pigeon", "pigeon.nolint"],
  },
  {
    id: "Q322",
    type: "mc",
    moduleId: "M15",
    difficulty: 1,
    checkpoint: "CP-M15.1",
    prompt: "A Jenkins log says the Pigeon test failed at \"select print\". What does that mean?",
    options: [
      "The printer hardware is broken",
      "The JSON for \"select print\" is invalid",
      "The robot is Unavailable",
      "That was the last step attempted before the runner timed out waiting for a printer payload",
    ],
    answer: 3,
    explanation: "A Jenkins log failure at \"select print\" means that action was the last step attempted before the runner timed out waiting for a printer payload. (F210)",
    factIds: ["F210"],
    tags: ["pigeon", "jenkins.logs"],
  },
  {
    id: "Q323",
    type: "mc",
    moduleId: "M15",
    difficulty: 1,
    prompt: "What is the usual root cause of a \"select print\" failure?",
    options: [
      "Outdated screen coordinates made the robot arm miss the Print button",
      "The printer ran out of paper",
      "Wine crashed on the Pi",
      "portNumber was 5555",
    ],
    answer: 0,
    explanation: "The usual root cause of a \"select print\" failure is outdated screen coordinates that made the robot arm miss the print button. (F211)",
    factIds: ["F211"],
    tags: ["pigeon", "jenkins.logs"],
  },
  {
    id: "Q324",
    type: "tf",
    moduleId: "M15",
    difficulty: 1,
    prompt: "A \"select print\" failure in the log always means the printer hardware failed.",
    options: ["True", "False"],
    answer: 1,
    explanation: "It's misleading: it was just the last step before the payload timeout (F210), usually stale coordinates (F211).",
    factIds: ["F210"],
    tags: ["pigeon", "jenkins.logs"],
  },
  {
    id: "Q325",
    type: "mc",
    moduleId: "M15",
    difficulty: 1,
    prompt: "In which format are Pigeon tests written?",
    options: [
      "Gherkin",
      "Java",
      "XML",
      "JSON",
    ],
    answer: 3,
    explanation: "Declarative, platform-agnostic JSON payloads (F012).",
    factIds: ["F012"],
    tags: ["pigeon", "pigeon.json"],
  },
  {
    id: "Q326",
    type: "tf",
    moduleId: "M15",
    difficulty: 2,
    prompt: "Pigeon tests are declarative, platform-agnostic JSON payloads parsed by the runner.",
    options: ["True", "False"],
    answer: 0,
    explanation: "JSON is the format used to write declarative, platform-agnostic test payloads in the legacy Pigeon repository. Pigeon parses raw JSON test payloads across REST, Android, Windows and iOS. (F012, F045)",
    factIds: ["F012", "F045"],
    tags: ["pigeon", "pigeon.json", "pigeon.lstr"],
  },
  {
    id: "Q327",
    type: "mc",
    moduleId: "M15",
    difficulty: 1,
    prompt: "Which framework is used (alongside mobile runners) to test the Go SDK?",
    options: [
      "Tesseract",
      "Laz",
      "uia-remote",
      "Pigeon",
    ],
    answer: 3,
    explanation: "The Go SDK is tested through Pigeon and mobile runners (F009).",
    factIds: ["F009"],
    tags: ["pigeon", "go.sdk"],
  },
  {
    id: "Q328",
    type: "match",
    moduleId: "M15",
    difficulty: 3,
    prompt: "Match each Pigeon symptom to its most likely cause.",
    pairs: [
      ["LSTR ParseError at line 23", "Missing comma or bracket (no linter)"],
      ["FAILED at \"select print\" after a timeout", "Arm missed Print due to outdated coordinates"],
    ],
    explanation: "Pigeon has no JSON linter, so missing commas or brackets must be hunted down manually. A Jenkins log failure at \"select print\" means that action was the last step attempted before the runner timed out waiting for a printer payload. The usual root cause of a \"select print\" failure is outdated screen coordinates that made the robot arm miss the print button. (F208, F210, F211)",
    factIds: ["F210", "F211", "F208"],
    tags: ["pigeon", "jenkins.logs", "pigeon.nolint"],
  },
  {
    id: "Q329",
    type: "mc",
    moduleId: "M15",
    difficulty: 2,
    prompt: "Which legacy repository is built around a Language Specific Test Runner?",
    options: [
      "Pigeon",
      "Orca",
      "Gort",
      "uia-remote",
    ],
    answer: 0,
    explanation: "Pigeon (LSTR) = Language Specific Test Runner (F041, F044).",
    factIds: ["F041", "F044"],
    tags: ["pigeon", "pigeon.lstr"],
  },
  {
    id: "Q330",
    type: "tf",
    moduleId: "M15",
    difficulty: 1,
    prompt: "In Pigeon, \"card swipe\" always becomes a physical robot action, even on the REST runner.",
    options: ["True", "False"],
    answer: 1,
    explanation: "The runner abstracts it into an SDK payment request or a physical robot action depending on platform (F204).",
    factIds: ["F204"],
    tags: ["pigeon", "pigeon.abstraction"],
  },
]);
