/**
 * Quiz bank — M16 Seeing the Second Screen: Station Duo, OCR, GIMP & UIA 2.3 (Cur §3). 20 items.
 * Transcribed from docs/design/10-curriculum.md; every answer re-verified against
 * docs/reference/REMOVED-internal-reference.md. Options are stored in the doc's canonical display order
 * (the UI reshuffles); `order` items store options in the CORRECT order; `match` pairs are the correct pairing.
 */
import type { QuizQuestion } from '../schema';
import { resolvePeople } from '../people';

export const QUIZ_M16: QuizQuestion[] = resolvePeople([
  {
    id: "Q331",
    type: "mc",
    moduleId: "M16",
    difficulty: 1,
    checkpoint: "CP-M16.1",
    prompt: "On a Station Duo, which display is exposed to ADB?",
    options: [
      "Only the CFD",
      "Neither",
      "Both displays",
      "Only the primary MFD",
    ],
    answer: 3,
    explanation: "One terminal drives two displays but only the primary MFD is exposed to ADB (F151).",
    factIds: ["F151"],
    tags: ["duo.ocr", "orca.screencompare", "uia.v23"],
  },
  {
    id: "Q332",
    type: "mc",
    moduleId: "M16",
    difficulty: 1,
    prompt: "How well could legacy UI Automator see the Station Duo's CFD?",
    options: [
      "Fully, with a second device handle",
      "Only in landscape mode",
      "Not at all; it was completely blind to it",
      "Partially, via accessibility IDs",
    ],
    answer: 2,
    explanation: "Legacy UI Automator was completely blind to the Station Duo's secondary CFD. (F152)",
    factIds: ["F152"],
    tags: ["duo.ocr", "orca.screencompare", "uia.v23"],
  },
  {
    id: "Q333",
    type: "mc",
    moduleId: "M16",
    difficulty: 1,
    checkpoint: "CP-M16.1",
    prompt: "Which Orca entity holds the Station Duo workaround?",
    options: [
      "Card Profile",
      "Screens",
      "Robot Capabilities",
      "Screen Compare Image",
    ],
    answer: 3,
    explanation: "The Screen Compare Image entity is the Station Duo workaround. (F150)",
    factIds: ["F150"],
    tags: ["duo.ocr", "orca.screencompare"],
  },
  {
    id: "Q334",
    type: "mc",
    moduleId: "M16",
    difficulty: 1,
    prompt: "What does a Screen Compare Image row store?",
    options: [
      "Spatial bounding coordinates on the CFD plus the expected text string",
      "Button coordinates in millimetres",
      "A Gort card path",
      "A full-resolution screenshot",
    ],
    answer: 0,
    explanation: "The OCR workaround stores spatial bounding coordinates on the CFD alongside the expected text string. (F153)",
    factIds: ["F153"],
    tags: ["duo.ocr", "orca.screencompare"],
  },
  {
    id: "Q335",
    type: "order",
    moduleId: "M16",
    difficulty: 3,
    checkpoint: "CP-M16.1",
    prompt: "Order the OCR workaround's steps.",
    options: [
      "Robot Controller captures a webcam screenshot",
      "Crops it to the bounding box",
      "Runs Tesseract OCR",
      "Returns a boolean match result",
    ],
    answer: -1,
    explanation: "In the OCR workaround the Robot Controller captures a webcam screenshot, crops it to the bounding box, runs Tesseract OCR and returns a boolean match result. (F154)",
    factIds: ["F154"],
    tags: ["duo.ocr", "orca.screencompare", "vision.tesseract", "vision.camera"],
  },
  {
    id: "Q336",
    type: "mc",
    moduleId: "M16",
    difficulty: 1,
    prompt: "What does the OCR workaround return to the test?",
    options: [
      "A boolean match result",
      "An HTTP 200",
      "A screenshot",
      "The recognised text",
    ],
    answer: 0,
    explanation: "In the OCR workaround the Robot Controller captures a webcam screenshot, crops it to the bounding box, runs Tesseract OCR and returns a boolean match result. (F154)",
    factIds: ["F154"],
    tags: ["duo.ocr", "orca.screencompare", "vision.tesseract", "vision.camera"],
  },
  {
    id: "Q337",
    type: "mc",
    moduleId: "M16",
    difficulty: 1,
    checkpoint: "CP-M16.1",
    prompt: "Which OCR engine runs on the cropped webcam screenshots?",
    options: [
      "Ollama",
      "Google Cloud Vision",
      "ABBYY FineReader",
      "Tesseract",
    ],
    answer: 3,
    explanation: "Tesseract OCR (F029).",
    factIds: ["F029"],
    tags: ["duo.ocr", "vision.tesseract"],
  },
  {
    id: "Q338",
    type: "tf",
    moduleId: "M16",
    difficulty: 1,
    prompt: "Tesseract is an open-source OCR engine.",
    options: ["True", "False"],
    answer: 0,
    explanation: "Tesseract OCR is the open-source OCR engine run on cropped webcam screenshots to validate text on displays that are blind to ADB. (F029)",
    factIds: ["F029"],
    tags: ["duo.ocr", "vision.tesseract"],
  },
  {
    id: "Q339",
    type: "mc",
    moduleId: "M16",
    difficulty: 1,
    checkpoint: "CP-M16.1",
    prompt: "Which change would break a Screen Compare OCR check?",
    options: [
      "Running the job from Jenkins instead of locally",
      "A Pi reboot between tests",
      "A 10-pixel shift of the label",
      "Switching the merchant with Laz",
    ],
    answer: 2,
    explanation: "A 10-pixel shift, a capitalisation change or a typo breaks it (F155).",
    factIds: ["F155"],
    tags: ["duo.ocr", "orca.screencompare"],
  },
  {
    id: "Q340",
    type: "fill",
    moduleId: "M16",
    difficulty: 2,
    prompt: "How many pixels of shift are enough to break the OCR suite? Type the number.",
    accepted: ["10", "ten"],
    caseInsensitive: true,
    explanation: "The OCR workaround is extremely brittle: a 10-pixel button shift, a capitalisation change or a typo breaks the suite. (F155)",
    factIds: ["F155"],
    tags: ["duo.ocr", "orca.screencompare"],
  },
  {
    id: "Q341",
    type: "tf",
    moduleId: "M16",
    difficulty: 1,
    prompt: "Changing \"TOTAL\" to \"Total\" on the CFD can break a Screen Compare check.",
    options: ["True", "False"],
    answer: 0,
    explanation: "Capitalisation changes break the brittle OCR workaround (F155).",
    factIds: ["F155"],
    tags: ["duo.ocr", "orca.screencompare"],
  },
  {
    id: "Q342",
    type: "mc",
    moduleId: "M16",
    difficulty: 1,
    prompt: "Why is Screen Compare / OCR being phased out?",
    options: [
      "UI Automator 2.3 natively supports dual-screen element tracking",
      "Tesseract's licence changed",
      "The GPUs are needed for Ollama",
      "Station Duos are being retired",
    ],
    answer: 0,
    explanation: "Screen Compare / OCR is being phased out because UI Automator 2.3 natively supports dual-screen element tracking. (F156)",
    factIds: ["F156"],
    tags: ["duo.ocr", "orca.screencompare", "uia.v23"],
  },
  {
    id: "Q343",
    type: "mc",
    moduleId: "M16",
    difficulty: 1,
    checkpoint: "CP-M16.1",
    prompt: "What does UI Automator 2.3 add that matters most to this lab?",
    options: [
      "Native dual-screen element location tracking",
      "Built-in OCR",
      "iOS support",
      "Kotlin support",
    ],
    answer: 0,
    explanation: "UI Automator 2.3 is chosen because it adds native support for dual-screen element location tracking. (F007)",
    factIds: ["F007"],
    tags: ["duo.ocr", "uia.v23"],
  },
  {
    id: "Q344",
    type: "mc",
    moduleId: "M16",
    difficulty: 1,
    prompt: "Which tool do engineers use to get exact coordinates from a device screenshot?",
    options: [
      "Tesseract",
      "Jenkins",
      "GIMP",
      "IntelliJ IDEA",
    ],
    answer: 2,
    explanation: "GIMP: open screenshot, draw a selection box, read coordinates (F030).",
    factIds: ["F030"],
    tags: ["duo.ocr", "pigeon.gimp"],
  },
  {
    id: "Q345",
    type: "mc",
    moduleId: "M16",
    difficulty: 1,
    prompt: "In Pigeon screen comparisons, where do the GIMP coordinates go?",
    options: [
      "Into the test's JSON block",
      "Into a Java locator",
      "Into Orca's Offsets",
      "Into config.properties",
    ],
    answer: 0,
    explanation: "For Pigeon screen comparisons, engineers open a screenshot in GIMP, draw a bounding box around the target text and copy the coordinates into the JSON block. (F212)",
    factIds: ["F212"],
    tags: ["duo.ocr", "pigeon.gimp"],
  },
  {
    id: "Q346",
    type: "order",
    moduleId: "M16",
    difficulty: 3,
    prompt: "Order a Pigeon screen-comparison set-up.",
    options: [
      "Open the device screenshot in GIMP",
      "Draw a bounding box around the target text",
      "Copy the coordinates",
      "Paste them into the Pigeon JSON block",
    ],
    answer: -1,
    explanation: "For Pigeon screen comparisons, engineers open a screenshot in GIMP, draw a bounding box around the target text and copy the coordinates into the JSON block. (F212)",
    factIds: ["F212", "F030"],
    tags: ["duo.ocr", "pigeon.gimp"],
  },
  {
    id: "Q347",
    type: "mc",
    moduleId: "M16",
    difficulty: 2,
    prompt: "R2-D2's CFD (Station Duo) is ADB-blind. What kind of bot is needed to interact with it?",
    options: [
      "A physical/interactive bot",
      "Any bot with portNumber 5555",
      "An ADB bot",
      "No bot; it cannot be tested",
    ],
    answer: 0,
    explanation: "Physical bots are required for ADB-blind displays (F221).",
    factIds: ["F221", "F151"],
    tags: ["duo.ocr", "bots.types", "orca.screencompare", "uia.v23"],
  },
  {
    id: "Q348",
    type: "tf",
    moduleId: "M16",
    difficulty: 2,
    prompt: "With UI Automator 2.3, uia-remote can locate elements on the Station Duo's CFD natively.",
    options: ["True", "False"],
    answer: 0,
    explanation: "UIA 2.3 natively supports dual-screen tracking (F007, F156).",
    factIds: ["F156", "F152"],
    tags: ["duo.ocr", "orca.screencompare", "uia.v23"],
  },
  {
    id: "Q349",
    type: "mc",
    moduleId: "M16",
    difficulty: 2,
    prompt: "Where does the OCR screenshot come from?",
    options: [
      "ADB screencap of the CFD",
      "The rig's webcam, captured by the Robot Controller",
      "GIMP",
      "The status tablet camera",
    ],
    answer: 1,
    explanation: "The Robot Controller captures a webcam screenshot (F154, F088). ADB can't see the CFD.",
    factIds: ["F088", "F154"],
    tags: ["duo.ocr", "hw.rigbom", "vision.camera", "orca.screencompare", "vision.tesseract"],
  },
  {
    id: "Q350",
    type: "mc",
    moduleId: "M16",
    difficulty: 2,
    prompt: "A legacy suite must verify text on R2-D2's CFD. Which Orca record do you create?",
    options: [
      "A Card Profile",
      "A Screen Location",
      "A Robot Capability",
      "A Screen Compare Image (bounding box + expected text)",
    ],
    answer: 3,
    explanation: "The Screen Compare Image entity stores CFD bounding coordinates and expected text (F150, F153).",
    factIds: ["F150", "F153"],
    tags: ["duo.ocr", "orca.screencompare"],
  },
]);
