/**
 * Quiz bank — M17 AI, Infrastructure & the Roadmap (Cur §3). 18 items.
 * Transcribed from docs/design/10-curriculum.md; every answer re-verified against
 * docs/reference/REMOVED-internal-reference.md. Options are stored in the doc's canonical display order
 * (the UI reshuffles); `order` items store options in the CORRECT order; `match` pairs are the correct pairing.
 */
import type { QuizQuestion } from '../schema';
import { resolvePeople } from '../people';

export const QUIZ_M17: QuizQuestion[] = resolvePeople([
  {
    id: "Q351",
    type: "mc",
    moduleId: "M17",
    difficulty: 1,
    checkpoint: "CP-M17.1",
    prompt: "How many NVIDIA GPUs are in the server blade?",
    options: [
      "8",
      "1",
      "2",
      "4",
    ],
    answer: 3,
    explanation: "Four NVIDIA GPUs are installed in a shelf-mounted server blade. (F075)",
    factIds: ["F075"],
    tags: ["infra.ai", "arch.infra"],
  },
  {
    id: "Q352",
    type: "mc",
    moduleId: "M17",
    difficulty: 1,
    prompt: "How are the blade's GPUs arranged?",
    options: [
      "Two exposed, two underneath",
      "One per VM in different racks",
      "All four exposed on top",
      "Inside a separate tower",
    ],
    answer: 0,
    explanation: "Of the four GPUs in the blade, two are exposed and two are underneath. (F076)",
    factIds: ["F076"],
    tags: ["infra.ai", "arch.infra"],
  },
  {
    id: "Q353",
    type: "mc",
    moduleId: "M17",
    difficulty: 1,
    prompt: "What did the GPU blade replace?",
    options: [
      "The Intel NUCs",
      "The Raspberry Pis",
      "A cloud subscription",
      "A legacy tower unit",
    ],
    answer: 3,
    explanation: "The GPU server blade replaced a legacy tower unit. (F077)",
    factIds: ["F077"],
    tags: ["infra.ai", "arch.infra"],
  },
  {
    id: "Q354",
    type: "mc",
    moduleId: "M17",
    difficulty: 1,
    checkpoint: "CP-M17.1",
    prompt: "What does the GPU blade host?",
    options: [
      "The VMs, Orca, Jenkins and Ollama",
      "Only MySQL",
      "The Raspberry Pi images",
      "Only Ollama",
    ],
    answer: 0,
    explanation: "The GPU server blade hosts the VMs, Orca, Jenkins and Ollama. (F078)",
    factIds: ["F078"],
    tags: ["infra.ai", "arch.infra"],
  },
  {
    id: "Q355",
    type: "mc",
    moduleId: "M17",
    difficulty: 1,
    checkpoint: "CP-M17.1",
    prompt: "What is Ollama in this lab?",
    options: [
      "A CI server",
      "A cloud AI API",
      "A local LLM runner hosted on the 4-GPU server blade",
      "An OCR engine",
    ],
    answer: 2,
    explanation: "Ollama is a local LLM runner hosted on the lab's 4-GPU server blade. (F031)",
    factIds: ["F031"],
    tags: ["infra.ai", "vision.ollama"],
  },
  {
    id: "Q356",
    type: "mc",
    moduleId: "M17",
    difficulty: 1,
    prompt: "What does the Ollama proof of concept validate?",
    options: [
      "Power-rail voltages",
      "Receipt layouts and tip math, from webcam streams",
      "Pigeon JSON syntax",
      "Jenkins logs",
    ],
    answer: 1,
    explanation: "Ollama currently runs proof-of-concept Vision-LLM inspections of webcam streams to validate receipt layouts and tip math. (F032)",
    factIds: ["F032"],
    tags: ["infra.ai", "vision.ollama"],
  },
  {
    id: "Q357",
    type: "tf",
    moduleId: "M17",
    difficulty: 1,
    prompt: "Ollama's vision checks are already the production gate replacing all assertions.",
    options: ["True", "False"],
    answer: 1,
    explanation: "They are a proof of concept (F032).",
    factIds: ["F032"],
    tags: ["infra.ai", "vision.ollama"],
  },
  {
    id: "Q358",
    type: "mc",
    moduleId: "M17",
    difficulty: 1,
    checkpoint: "CP-M17.1",
    prompt: "What was Claude evaluated for during corporate AI initiatives?",
    options: [
      "Driving the robots",
      "Repository optimisation and automated test generation",
      "Emulating cards",
      "Replacing Tesseract",
    ],
    answer: 1,
    explanation: "Claude was evaluated during corporate AI initiatives for repository optimisation and automated test generation. (F033)",
    factIds: ["F033"],
    tags: ["infra.ai", "tools.claude"],
  },
  {
    id: "Q359",
    type: "mc",
    moduleId: "M17",
    difficulty: 1,
    checkpoint: "CP-M17.1",
    prompt: "What are the planned migration targets for Orca?",
    options: [
      "The Raspberry Pis",
      "Kubernetes on AWS",
      "Heroku",
      "Docker and Google Cloud Platform",
    ],
    answer: 3,
    explanation: "Docker and Google Cloud Platform (GCP) are the planned migration targets for containerising Orchestrator. (F022)",
    factIds: ["F022"],
    tags: ["infra.ai", "arch.infra"],
  },
  {
    id: "Q360",
    type: "tf",
    moduleId: "M17",
    difficulty: 2,
    prompt: "Orca already runs in Docker on GCP.",
    options: ["True", "False"],
    answer: 1,
    explanation: "It runs on an on-prem lab VM today; Docker/GCP is planned (F023, F022).",
    factIds: ["F023", "F022"],
    tags: ["infra.ai", "arch.stack", "arch.infra"],
  },
  {
    id: "Q361",
    type: "mc",
    moduleId: "M17",
    difficulty: 1,
    prompt: "Which team is the partner for the Gen 2 Software PIN Bypass?",
    options: [
      "Core OS Team",
      "IPX Team",
      "PayCore Team",
      "Semi Team",
    ],
    answer: 0,
    explanation: "Gen 2 Software PIN Bypass: the team is partnering with the Core OS Team on a software framework that bypasses physical robotics for Secure Touch PIN entry. (F222)",
    factIds: ["F222"],
    tags: ["infra.ai", "bots.pin"],
  },
  {
    id: "Q362",
    type: "mc",
    moduleId: "M17",
    difficulty: 1,
    prompt: "What does Gen 2 Software PIN Bypass bypass?",
    options: [
      "Physical robotics for Secure Touch PIN entry",
      "Orca's health checks",
      "Laz OOBE",
      "Jenkins checkouts",
    ],
    answer: 0,
    explanation: "Gen 2 Software PIN Bypass: the team is partnering with the Core OS Team on a software framework that bypasses physical robotics for Secure Touch PIN entry. (F222)",
    factIds: ["F222"],
    tags: ["infra.ai", "bots.pin"],
  },
  {
    id: "Q363",
    type: "mc",
    moduleId: "M17",
    difficulty: 1,
    prompt: "Under Gen 2, physical robotics are reserved for…",
    options: [
      "PIN entry",
      "Non-negotiable hardware interactions such as card dipping",
      "Every tap",
      "Receipt printing only",
    ],
    answer: 1,
    explanation: "Under Gen 2, physical robotics are reserved exclusively for non-negotiable hardware interactions such as card dipping. (F223)",
    factIds: ["F223"],
    tags: ["infra.ai", "bots.pin"],
  },
  {
    id: "Q364",
    type: "mc",
    moduleId: "M17",
    difficulty: 1,
    prompt: "Which repositories does GitHub host, per the reference?",
    options: [
      "Wine and Tesseract",
      "Gort, uia-remote and pigeon",
      "Orca only",
      "Jenkins and Ollama",
    ],
    answer: 1,
    explanation: "GitHub hosts the team's repositories (Gort, uia-remote, pigeon) for branch management and pull requests. (F018)",
    factIds: ["F018"],
    tags: ["infra.ai", "arch.repos", "tools.github"],
  },
  {
    id: "Q365",
    type: "mc",
    moduleId: "M17",
    difficulty: 2,
    prompt: "Where does Orca's MySQL-backed VM run?",
    options: [
      "On WALL-E's Pi",
      "On a Minix box",
      "On the shelf-mounted 4-GPU server blade",
      "On GCP",
    ],
    answer: 2,
    explanation: "The blade hosts the VMs and Orca (F078); Orca is backed by MySQL (F013).",
    factIds: ["F013", "F078"],
    tags: ["infra.ai", "arch.stack", "arch.infra"],
  },
  {
    id: "Q366",
    type: "tf",
    moduleId: "M17",
    difficulty: 2,
    prompt: "Hardware control today runs on the Windows Intel NUCs.",
    options: ["True", "False"],
    answer: 1,
    explanation: "It was migrated off the NUCs onto Raspberry Pis (F068).",
    factIds: ["F066", "F068"],
    tags: ["infra.ai", "hw.nuc"],
  },
  // Correction vs Cur §3: factIds: + F032 (the explanation and option 3 test the Ollama PoC)
  {
    id: "Q367",
    type: "match",
    moduleId: "M17",
    difficulty: 3,
    prompt: "Match each roadmap item to its state.",
    pairs: [
      ["Orca on an on-prem lab VM", "Today"],
      ["Orca containerised in Docker on GCP", "Planned"],
      ["Ollama vision checks on webcam streams", "Proof of concept"],
      ["Software PIN bypass with Core OS", "Gen 2, in partnership"],
    ],
    explanation: "Orchestrator currently runs on a local, on-premise laboratory Virtual Machine (which the Docker/GCP plan would move it off). Docker and Google Cloud Platform (GCP) are the planned migration targets for containerising Orchestrator. Ollama currently runs proof-of-concept Vision-LLM inspections of webcam streams to validate receipt layouts and tip math. Gen 2 Software PIN Bypass: the team is partnering with the Core OS Team on a software framework that bypasses physical robotics for Secure Touch PIN entry. (F023, F022, F032, F222)",
    factIds: ["F022", "F023", "F031", "F222", "F032"],
    tags: ["infra.ai", "arch.infra", "arch.stack", "vision.ollama", "bots.pin"],
  },
  {
    id: "Q368",
    type: "fill",
    moduleId: "M17",
    difficulty: 2,
    prompt: "How many NVIDIA GPUs are in the lab's server blade? Type the number.",
    accepted: ["4", "four"],
    caseInsensitive: true,
    explanation: "Four NVIDIA GPUs in a shelf-mounted blade (F075).",
    factIds: ["F075"],
    tags: ["infra.ai", "arch.infra"],
  },
]);
