/**
 * Quiz bank — M18 Teams, History & the Capstone Shift (Cur §3). 14 items.
 * Transcribed from docs/design/10-curriculum.md; every answer re-verified against
 * docs/reference/REMOVED-internal-reference.md. Options are stored in the doc's canonical display order
 * (the UI reshuffles); `order` items store options in the CORRECT order; `match` pairs are the correct pairing.
 */
import type { QuizQuestion } from '../schema';
import { resolvePeople } from '../people';

export const QUIZ_M18: QuizQuestion[] = resolvePeople([
  {
    id: "Q369",
    type: "mc",
    moduleId: "M18",
    difficulty: 1,
    checkpoint: "CP-M18.1",
    prompt: "Historically, which team developed third-party POS SDKs and remote pay display apps?",
    options: [
      "Semi Team",
      "Sedi Team",
      "IPX Team",
      "PayCore Team",
    ],
    answer: 0,
    explanation: "Historically the Semi Team developed third-party POS SDKs and the remote pay display apps. (F157)",
    factIds: ["F157"],
    tags: ["teams.history", "uia.history"],
  },
  {
    id: "Q370",
    type: "mc",
    moduleId: "M18",
    difficulty: 1,
    checkpoint: "CP-M18.1",
    prompt: "What was the Sedi Team's role?",
    options: [
      "Built the POS SDKs",
      "Built the robots",
      "Built Core OS",
      "QA: tested the Semi Team's apps with the legacy Lester framework",
    ],
    answer: 3,
    explanation: "The Sedi (QA) Team tested the Semi Team's apps using the legacy Lester framework. (F158)",
    factIds: ["F158"],
    tags: ["teams.history", "uia.history"],
  },
  {
    id: "Q371",
    type: "mc",
    moduleId: "M18",
    difficulty: 1,
    prompt: "Which team maintains USB Pay Display and Secure Network Pay Display?",
    options: [
      "Sedi Team",
      "PayCore Team",
      "Core OS Team",
      "Semi Team",
    ],
    answer: 3,
    explanation: "USB Pay Display and Secure Network Pay Display are applications maintained by the Semi Team. (F052)",
    factIds: ["F052"],
    tags: ["teams.history", "semi.paydisplay"],
  },
  {
    id: "Q372",
    type: "mc",
    moduleId: "M18",
    difficulty: 1,
    prompt: "What do USB Pay Display and Secure Network Pay Display do?",
    options: [
      "Mirror the status tablet to a TV",
      "Stream webcams to Orca",
      "Emulate cards over USB",
      "Link Merchant Facing Devices and Customer Facing Devices over USB or the local network",
    ],
    answer: 3,
    explanation: "USB Pay Display and Secure Network Pay Display link Merchant Facing Devices and Customer Facing Devices over USB or the local network. (F053)",
    factIds: ["F053"],
    tags: ["teams.history", "semi.paydisplay"],
  },
  {
    id: "Q373",
    type: "mc",
    moduleId: "M18",
    difficulty: 1,
    checkpoint: "CP-M18.1",
    prompt: "What does IPX stand for?",
    options: [
      "Integrated POS eXecutor",
      "Integrated Payment Experience",
      "Interac Payment eXtension",
      "Internal Payment eXchange",
    ],
    answer: 1,
    explanation: "uia-remote is now integrated with the IPX (Integrated Payment Experience) Team. (F160)",
    factIds: ["F160"],
    tags: ["teams.history", "uia.history"],
  },
  {
    id: "Q374",
    type: "mc",
    moduleId: "M18",
    difficulty: 1,
    prompt: "Which of these is NOT one of the native apps IPX tests with uia-remote?",
    options: [
      "Register",
      "LabSim Dining",
      "Authorizations",
      "Orders",
    ],
    answer: 1,
    explanation: "IPX: Register, Orders, Authorizations, Sale, Transactions, Setup (F161). LabSim Dining is PayCore's (F162).",
    factIds: ["F161"],
    tags: ["teams.history", "uia.history"],
  },
  {
    id: "Q375",
    type: "mc",
    moduleId: "M18",
    difficulty: 1,
    checkpoint: "CP-M18.1",
    prompt: "PayCore adopted uia-remote for apps like…",
    options: [
      "USB Pay Display",
      "Setup",
      "LabSim Dining",
      "Register",
    ],
    answer: 2,
    explanation: "The PayCore Team adopted uia-remote for apps like LabSim Dining. (F162)",
    factIds: ["F162"],
    tags: ["teams.history", "uia.history"],
  },
  {
    id: "Q376",
    type: "mc",
    moduleId: "M18",
    difficulty: 1,
    prompt: "How does the PayCore Team test cards?",
    options: [
      "They don't test cards",
      "Exhaustive back-to-back card-matrix validations: Visa, Discover, AmEx",
      "One Visa profile only",
      "Interac only",
    ],
    answer: 1,
    explanation: "The PayCore Team runs exhaustive back-to-back card-matrix validations (Visa, Discover, AmEx). (F226)",
    factIds: ["F226"],
    tags: ["teams.history", "cards.philosophy"],
  },
  // Correction vs Cur §3: factIds: + F161, F226 (options A and E test them; the explanation cites them)
  {
    id: "Q377",
    type: "match",
    moduleId: "M18",
    difficulty: 3,
    checkpoint: "CP-M18.1",
    prompt: "Match each team to what it does.",
    pairs: [
      ["Semi Team", "POS SDKs and remote pay display apps"],
      ["Sedi Team", "QA with the Lester framework"],
      ["IPX Team", "Native apps Register, Orders, Authorizations, Sale, Transactions, Setup"],
      ["PayCore Team", "LabSim Dining and the full card matrix"],
      ["Core OS Team", "Gen 2 Software PIN Bypass partner"],
    ],
    explanation: "Historically the Semi Team developed third-party POS SDKs and the remote pay display apps. The Sedi (QA) Team tested the Semi Team's apps using the legacy Lester framework. With IPX, uia-remote tests standalone and tethered devices across the native apps Register, Orders, Authorizations, Sale, Transactions and Setup. The PayCore Team adopted uia-remote for apps like LabSim Dining. The PayCore Team runs exhaustive back-to-back card-matrix validations (Visa, Discover, AmEx). Gen 2 Software PIN Bypass: the team is partnering with the Core OS Team on a software framework that bypasses physical robotics for Secure Touch PIN entry. (F157, F158, F161, F162, F226, F222)",
    factIds: ["F157", "F158", "F160", "F162", "F222", "F161", "F226"],
    tags: ["teams.history", "uia.history", "bots.pin", "cards.philosophy"],
  },
  {
    id: "Q378",
    type: "tf",
    moduleId: "M18",
    difficulty: 1,
    prompt: "uia-remote was created by the Sedi Team as an upgrade to Lester.",
    options: ["True", "False"],
    answer: 1,
    explanation: "The presenter ({{morgan}} in-game) created uia-remote because nothing could automate native tethered setups (F159).",
    factIds: ["F159"],
    tags: ["teams.history", "uia.history", "people.roles"],
  },
  {
    id: "Q379",
    type: "mc",
    moduleId: "M18",
    difficulty: 2,
    prompt: "Why does the PayCore Team's ROSIE sit in Unavailable?",
    options: [
      "It has no printer",
      "It is Canadian",
      "It's broken",
      "So general tests don't overwrite its merchant profile",
    ],
    answer: 3,
    explanation: "Unavailable isolates specialised rigs like PayCore standalone setups (F103).",
    factIds: ["F103", "F226"],
    tags: ["teams.history", "orca.status.unavailable", "cards.philosophy"],
  },
  {
    id: "Q380",
    type: "tf",
    moduleId: "M18",
    difficulty: 2,
    prompt: "Your team and PayCore use the same card-testing strategy.",
    options: ["True", "False"],
    answer: 1,
    explanation: "Your team uses one Visa (+ Interac); PayCore runs the full matrix (F224, F226).",
    factIds: ["F224", "F226"],
    tags: ["teams.history", "cards.philosophy"],
  },
  {
    id: "Q381",
    type: "mc",
    moduleId: "M18",
    difficulty: 2,
    prompt: "Notes show \"GET http://10.42.10.13:8000/health → 502 … callus upstream 10.42.20.1:9000 unreachable\". Best action?",
    options: [
      "Escalate to {{jared}}: the Minix box running Callus is unreachable",
      "Re-run the job until it passes",
      "Edit config.properties",
      "Set the robot to Available",
    ],
    answer: 0,
    explanation: "A Minix box running Callus going offline is a typical Connection Failed cause, escalated to {{jared}} (F110, F111).",
    factIds: ["F110", "F111"],
    tags: ["teams.history", "orca.status.connfailed", "people.roles"],
  },
  {
    id: "Q382",
    type: "mc",
    moduleId: "M18",
    difficulty: 2,
    prompt: "Lester was the legacy framework used by which team, and what did it evolve into?",
    options: [
      "The Semi Team; it evolved into uia-remote",
      "IPX; it evolved into Orca",
      "PayCore; it evolved into Laz",
      "The Sedi (QA) Team; it evolved into Pigeon",
    ],
    answer: 3,
    explanation: "Sedi tested with Lester (F158); Pigeon evolved from Lester (F043).",
    factIds: ["F043", "F158"],
    tags: ["teams.history", "pigeon.lstr", "uia.history"],
  },
]);
