/**
 * GP §3.3 global wrong actions GW01–GW24 with their GP §5.5 Teach Cards (exact texts) and detectors over
 * sim / app events. Detection only sees player-caused events (runtime-driven events are filtered out by
 * the caller); `GWS` holds the pre-event facts some rules need. GW12 (escalation) and GW16 (premature
 * resolve) are raised directly by the ticket logic.
 */
import type { GlobalWrongActionDef, GwDetector } from '../../types';
import { on } from '../../types';
import { personText } from '@/content';
import { GWS, currentConfig } from './gwState';
import {
  INFRA_HOSTS,
  askedInChat,
  byPlayer,
  configTurnedBad,
  connFailedCausePersists,
  has5555,
  islabload,
  isCollisLoad,
  isCoworkerDevice,
  isDc,
  isLegacyRow,
  paycoreRig,
  pl,
  playerTouchedPower,
  recentProtectionTrip,
  robotUrl,
} from './gwHelpers';

export { clearChatAsks, connFailedCausePersists, noteChatAsk } from './gwHelpers';

/* ───────────────────────────── definitions ───────────────────────────── */

const d = (def: GlobalWrongActionDef): GlobalWrongActionDef => def;
const det = (match: GwDetector['match'], when?: GwDetector['when']): GwDetector => (when ? { match, when } : { match });

export const GLOBAL_WRONG_ACTIONS: readonly GlobalWrongActionDef[] = [
  d({
    id: 'GW01',
    name: 'Fried hardware',
    action: 'Connect a LabSim device (or its PSU lead) to any DC rail/regulator terminal',
    penalty: 500,
    strike: true,
    tags: ['power.18v'],
    consequence: 'Device FRIED (spark, smoke); follow-up "Replace fried device" ticket',
    factIds: ['F228', 'F229'],
    cooldownS: 5,
    detect: [
      det(on('power.plugged'), (s, p) => isDc(pl(p).hookup) && islabload(s.lab, String(pl(p).loadId))),
      det(on('device.fried'), (_s, p) => /dc|rail|regulator|terminal|24 ?v|plug/i.test(String(pl(p).cause ?? ''))),
    ],
    teach: {
      whatHappened: 'The Flex fried on the 24 V tap.',
      why: 'LabSim devices draw an irregular 18 V; they bypass the DC rails and use commercial AC strips. (Ref §6)',
      doInstead: "Free an outlet on the AC strip; use the device's own PSU.",
      ref: 'Ref §6',
      factIds: ['F228', 'F229'],
      practiceDrillId: 'DR04',
      tag: 'power.18v',
    },
  }),
  d({
    id: 'GW02',
    name: 'Fried Collis probe',
    action: 'Connect a Collis probe to any DC terminal',
    penalty: 750,
    strike: true,
    tags: ['power.18v', 'hw.collis'],
    consequence: 'Probe FRIED; rig loses card actions; spare from the locked cabinet costs 120 s',
    factIds: ['F229'],
    cooldownS: 5,
    detect: [det(on('power.plugged'), (s, p) => isDc(pl(p).hookup) && isCollisLoad(s.lab, String(pl(p).loadId)))],
    teach: {
      whatHappened: 'The Collis probe fried on DC power.',
      why: 'Collis probes are high-cost and, like LabSim devices, go only on AC strips. (Ref §1, §6)',
      doInstead: 'Plug the probe PSU into the strip; re-seat its rear ribbon.',
      ref: 'Ref §1, §6',
      factIds: ['F229'],
      practiceDrillId: 'DR04',
      tag: 'power.18v',
    },
  }),
  d({
    id: 'GW03',
    name: 'Live fuse swap',
    action: 'Remove/insert a fuse with its branch live (regulator input on / MAIN on)',
    penalty: 200,
    strike: false,
    tags: ['power.fuses'],
    consequence: 'Spark + snap',
    factIds: ['F087'],
    detect: [det(on('power.fuseRemoved', { live: true })), det(on('power.fuseInserted', { live: true }))],
    teach: {
      whatHappened: 'You pulled a fuse on a live branch.',
      why: 'De-energise before servicing a fused line. [illus. practice]',
      doInstead: 'Regulator input off (or MAIN off), then swap the fuse.',
      illustrative: true,
      practiceDrillId: 'DR13',
      tag: 'power.fuses',
    },
  }),
  d({
    id: 'GW04',
    name: 'Wrong fuse rating',
    action: 'Fuse rating ≠ holder label',
    penalty: 250,
    strike: false,
    tags: ['power.fuses'],
    consequence: 'Over-rated: flagged unsafe; under-rated (5 A): blows again within 20 s',
    factIds: ['F087'],
    detect: [det(on('power.fuseInserted'), (_s, p) => Number(pl(p).ratingA) !== Number(pl(p).labelA))],
    teach: {
      whatHappened: 'Wrong fuse rating.',
      why: 'Use the rating on the holder label (10 A on the 5 V 10 A line). [illus. rating]',
      doInstead: 'Take a red 10 A blade fuse.',
      illustrative: true,
      practiceDrillId: 'DR13',
      tag: 'power.fuses',
    },
  }),
  d({
    id: 'GW05',
    name: 'PayCore rig opened',
    action: 'Set a paycore rig to Available',
    penalty: 400,
    strike: 'conditional',
    strikeWhen: () => false,
    tags: ['orca.status.unavailable'],
    consequence: '40 % per checkout cycle that a general pipeline takes it and Laz swaps its merchant → INC40',
    factIds: ['F102', 'F103'],
    detect: [det(on('robot.statusChanged', { to: 'AVAILABLE' }), (_s, p) => byPlayer(p) && paycoreRig(String(pl(p).name)))],
    teach: {
      whatHappened: 'ROSIE opened to general pipelines.',
      why: 'Unavailable keeps PayCore\'s merchant safe; only jobs naming the robot use it, and Orca resets it afterwards. (Ref §3)',
      doInstead: 'Leave it Unavailable; pass `ROBOT_NAME=rosie`.',
      ref: 'Ref §3',
      factIds: ['F102', 'F103'],
      practiceDrillId: 'DR01',
      tag: 'orca.status.unavailable',
    },
  }),
  d({
    id: 'GW06',
    name: 'Arm pushed by hand',
    action: 'Push/drag a gantry carriage by hand',
    penalty: 100,
    strike: false,
    tags: ['hw.motion'],
    consequence: 'Lock released, banner yellow',
    factIds: ['F231', 'F232'],
    cooldownS: 10,
    detect: [det(on('rig.carriageDragged'), (_s, p) => byPlayer(p)), det(on('rig.lockBroken'), (_s, p) => byPlayer(p))],
    teach: {
      whatHappened: 'Pushing the arm released its magnetic lock.',
      why: 'Manual moves turn the banner yellow; only Park All re-homes to the limit switches. (Ref §6)',
      doInstead: 'Motion Control → Park All.',
      ref: 'Ref §6',
      factIds: ['F231', 'F232'],
      practiceDrillId: 'DR16',
      tag: 'hw.motion',
    },
  }),
  d({
    id: 'GW07',
    name: 'Cut an active test',
    action: 'Toggle MAIN/MOTOR or press any motion button on a rig with an active test',
    penalty: 250,
    strike: false,
    tags: ['hw.lockout'],
    consequence: 'Running build fails; coworker bark',
    factIds: ['F230'],
    detect: [
      det(on('rig.switch'), (_s, p) => GWS.activeTests.has(String(pl(p).rigId))),
      det(on('rig.command', { ok: true }), (_s, p) => byPlayer(p) && GWS.activeTests.has(String(pl(p).rigId))),
    ],
    teach: {
      whatHappened: 'You cut power during an active test.',
      why: 'The dashboard locks out during tests for this reason. (Ref §6)',
      doInstead: 'Wait for the job to finish.',
      ref: 'Ref §6',
      factIds: ['F230'],
      practiceDrillId: 'DR16',
      tag: 'hw.lockout',
    },
  }),
  d({
    id: 'GW08',
    name: 'Port 5555',
    action: 'Use port 5555 (config, adb connect, adb tcpip 5555, Orca URL)',
    penalty: 300,
    strike: 'conditional',
    strikeWhen: (_s, p) => String(pl(p).target ?? pl(p).line ?? '').includes('10.42.60.') || pl(p).coworker === true || pl(p).by === 'terminal' || pl(p).by === 'runner',
    tags: ['adb.port'],
    consequence: personText("{{riley}}'s desk Flex gets driven (INC27)"),
    factIds: ['F198', 'F199', 'F200'],
    cooldownS: 20,
    detect: [
      // Undoing a 5555 connection (`adb disconnect …:5555`) is the fix, not the mistake.
      det(on('terminal.command'), (_s, p) => /\badb\b/.test(String(pl(p).line)) && !/\badb\s+(-s\s+\S+\s+)?disconnect\b/.test(String(pl(p).line)) && has5555(pl(p).line)),
      // A runner connection/drive belongs to whoever started the run: an incident's pre-started run
      // (INC27) is the situation to fix, not the player's move (its own −20 drain covers the delay).
      det(on('adb.connected'), (_s, p) => String(pl(p).target).endsWith(':5555') && !GWS.runtimeRuns.size),
      det(on('adb.coworkerDriven'), (_s, p) => pl(p).by !== 'runner' || !GWS.runtimeRuns.size),
      det(on('orca.entitySaved', { entity: 'robot' }), (s, p) => byPlayer(p) && has5555(robotUrl(s.lab, Number(pl(p).id)))),
      det(on('git.fileEdited'), (s, p) => String(pl(p).path).endsWith('config.properties') && currentConfig(s.lab).portNumber === '5555'),
    ],
    teach: {
      whatHappened: 'Port 5555 used.',
      why: '5555 is the ADB default and let scripts drive coworkers\' desk devices; the lab uses 5444. (Ref §4)',
      doInstead: '`portNumber=5444`; `adb connect <ip>:5444`.',
      ref: 'Ref §4',
      factIds: ['F198', 'F199', 'F200'],
      practiceDrillId: 'DR03',
      tag: 'adb.port',
    },
  }),
  d({
    id: 'GW09',
    name: 'Legacy device deleted',
    action: "Delete a Device row that is a robot's legacy/rollback device",
    penalty: 300,
    strike: false,
    tags: ['orca.device'],
    consequence: 'Rollback impossible (INC43 much longer)',
    factIds: ['F119', 'F120'],
    detect: [det(on('orca.entitySaved', { entity: 'device', action: 'delete' }), (_s, p) => byPlayer(p) && isLegacyRow(Number(pl(p).id)))],
    teach: {
      whatHappened: 'Legacy device configuration lost.',
      why: 'Robots link to a separate Device row so upgrades keep the old config for rollback. (Ref §3)',
      doInstead: 'Create a new Device row and relink Robot Device.',
      ref: 'Ref §3',
      factIds: ['F119', 'F120'],
      practiceDrillId: 'DR12',
      tag: 'orca.device',
    },
  }),
  d({
    id: 'GW10',
    name: 'Device row edited in place',
    action: "Change an existing Device row's type/serial in place for a hardware swap",
    penalty: 300,
    strike: false,
    tags: ['orca.device'],
    consequence: 'Legacy config lost',
    factIds: ['F119', 'F120'],
    detect: [
      det(on('orca.entitySaved', { entity: 'device', action: 'update' }), (_s, p) => {
        const f = (pl(p).fields as string[] | undefined) ?? [];
        return byPlayer(p) && f.some((x) => /type|serial/i.test(x));
      }),
    ],
    teach: {
      whatHappened: 'Legacy device configuration lost.',
      why: 'Robots link to a separate Device row so upgrades keep the old config for rollback. (Ref §3)',
      doInstead: 'Create a new Device row and relink Robot Device.',
      ref: 'Ref §3',
      factIds: ['F119', 'F120'],
      practiceDrillId: 'DR12',
      tag: 'orca.device',
    },
  }),
  d({
    id: 'GW11',
    name: 'Security tampering',
    action: 'Uninstall/disable the corporate security agent or delete its logs',
    penalty: 800,
    strike: true,
    tags: ['hw.nuc'],
    consequence: '"Security policy violation" email in LabChat',
    factIds: ['F067', 'F068'],
    detect: [det(on('host.securityTamper'), (_s, p) => byPlayer(p))],
    teach: {
      whatHappened: 'Security monitoring was tampered with.',
      why: 'The NUC disk problem is why hardware control moved to the Pis — not something to delete. (Ref §1)',
      doInstead: 'Move control back to the Pi.',
      ref: 'Ref §1',
      factIds: ['F067', 'F068'],
      practiceDrillId: 'DR17',
      tag: 'hw.nuc',
    },
  }),
  d({
    id: 'GW12',
    name: 'Escalated config issue',
    action: personText('Escalate a non-escalatable issue to {{jared}}'),
    penalty: 100,
    strike: false,
    tags: ['people.roles'],
    consequence: '20 s bounce + teaching bark',
    factIds: ['F111'],
    detect: [],
    teach: {
      whatHappened: '{{jared}} bounced the escalation.',
      why: 'Escalate hardware Connection Failed causes; config issues are yours. (Ref §3)',
      doInstead: 'Read the Notes / Edit view and fix it.',
      ref: 'Ref §3',
      factIds: ['F111'],
      practiceDrillId: 'DR14',
      tag: 'people.roles',
    },
  }),
  d({
    id: 'GW13',
    name: 'Shared infrastructure restarted',
    action: 'Restart the Orca/Jenkins/Ollama VM or power-cycle the GPU blade',
    penalty: 500,
    strike: false,
    tags: ['arch.infra'],
    consequence: 'All running builds fail; VMs down 45 s (they share the blade)',
    factIds: ['F078'],
    cooldownS: 10,
    detect: [
      det(on('host.powerChanged'), (_s, p) => INFRA_HOSTS.has(String(pl(p).hostId)) && pl(p).from === 'on' && pl(p).to !== 'on' && playerTouchedPower(_s.session.clockS, String(pl(p).hostId))),
      det(on('terminal.command'), (_s, p) => /\b(sudo\s+)?(reboot|shutdown)\b/.test(String(pl(p).line)) && /orca|jenkins|ollama|blade/.test(String(pl(p).host))),
    ],
    teach: {
      whatHappened: 'You restarted shared infrastructure.',
      why: 'Orca, Jenkins and Ollama VMs share the GPU blade; restarts kill every running job. (Ref §1)',
      doInstead: 'Restart only the failed service.',
      ref: 'Ref §1',
      factIds: ['F078'],
      practiceDrillId: 'DR17',
      tag: 'arch.infra',
    },
  }),
  d({
    id: 'GW14',
    name: 'Edited app/src/main',
    action: 'Edit any file under uia-remote/app/src/main',
    penalty: 200,
    strike: false,
    tags: ['uia.layout'],
    consequence: personText('PR auto-flagged by {{morgan}}'),
    factIds: ['F164'],
    cooldownS: 30,
    detect: [det(on('git.fileEdited', { repo: 'uia-remote' }), (_s, p) => String(pl(p).path).startsWith('app/src/main'))],
    teach: {
      whatHappened: 'Edited app/src/main.',
      why: 'main holds production/app registration code; QA never modifies it. (Ref §4)',
      doInstead: 'Put tests in the androidTest packages.',
      ref: 'Ref §4',
      factIds: ['F164'],
      practiceDrillId: 'DR15',
      tag: 'uia.layout',
    },
  }),
  d({
    id: 'GW15',
    name: 'Deprecated theme/kernel',
    action: 'theme ≠ avocado or kernelType ≠ CPA',
    penalty: 100,
    strike: false,
    tags: ['uia.config'],
    consequence: 'Local run fails at setup',
    factIds: ['F196', 'F197'],
    cooldownS: 30,
    detect: [det(on('git.fileEdited'), (s, p) => String(pl(p).path).endsWith('config.properties') && configTurnedBad(s.lab))],
    teach: {
      whatHappened: 'Deprecated theme/kernel.',
      why: 'theme is locked to avocado; kernelType to CPA (replaces SPA). (Ref §4)',
      doInstead: '`theme=avocado`, `kernelType=CPA`.',
      ref: 'Ref §4',
      factIds: ['F196', 'F197'],
      practiceDrillId: 'DR02',
      tag: 'uia.config',
    },
  }),
  d({
    id: 'GW16',
    name: 'Resolved too early',
    action: 'Resolve a ticket whose success condition is false',
    penalty: 100,
    strike: false,
    tags: [],
    consequence: 'Combo reset; ticket stays open',
    detect: [],
    teach: {
      whatHappened: 'Resolved too early.',
      why: "The fix isn't verified yet (next health check / next build).",
      doInstead: "Check the ticket's verification line.",
    },
  }),
  d({
    id: 'GW17',
    name: 'Extra power cycle',
    action: 'Redundant power-cycle (target already booting or healthy)',
    penalty: 50,
    strike: false,
    tags: ['orca.healthcheck'],
    consequence: 'Recovery slips to the next health check',
    factIds: ['F099'],
    cooldownS: 1,
    detect: [
      det(on('host.powerChanged'), (_s, p) => {
        const id = String(pl(p).hostId);
        if (!id.startsWith('pi-')) return false;
        // Only a power *cut* counts (a finishing boot is booting → on; a hang is on → crashed), and only
        // one the player caused (not a fault taking the rail down or Jared's fix).
        if (pl(p).to !== 'off' || !playerTouchedPower(_s.session.clockS, id) || recentProtectionTrip(_s.session.clockS)) return false;
        const from = pl(p).from;
        return from === 'booting' || (from === 'on' && GWS.hostHealthy.get(id) === true);
      }),
      det(on('rig.switch', { which: 'main', on: false }), (s, p) => {
        const pi = s.lab.rigs?.[String(pl(p).rigId)]?.piHostId;
        return !!pi && GWS.hostHealthy.get(pi) === true && !GWS.activeTests.has(String(pl(p).rigId));
      }),
    ],
    teach: {
      whatHappened: 'Extra power cycle.',
      why: 'Recovery shows at the next 5-minute health check; cycling again delays it. (Ref §3)',
      doInstead: 'Verify with curl and wait for the ping.',
      ref: 'Ref §3',
      factIds: ['F099'],
      practiceDrillId: 'DR01',
      tag: 'orca.healthcheck',
    },
  }),
  d({
    id: 'GW18',
    name: 'Offsets used to compensate',
    action: 'Enter non-zero Offsets to compensate for coordinate problems',
    penalty: 150,
    strike: false,
    tags: ['orca.offsets'],
    consequence: 'Masks the root cause',
    factIds: ['F129', 'F130'],
    detect: [
      det(on('orca.entitySaved', { entity: 'robot' }), (s, p) => {
        const f = (pl(p).fields as string[] | undefined) ?? [];
        if (!byPlayer(p) || !f.some((x) => /offset/i.test(x))) return false;
        const r = Object.values(s.lab.orca?.robots ?? {}).find((x) => x.id === Number(pl(p).id));
        return !!r && (Math.abs(r.offsetXMm ?? 0) > 1e-9 || Math.abs(r.offsetYMm ?? 0) > 1e-9);
      }),
    ],
    teach: {
      whatHappened: 'Offsets used to compensate.',
      why: 'Offsets are legacy; the lab is calibrated to true (0,0). (Ref §3)',
      doInstead: 'Offsets to 0; fix the coordinates or hardware.',
      ref: 'Ref §3',
      factIds: ['F129', 'F130'],
      practiceDrillId: 'DR12',
      tag: 'orca.offsets',
    },
  }),
  d({
    id: 'GW19',
    name: "Aborted someone's job",
    action: "Abort another engineer's running job without cause",
    penalty: 200,
    strike: false,
    tags: ['hw.lockout'],
    consequence: 'Coworker complaint',
    factIds: ['F230'],
    detect: [
      det(on('jenkins.buildFinished', { result: 'ABORTED' }), (s, p) => {
        const b = s.lab.jenkins?.builds?.[String(pl(p).buildId)];
        return !!b && b.triggeredBy !== 'player' && (b as unknown as { abortedBy?: string }).abortedBy !== 'system';
      }),
    ],
    teach: {
      whatHappened: "You took over someone else's rig.",
      why: 'Active runs and Reserved rigs belong to their engineer. (Ref §3, §6)',
      doInstead: 'Ask in LabChat first.',
      ref: 'Ref §3, §6',
      practiceDrillId: 'DR01',
      tag: 'hw.lockout',
    },
  }),
  d({
    id: 'GW20',
    name: 'Took over a reservation',
    action: 'Change a rig away from Reserved set by someone else without asking',
    penalty: 150,
    strike: false,
    tags: ['orca.status.reserved'],
    consequence: 'Their local run collides with Jenkins',
    factIds: ['F112', 'F113'],
    detect: [
      det(on('robot.statusChanged', { from: 'RESERVED' }), (_s, p) => {
        if (!byPlayer(p)) return false;
        const who = GWS.reservedBy.get(String(pl(p).name));
        return !!who && who !== 'player' && !askedInChat(who);
      }),
    ],
    teach: {
      whatHappened: "You took over someone else's rig.",
      why: 'Active runs and Reserved rigs belong to their engineer. (Ref §3, §6)',
      doInstead: 'Ask in LabChat first.',
      ref: 'Ref §3, §6',
      factIds: ['F112', 'F113'],
      practiceDrillId: 'DR01',
      tag: 'orca.status.reserved',
    },
  }),
  d({
    id: 'GW21',
    name: 'Ω on a live circuit',
    action: 'Ω mode on a powered circuit',
    penalty: 50,
    strike: false,
    tags: ['power.fuses'],
    consequence: 'Meter shows "ERR"',
    detect: [det(on('power.measured', { mode: 'OHM', live: true }))],
    teach: {
      whatHappened: 'Ω mode on a live circuit.',
      why: 'Resistance is measured with power off. [general practice]',
      doInstead: 'Power off, then Ω.',
      practiceDrillId: 'DR13',
      tag: 'power.fuses',
    },
  }),
  d({
    id: 'GW22',
    name: 'Edited the robot Name',
    action: "Edit a robot's Name (system identifier) when the Human Readable Name was meant",
    penalty: 100,
    strike: false,
    tags: ['orca.names'],
    consequence: 'Pipelines and named jobs lose the robot until reverted',
    factIds: ['F117', 'F118'],
    detect: [det(on('orca.entitySaved', { entity: 'robot', action: 'update' }), (_s, p) => byPlayer(p) && ((pl(p).fields as string[] | undefined) ?? []).includes('name'))],
    teach: {
      whatHappened: "You edited the robot's Name.",
      why: 'Name is the system identifier pipelines use; the tablet shows the Human Readable Name. (Ref §3)',
      doInstead: 'Revert Name; edit Human Readable Name.',
      ref: 'Ref §3',
      factIds: ['F117', 'F118'],
      practiceDrillId: 'DR12',
      tag: 'orca.names',
    },
  }),
  d({
    id: 'GW23',
    name: "Unplugged a coworker's device",
    action: "Unplug or power off a coworker's desk device to stop a collision",
    penalty: 100,
    strike: false,
    tags: ['adb.port'],
    consequence: personText('{{riley}} annoyed; the config is still wrong'),
    factIds: ['F200'],
    detect: [
      det(on('power.unplugged'), (s, p) => isCoworkerDevice(s.lab, String(pl(p).loadId))),
      det(on('device.powerChanged'), (s, p) => pl(p).to === 'off' && isCoworkerDevice(s.lab, String(pl(p).deviceId))),
    ],
    teach: {
      whatHappened: "You unplugged a coworker's device.",
      why: 'The problem is your port, not their desk. (Ref §4)',
      doInstead: 'Stop the run, disconnect, set 5444.',
      ref: 'Ref §4',
      factIds: ['F200'],
      practiceDrillId: 'DR03',
      tag: 'adb.port',
    },
  }),
  d({
    id: 'GW24',
    name: 'Overrode a failed health check',
    action: 'Manually set a Connection Failed rig to Available while the cause persists',
    penalty: 200,
    strike: true,
    tags: ['orca.status.connfailed'],
    consequence: 'A pipeline checks out a dead rig (red build); next ping flips it back',
    factIds: ['F107', 'F108', 'F111'],
    detect: [
      det(on('robot.statusChanged', { from: 'CONNECTION_FAILED', to: 'AVAILABLE' }), (s, p) => byPlayer(p) && connFailedCausePersists(s.lab, String(pl(p).name))),
    ],
    teach: {
      whatHappened: 'You overrode a failed health check.',
      why: 'Connection Failed blocks checkouts for a reason; the next ping will flip it back. (Ref §3)',
      doInstead: 'Find the cause or escalate to {{jared}} with the endpoint.',
      ref: 'Ref §3',
      factIds: ['F107', 'F108', 'F111'],
      practiceDrillId: 'DR01',
      tag: 'orca.status.connfailed',
    },
  }),
];

export const GW_BY_ID: Readonly<Record<string, GlobalWrongActionDef>> = Object.fromEntries(GLOBAL_WRONG_ACTIONS.map((g) => [g.id, g]));

/** Bark per GW (GP §5.4). */
export const GW_BARKS: Readonly<Record<string, string>> = {
  GW01: 'BARK_JARED_02',
  GW02: 'BARK_JARED_02',
  GW05: 'BARK_TATE_03',
  GW07: 'BARK_RILEY_01',
  GW12: 'BARK_JARED_05',
  GW14: 'BARK_MORGAN_02',
  GW18: 'BARK_JARED_07',
  GW19: 'BARK_RILEY_01',
  GW20: 'BARK_TATE_04',
  GW22: 'BARK_TATE_05',
  GW24: 'BARK_TATE_02',
};

