/**
 * Fact inventory — every teachable fact in the reference (Cur §1, F001–F245) plus the curriculum's
 * sim-only illustrative details (Cur §0.3, S01–S20).
 *
 * Generated from docs/design/10-curriculum.md (§1 table, text verbatim; people as `{{key}}` tokens, see people.ts). `tags` = the default topic tag of
 * the first "Taught in" module (Cur §8) followed by the fine tags of GP §4.8.1. `S##` facts are
 * `illustrative: true`: the Field Manual badges them "Illustrative (sim only)" and no quiz item may cite them.
 */
import type { Fact, FactTier } from './schema';
import { resolvePeople } from './people';

/** Reference section names for the curriculum's short `Ref` codes. */
export const FACT_SECTIONS: Record<string, string> = {
  "§1.1": "1. Technology Stack > Languages, Frameworks & Build Tools",
  "§1.2": "1. Technology Stack > Infrastructure, Databases & Operating Systems",
  "§1.3": "1. Technology Stack > Developer Utilities, Computer Vision & AI",
  "§1.4": "1. Technology Stack > Internal Repositories & Proprietary Subsystems",
  "§1.5": "1. Technology Stack > Lab Hardware, Robotics & Electrical Engineering",
  "§2": "2. System Architecture & Execution Flow",
  "§3": "3. Orchestrator (Orca) & Database Entities",
  "§3.1": "3. Orchestrator > The 5 Robot Operational Statuses",
  "§3.2": "3. Orchestrator > The 7 Core Database Schemas",
  "§4.1": "4. uia-remote > Team History & Scope Expansion",
  "§4.2": "4. uia-remote > Directory Structure & Multi-Device Execution",
  "§4.3": "4. uia-remote > Page Object Model & Synchronization Rules",
  "§4.4": "4. uia-remote > End-to-End Test Flow: The Tax Test",
  "§4.5": "4. uia-remote > Local Configuration (config.properties)",
  "§5": "5. Pigeon Repository (Legacy LSTR Framework)",
  "§6.1": "6. Hardware, Power & Lab Operations > ADB Bots vs Physical/Interactive Bots",
  "§6.2": "6. Hardware, Power & Lab Operations > Card Testing Philosophy",
  "§6.3": "6. Hardware, Power & Lab Operations > Power Distribution Architecture",
  "§6.4": "6. Hardware, Power & Lab Operations > Motor Control & Safety Locks",
  "IMG-T": "Reference photo > walle-status-tablet-front.jpg",
  "IMG-R": "Reference photo > tethered-megatron-optimus-rack.jpg",
  "IMG-G": "Reference photo > touch-robot-side-gantry.jpg",
  "IMG-V": "Reference video > solenoid-tapping-flex3.mp4"
};

function fact(id: string, ref: string, tier: FactTier, taughtIn: string[], tags: string[], text: string): Fact {
  return { id, ref, section: FACT_SECTIONS[ref] ?? ref, tier, taughtIn, tags, text };
}

function simFact(id: string, tags: string[], text: string): Fact {
  return { id, ref: 'Cur §0.3', section: 'Sim-only illustrative detail', tier: 'trivia', taughtIn: [], tags, text, illustrative: true };
}

/** F001–F245, in id order. */
export const FACTS: Fact[] = resolvePeople([
  fact("F001", "§1.1", "core", ["M06", "M13"], ["orca.status", "arch.stack"], "Java (Oracle Java) is the primary programming language powering both the Orchestrator backend and the uia-remote test automation suites."),
  fact("F002", "§1.1", "core", ["M06"], ["orca.status", "arch.stack"], "Spring Boot is the backend web framework used to build the Orchestrator monolith and its REST API endpoints."),
  fact("F003", "§1.1", "supporting", ["M06"], ["orca.status", "arch.stack"], "JHipster is a rapid application development platform that scaffolded Orchestrator through an interactive setup questionnaire."),
  fact("F004", "§1.1", "supporting", ["M06"], ["orca.status", "arch.stack"], "JHipster auto-generated Orchestrator's frontend UI, its Spring Boot REST endpoints and its MySQL database schemas."),
  fact("F005", "§1.1", "core", ["M13"], ["uia.pom"], "Android UI Automator is Google's native Android instrumentation framework and is the engine used inside uia-remote."),
  fact("F006", "§1.1", "core", ["M13", "M16"], ["uia.pom", "uia.v23"], "uia-remote specifically uses UI Automator version 2.3."),
  fact("F007", "§1.1", "core", ["M16"], ["duo.ocr", "uia.v23"], "UI Automator 2.3 is chosen because it adds native support for dual-screen element location tracking."),
  fact("F008", "§1.1", "supporting", ["M08"], ["orca.capabilities", "go.sdk"], "Go (Golang) is used for the Terminal SDK."),
  fact("F009", "§1.1", "supporting", ["M08", "M15"], ["orca.capabilities", "go.sdk"], "The Go SDK is supported via custom extensions in Orchestrator and is tested through Pigeon and mobile runners."),
  fact("F010", "§1.1", "supporting", ["M13"], ["uia.pom", "uia.layout"], "The uia-remote Android project layout mirrors the Apache Maven build-structure standard."),
  fact("F011", "§1.1", "supporting", ["M08"], ["orca.capabilities", "arch.stack"], "JSON is the data format used for runtime capability lookups in Orchestrator."),
  fact("F012", "§1.1", "core", ["M15"], ["pigeon", "pigeon.json"], "JSON is the format used to write declarative, platform-agnostic test payloads in the legacy Pigeon repository."),
  fact("F013", "§1.2", "core", ["M06", "M17"], ["orca.status", "arch.stack"], "MySQL is the relational database engine backing Orchestrator."),
  fact("F014", "§1.2", "supporting", ["M07"], ["orca.entities", "arch.stack"], "Orca's MySQL database stores all hardware states, merchant profiles and screen-coordinate tables (robots, devices, screens, card profiles, merchants)."),
  fact("F015", "§1.2", "core", ["M11"], ["jenkins", "jenkins.envvars", "arch.roles"], "Jenkins is the CI/CD execution engine, called the \"Executor\"."),
  fact("F016", "§1.2", "core", ["M11"], ["jenkins", "jenkins.envvars"], "Jenkins triggers test pipelines and injects runtime environment variables into them."),
  fact("F017", "§1.2", "supporting", ["M11"], ["jenkins", "jenkins.folders"], "Jenkins organises legacy jobs by platform, separating Java jobs from iOS jobs."),
  fact("F018", "§1.2", "core", ["M13", "M17"], ["uia.pom", "arch.repos", "tools.github"], "GitHub hosts the team's repositories (Gort, uia-remote, pigeon) for branch management and pull requests."),
  fact("F019", "§1.2", "core", ["M05"], ["pi.controller", "hw.pi"], "Linux is the lightweight operating system deployed on the lab's Raspberry Pi controllers."),
  fact("F020", "§1.2", "supporting", ["M05"], ["pi.controller", "hw.pi"], "Running Linux on the Pis isolates hardware control loops from the corporate Windows machines."),
  fact("F021", "§1.2", "core", ["M05"], ["pi.controller", "cards.wine"], "Wine runs on the Raspberry Pi Linux environments to emulate the Windows-only card-programming software layers."),
  fact("F022", "§1.2", "supporting", ["M17"], ["infra.ai", "arch.infra"], "Docker and Google Cloud Platform (GCP) are the planned migration targets for containerising Orchestrator."),
  fact("F023", "§1.2", "core", ["M06", "M17"], ["orca.status", "arch.stack", "arch.infra"], "Orchestrator currently runs on a local, on-premise laboratory Virtual Machine (which the Docker/GCP plan would move it off)."),
  fact("F024", "§1.3", "core", ["M12"], ["adb.port", "adb.usage"], "ADB (Android Debug Bridge) is the command-line tool used to inspect XML UI hierarchies and locate elements."),
  fact("F025", "§1.3", "core", ["M12"], ["adb.port", "adb.usage"], "ADB is used to dispatch programmatic touch events to a device."),
  fact("F026", "§1.3", "core", ["M12"], ["adb.port"], "In the LabSim lab, ADB runs over port 5444."),
  fact("F027", "§1.3", "core", ["M13"], ["uia.pom", "tools.intellij"], "IntelliJ IDEA is the team's primary IDE."),
  fact("F028", "§1.3", "supporting", ["M13"], ["uia.pom", "tools.intellij"], "IntelliJ IDEA is used to import repositories, configure local properties and execute test suites from developer workstations."),
  fact("F029", "§1.3", "core", ["M16"], ["duo.ocr", "vision.tesseract"], "Tesseract OCR is the open-source OCR engine run on cropped webcam screenshots to validate text on displays that are blind to ADB."),
  fact("F030", "§1.3", "core", ["M16"], ["duo.ocr", "pigeon.gimp"], "GIMP is used to open device screenshots, draw selection bounding boxes around text elements and extract exact spatial coordinates for legacy screen-comparison blocks."),
  fact("F031", "§1.3", "core", ["M17"], ["infra.ai", "vision.ollama"], "Ollama is a local LLM runner hosted on the lab's 4-GPU server blade."),
  fact("F032", "§1.3", "supporting", ["M17"], ["infra.ai", "vision.ollama"], "Ollama currently runs proof-of-concept Vision-LLM inspections of webcam streams to validate receipt layouts and tip math."),
  fact("F033", "§1.3", "supporting", ["M17"], ["infra.ai", "tools.claude"], "Claude was evaluated during corporate AI initiatives for repository optimisation and automated test generation."),
  fact("F034", "§1.4", "core", ["M10"], ["cards", "arch.repos"], "Gort is the core monorepo housing the automated testing ecosystem and its distinct configuration modules."),
  fact("F035", "§1.4", "core", ["M10"], ["cards", "arch.repos", "cards.diptap"], "Gort holds the virtual card definition files used by Dip and Tap profiles."),
  fact("F036", "§1.4", "core", ["M06"], ["orca.status", "arch.roles"], "\"Orca\" is the team's short name for the Orchestrator."),
  fact("F037", "§1.4", "core", ["M06"], ["orca.status", "arch.stack"], "Orca is an on-premise Spring Boot monolith."),
  fact("F038", "§1.4", "core", ["M06"], ["orca.status", "arch.roles"], "Orca acts as the central Controller between Jenkins pipelines and the physical lab robots."),
  fact("F039", "§1.4", "core", ["M13"], ["uia.pom", "arch.repos"], "uia-remote is the team's modern Java / UI Automator test repository."),
  fact("F040", "§1.4", "core", ["M13"], ["uia.pom", "arch.repos"], "uia-remote automates both standalone devices and tethered multi-device setups across native LabSim apps."),
  fact("F041", "§1.4", "core", ["M15"], ["pigeon", "pigeon.lstr"], "Pigeon, also called LSTR, is the team's legacy test repository."),
  fact("F042", "§1.4", "trivia", ["M15", "M18"], ["pigeon", "pigeon.lstr"], "The name \"Pigeon\" is a play on words on \"pidgin language\"."),
  fact("F043", "§1.4", "supporting", ["M15", "M18"], ["pigeon", "pigeon.lstr"], "Pigeon evolved from the Lester framework."),
  fact("F044", "§1.4", "core", ["M15"], ["pigeon", "pigeon.lstr"], "LSTR stands for Language Specific Test Runner."),
  fact("F045", "§1.4", "core", ["M15"], ["pigeon", "pigeon.lstr", "pigeon.json"], "Pigeon parses raw JSON test payloads across REST, Android, Windows and iOS."),
  fact("F046", "§1.4", "core", ["M08"], ["orca.capabilities", "laz.oobe"], "Laz Automation is an automated provisioning framework that runs a zero-touch OOBE (Out-of-Box Experience) routine."),
  fact("F047", "§1.4", "core", ["M08"], ["orca.capabilities", "laz.oobe"], "Laz's OOBE routine de-provisions hardware, wipes local caches, steps through the setup wizard and swaps merchants mid-suite."),
  fact("F048", "§1.4", "supporting", ["M10"], ["cards", "cards.callus"], "Callus is also referred to as \"Callers\" or \"Collos\"."),
  fact("F049", "§1.4", "core", ["M10"], ["cards", "cards.callus"], "Callus is a microservice subsystem that runs on the local Windows/Minix boxes."),
  fact("F050", "§1.4", "core", ["M10"], ["cards", "cards.callus"], "Callus reads card-profile paths from Gort and drives the physical Collis probes during virtual card transactions."),
  fact("F051", "§1.4", "supporting", ["M08"], ["orca.capabilities", "ubi.routing"], "Ubi Platform is the internal routing platform used when test jobs dynamically switch merchant configurations."),
  fact("F052", "§1.4", "supporting", ["M18"], ["teams.history", "semi.paydisplay"], "USB Pay Display and Secure Network Pay Display are applications maintained by the Semi Team."),
  fact("F053", "§1.4", "supporting", ["M18"], ["teams.history", "semi.paydisplay"], "USB Pay Display and Secure Network Pay Display link Merchant Facing Devices and Customer Facing Devices over USB or the local network."),
  fact("F054", "§1.4", "core", ["M02", "M14"], ["devices", "hw.devices"], "MFD means Merchant Facing Device and CFD means Customer Facing Device."),
  fact("F055", "§1.5", "core", ["M02"], ["devices", "hw.devices"], "The Station series targets are Station 2018, Station 2 and Station Duo (Duo 1, Duo 2 and the upcoming Duo 3)."),
  fact("F056", "§1.5", "core", ["M02"], ["devices", "hw.devices"], "The Mini series targets are Mini 2, Mini 3 and the upcoming Mini 4."),
  fact("F057", "§1.5", "supporting", ["M02"], ["devices", "hw.devices"], "The Mini 3 is used as a hot-swap equivalent for the printerless Station Duo 2."),
  fact("F058", "§1.5", "core", ["M02"], ["devices", "hw.devices"], "The Flex series targets are Flex 1, Flex 2, Flex 3, Flex 4 and Flex Pocket."),
  fact("F059", "§1.5", "core", ["M02"], ["devices", "hw.devices"], "Flex 3, Flex 4 and Flex Pocket share exactly the same testing profile."),
  fact("F060", "§1.5", "supporting", ["M02"], ["devices", "hw.devices"], "The Flex Pocket omits the physical printer block."),
  fact("F061", "§1.5", "supporting", ["M02"], ["devices", "hw.devices"], "The LabSim Compact is the target terminal for the Canadian market and is used on the Westers test beds."),
  fact("F062", "§1.5", "trivia", ["M02"], ["devices", "hw.devices"], "The Station Duo 3 and the Mini 4 are upcoming devices."),
  fact("F063", "§1.5", "supporting", ["M05"], ["pi.controller", "hw.pi"], "The lab's Raspberry Pis are cheap units of about $50 each."),
  fact("F064", "§1.5", "core", ["M05"], ["pi.controller", "hw.pi"], "A Raspberry Pi operates as the Robot Pi / Robot Controller on each shelf."),
  fact("F065", "§1.5", "core", ["M05"], ["pi.controller", "hw.pi"], "The Robot Pi handles ADB routing, camera streams, stepper motors, solenoids and Wine card-programming emulation."),
  fact("F066", "§1.5", "core", ["M05", "M17"], ["pi.controller", "hw.nuc"], "Intel NUC and Minix boxes are the local Windows execution machines in the lab (the NUCs are listed as ASUS NUC)."),
  fact("F067", "§1.5", "core", ["M05"], ["pi.controller", "hw.nuc"], "Aggressive corporate security-monitoring packages exhausted the disk space on the NUCs."),
  fact("F068", "§1.5", "core", ["M05", "M17"], ["pi.controller", "hw.nuc"], "Because of the corporate disk exhaustion, physical hardware control was migrated off the NUCs onto Raspberry Pis."),
  fact("F069", "§1.5", "core", ["M10"], ["cards", "hw.collis"], "Collis probes (UL Transaction Security) are high-cost proprietary card emulators."),
  fact("F070", "§1.5", "supporting", ["M10"], ["cards", "hw.collis"], "Collis probes connect to the rig via rear ribbon cables."),
  fact("F071", "§1.5", "core", ["M10"], ["cards", "hw.collis"], "Collis probes simulate magnetic-stripe swipes, EMV chip dips and contactless NFC taps."),
  fact("F072", "§1.5", "supporting", ["M01"], ["lab.orientation", "hw.print3d"], "Prusa and Bambu Lab 3D printers print all of the black plastic modular shelf fixtures."),
  fact("F073", "§1.5", "trivia", ["M01"], ["lab.orientation", "hw.print3d"], "The shelf fixtures are drafted in CAD using simple geometric shapes."),
  fact("F074", "§1.5", "core", ["M03"], ["power.rails"], "Mean Well transformers are the industrial power supplies that convert 120V AC wall power to a central 24V DC rail."),
  fact("F075", "§1.5", "core", ["M17"], ["infra.ai", "arch.infra"], "Four NVIDIA GPUs are installed in a shelf-mounted server blade."),
  fact("F076", "§1.5", "trivia", ["M17"], ["infra.ai", "arch.infra"], "Of the four GPUs in the blade, two are exposed and two are underneath."),
  fact("F077", "§1.5", "supporting", ["M17"], ["infra.ai", "arch.infra"], "The GPU server blade replaced a legacy tower unit."),
  fact("F078", "§1.5", "core", ["M17"], ["infra.ai", "arch.infra"], "The GPU server blade hosts the VMs, Orca, Jenkins and Ollama."),
  fact("F079", "§1.5", "supporting", ["M04"], ["robots.mechanics", "hw.rigbom"], "The rigs use sub-millimetre stepper motors."),
  fact("F080", "§1.5", "core", ["M04"], ["robots.mechanics", "hw.rigbom"], "The rigs use remote-firing solenoids whose plunger drops onto the screen to tap."),
  fact("F081", "§1.5", "supporting", ["M04"], ["robots.mechanics", "hw.rigbom", "hw.motion"], "Each rig arm is held by a magnetic lock."),
  fact("F082", "§1.5", "core", ["M04", "M09"], ["robots.mechanics", "hw.rigbom", "hw.motion"], "Physical limit switches are calibrated to the (0,0) origin."),
  fact("F083", "§1.5", "supporting", ["M04"], ["robots.mechanics", "hw.rigbom"], "The rigs use custom 25-pin motor-controller PCBs."),
  fact("F084", "§1.5", "trivia", ["M04"], ["robots.mechanics", "hw.rigbom"], "The custom motor-controller PCBs were printed in Hong Kong."),
  fact("F085", "§1.5", "core", ["M03"], ["power.rails"], "A DC step-down regulator provides a 12V DC line for the Intel NUCs."),
  fact("F086", "§1.5", "core", ["M03"], ["power.rails"], "A DC step-down regulator provides a 5V DC, 10-Amp line for the Raspberry Pis."),
  fact("F087", "§1.5", "supporting", ["M03"], ["power.rails", "power.fuses"], "Inline fuses protect the DC lines."),
  fact("F088", "§1.5", "supporting", ["M04", "M16"], ["robots.mechanics", "hw.rigbom", "vision.camera"], "The rigs carry webcams (the source of camera streams and OCR screenshots)."),
  fact("F089", "§1.5", "core", ["M01"], ["lab.orientation", "hw.tablet"], "Each touch robot has a front-mounted status tablet."),
  fact("F090", "§1.5", "trivia", ["M04"], ["robots.mechanics", "hw.rigbom"], "A touch robot uses 10 ft cut aluminium rails."),
  fact("F091", "§1.5", "trivia", ["M04"], ["robots.mechanics", "hw.rigbom"], "A touch robot contains about 130 ft of wiring."),
  fact("F092", "§1.5", "trivia", ["M04"], ["robots.mechanics", "hw.rigbom"], "A touch robot has about 300 manual solder points."),
  fact("F093", "§1.5", "trivia", ["M04"], ["robots.mechanics", "hw.rigbom"], "A touch robot uses 200+ nuts and bolts in 2.5mm and 5mm diameters."),
  fact("F094", "§2", "core", ["M06", "M11"], ["orca.status", "arch.flow"], "In the execution flow, Jenkins triggers the pipeline and injects environment variables into the test runner (uia-remote or Pigeon)."),
  fact("F095", "§2", "core", ["M06", "M11"], ["orca.status", "arch.flow", "jenkins.checkout"], "Jenkins checks out a robot from Orca before the test runs."),
  fact("F096", "§2", "core", ["M06", "M09"], ["orca.status", "arch.flow", "orca.xytouch"], "The test runner calls Orca over REST for xy_touch and for card swipe / dip / tap."),
  fact("F097", "§2", "core", ["M06", "M10"], ["orca.status", "arch.flow", "cards.callus"], "The Windows/Minix box running Callus drives the Collis probe over a ribbon cable, and the Collis probe feeds the LabSim device's card reader."),
  fact("F098", "§3", "core", ["M06"], ["orca.status", "arch.roles"], "Orchestrator is the Controller and Jenkins is the Executor."),
  fact("F099", "§3", "core", ["M06"], ["orca.status", "orca.healthcheck"], "Every 5 minutes Orca runs a synchronized background thread that pings the Robot Controller on every Raspberry Pi."),
  fact("F100", "§3.1", "core", ["M06"], ["orca.status"], "There are exactly 5 robot operational statuses: Available, Unavailable, Offline, Connection Failed and Reserved."),
  fact("F101", "§3.1", "core", ["M06"], ["orca.status"], "Available means the robot is online, healthy and open to general pipeline checkouts."),
  fact("F102", "§3.1", "core", ["M06", "M11"], ["orca.status", "orca.status.unavailable"], "Unavailable is a strictly reserved state: general pipelines cannot check the robot out unless an engineer passes the robot's exact unique name in the job parameters."),
  fact("F103", "§3.1", "core", ["M06", "M18"], ["orca.status", "orca.status.unavailable"], "Unavailable isolates specialised rigs (such as PayCore standalone setups) so general tests do not overwrite their merchant profiles."),
  fact("F104", "§3.1", "core", ["M06"], ["orca.status", "orca.status.unavailable"], "When an explicitly named job finishes, Orca automatically resets the robot back to Unavailable."),
  fact("F105", "§3.1", "core", ["M06"], ["orca.status", "orca.status.offline"], "Offline is a manual placeholder state used while engineers physically build a rig or assemble data profiles."),
  fact("F106", "§3.1", "core", ["M06"], ["orca.status", "orca.status.offline", "orca.healthcheck"], "Orca bypasses the 5-minute health check for Offline units."),
  fact("F107", "§3.1", "core", ["M06"], ["orca.status", "orca.status.connfailed", "orca.healthcheck"], "Connection Failed is set automatically when the 5-minute REST ping to the Pi drops or returns a non-200 HTTP response."),
  fact("F108", "§3.1", "core", ["M06"], ["orca.status", "orca.status.connfailed"], "A Connection Failed robot is blocked from checkouts."),
  fact("F109", "§3.1", "core", ["M06"], ["orca.status", "orca.status.connfailed", "orca.notes"], "Connection Failed opens a Notes section in the Orca UI logging the exact endpoint attempted and the error text."),
  fact("F110", "§3.1", "supporting", ["M06", "M18"], ["orca.status", "orca.status.connfailed"], "Typical Connection Failed causes are a crashed Pi board or a Minix box running Callus services going offline."),
  fact("F111", "§3.1", "core", ["M06"], ["orca.status", "orca.status.connfailed", "people.roles"], "Connection Failed robots are escalated to {{jared}} for hardware intervention."),
  fact("F112", "§3.1", "core", ["M06"], ["orca.status", "orca.status.reserved"], "Reserved is set manually by an engineer who is running tests locally from their workstation."),
  fact("F113", "§3.1", "core", ["M06"], ["orca.status", "orca.status.reserved"], "Reserved blocks both Jenkins pipelines and health-check overrides."),
  fact("F114", "§3.2", "supporting", ["M07"], ["orca.entities", "arch.stack"], "Orca has 7 core database schemas, generated as JHipster entities."),
  fact("F115", "§3.2", "core", ["M01", "M07"], ["lab.orientation", "orca.robot"], "The Robot entity tracks the pool of 40+ rigs and their operational status flags."),
  fact("F116", "§3.2", "supporting", ["M06"], ["orca.status", "orca.robot", "people.roles"], "{{tate}} built the custom UI filtering for the Robot list."),
  fact("F117", "§3.2", "core", ["M07"], ["orca.entities", "orca.names"], "A robot has a Name (system identifier) and a Human Readable Name (display string)."),
  fact("F118", "§3.2", "core", ["M07"], ["orca.entities", "orca.names", "hw.tablet"], "The Human Readable Name is pushed to the physical status tablet mounted on the front of the lab enclosure."),
  fact("F119", "§3.2", "core", ["M07"], ["orca.entities", "orca.device"], "The Robot Device field links the robot to a separate Device entity."),
  fact("F120", "§3.2", "core", ["M07"], ["orca.entities", "orca.device"], "Decoupling the Device from the Robot means a hardware upgrade (e.g. Flex 1 to Flex 2) leaves legacy configurations intact for quick rollbacks."),
  fact("F121", "§3.2", "core", ["M07"], ["orca.entities", "orca.devicetype"], "Device Type is an enum that stores device dimensions, layout metrics and internal string definitions."),
  fact("F122", "§3.2", "core", ["M07", "M11"], ["orca.entities", "orca.devicetype", "jenkins.envvars"], "The Device Type enum is the reason Jenkins pipeline environment variables must be in ALL CAPS."),
  fact("F123", "§3.2", "core", ["M07"], ["orca.entities", "orca.urls"], "URL Mappings store the Robot ADB Service URL, which routes to the Pi controller."),
  fact("F124", "§3.2", "supporting", ["M07"], ["orca.entities", "orca.urls", "vision.camera"], "The Camera Stream URL is either dedicated per Pi or shared across 4 rigs."),
  fact("F125", "§3.2", "core", ["M07"], ["orca.entities", "orca.urls"], "URL Mappings also store the hardware-specific Dip, Tap and Swipe URLs."),
  fact("F126", "§3.2", "core", ["M07"], ["orca.entities", "orca.tethered"], "USB Tethered Device Configuration populates MFD and CFD relations for nested setups."),
  fact("F127", "§3.2", "supporting", ["M07"], ["orca.entities", "orca.tethered"], "Tethered examples include a Station 2 tethered to a Mini 2 and nested Mini 3 rigs."),
  fact("F128", "§3.2", "core", ["M07"], ["orca.entities", "orca.tethered"], "If the MFD field is populated, the pipeline treats the rig as tethered."),
  fact("F129", "§3.2", "core", ["M07"], ["orca.entities", "orca.offsets"], "Offsets are legacy millimetre coordinate adjustments once used to compensate for imprecise physical limit switches."),
  fact("F130", "§3.2", "core", ["M07"], ["orca.entities", "orca.offsets", "people.roles"], "{{jared}} calibrated the lab hardware to a true (0,0) origin, which made the Offsets field mostly deprecated."),
  fact("F131", "§3.2", "core", ["M08"], ["orca.capabilities"], "The Robot Capabilities entity controls how Orca matches pipeline requests to physical hardware."),
  fact("F132", "§3.2", "core", ["M08"], ["orca.capabilities"], "Dynamic JSON lookups are used by SDK frameworks: capabilities are defined as JSON metadata inside individual test definitions and parsed at runtime."),
  fact("F133", "§3.2", "supporting", ["M08"], ["orca.capabilities", "people.roles"], "{{david}} oversees the SDK frameworks that use dynamic JSON capability lookups."),
  fact("F134", "§3.2", "core", ["M08"], ["orca.capabilities"], "Non-dynamic lookups are used by traditional UI Automator suites: capabilities are hardcoded inside the pipeline script."),
  fact("F135", "§3.2", "supporting", ["M08"], ["orca.capabilities"], "Both lookup methods are used interchangeably for Contact Canada automation scripts running on Westers test beds."),
  fact("F136", "§3.2", "core", ["M08"], ["orca.capabilities", "orca.merchant"], "The Merchant Config entity stores merchant account parameters."),
  fact("F137", "§3.2", "core", ["M08"], ["orca.capabilities", "orca.merchant"], "Because of UI table display limits, you must click Edit on a Merchant Config row to view all of its fields."),
  fact("F138", "§3.2", "core", ["M08"], ["orca.capabilities", "orca.merchant", "people.roles"], "{{tate}} extended Merchant Config with App ID, App Secret and API Key fields."),
  fact("F139", "§3.2", "core", ["M08"], ["orca.capabilities", "orca.merchant", "go.sdk"], "Pipelines export App ID, App Secret and API Key as runtime environment variables for the Go SDK."),
  fact("F140", "§3.2", "supporting", ["M08"], ["orca.capabilities", "orca.merchant", "laz.oobe"], "Merchant Config works alongside Laz Automation for dynamic OOBE merchant switching."),
  fact("F141", "§3.2", "core", ["M09"], ["orca.screens"], "The Screens entity maps discrete UI layouts within a transaction flow relative to the target device architecture (e.g. a cash-discount tender selection prompt)."),
  fact("F142", "§3.2", "core", ["M09"], ["orca.screens"], "The Screen Locations entity maps exact button placements using relative X and Y coordinates in millimetres."),
  fact("F143", "§3.2", "core", ["M09"], ["orca.screens", "orca.xytouch"], "Scripts call Orca's xy_touch REST endpoint with a screen name and a button string."),
  fact("F144", "§3.2", "core", ["M09"], ["orca.screens", "orca.xytouch"], "For xy_touch, Orca looks up the millimetre coordinates and instructs the Pi to fire either an electronic ADB touch or a physical mechanical probe tap."),
  fact("F145", "§3.2", "core", ["M10"], ["cards", "cards.swipe"], "Swipe profiles store raw Track Data text strings directly in the MySQL table."),
  fact("F146", "§3.2", "supporting", ["M10"], ["cards", "cards.swipe"], "Swipe Track Data is extracted with a hardware card-reader utility."),
  fact("F147", "§3.2", "core", ["M10"], ["cards", "cards.diptap"], "Dip and Tap profiles store file paths pointing to card definitions inside the Gort repository."),
  fact("F148", "§3.2", "core", ["M10"], ["cards", "cards.callus"], "A scheduled job clones the Gort card-definition files onto the local Windows boxes."),
  fact("F149", "§3.2", "core", ["M10"], ["cards", "cards.callus"], "During a test run, Callus servers map the file path and load the virtual card."),
  fact("F150", "§3.2", "core", ["M16"], ["duo.ocr", "orca.screencompare"], "The Screen Compare Image entity is the Station Duo workaround."),
  fact("F151", "§3.2", "core", ["M16"], ["duo.ocr", "orca.screencompare", "uia.v23"], "On the Station Duo one terminal drives two displays, but only the primary MFD is exposed to ADB."),
  fact("F152", "§3.2", "core", ["M16"], ["duo.ocr", "orca.screencompare", "uia.v23"], "Legacy UI Automator was completely blind to the Station Duo's secondary CFD."),
  fact("F153", "§3.2", "core", ["M16"], ["duo.ocr", "orca.screencompare"], "The OCR workaround stores spatial bounding coordinates on the CFD alongside the expected text string."),
  fact("F154", "§3.2", "core", ["M16"], ["duo.ocr", "orca.screencompare", "vision.tesseract", "vision.camera"], "In the OCR workaround the Robot Controller captures a webcam screenshot, crops it to the bounding box, runs Tesseract OCR and returns a boolean match result."),
  fact("F155", "§3.2", "core", ["M16"], ["duo.ocr", "orca.screencompare"], "The OCR workaround is extremely brittle: a 10-pixel button shift, a capitalisation change or a typo breaks the suite."),
  fact("F156", "§3.2", "core", ["M16"], ["duo.ocr", "orca.screencompare", "uia.v23"], "Screen Compare / OCR is being phased out because UI Automator 2.3 natively supports dual-screen element tracking."),
  fact("F157", "§4.1", "supporting", ["M18"], ["teams.history", "uia.history"], "Historically the Semi Team developed third-party POS SDKs and the remote pay display apps."),
  fact("F158", "§4.1", "supporting", ["M18"], ["teams.history", "uia.history"], "The Sedi (QA) Team tested the Semi Team's apps using the legacy Lester framework."),
  fact("F159", "§4.1", "core", ["M13", "M18"], ["uia.pom", "uia.history", "people.roles"], "The presenter ({{morgan}} in-game) created uia-remote because no prior framework could automate native tethered setups: Station-to-Mini, Mini-to-Mini and Station Duo."),
  fact("F160", "§4.1", "supporting", ["M18"], ["teams.history", "uia.history"], "uia-remote is now integrated with the IPX (Integrated Payment Experience) Team."),
  fact("F161", "§4.1", "supporting", ["M18"], ["teams.history", "uia.history"], "With IPX, uia-remote tests standalone and tethered devices across the native apps Register, Orders, Authorizations, Sale, Transactions and Setup."),
  fact("F162", "§4.1", "supporting", ["M18"], ["teams.history", "uia.history"], "The PayCore Team adopted uia-remote for apps like LabSim Dining."),
  fact("F163", "§4.2", "core", ["M13"], ["uia.pom", "uia.layout"], "uia-remote is built inside a standard Android/Maven structure under app/src/."),
  fact("F164", "§4.2", "core", ["M13"], ["uia.pom", "uia.layout"], "app/src/main is reserved for production/application registration code; QA engineers never modify it."),
  fact("F165", "§4.2", "core", ["M13"], ["uia.pom", "uia.layout"], "app/src/test houses local unit tests and the multi-device execution runner scripts."),
  fact("F166", "§4.2", "core", ["M13"], ["uia.pom", "uia.layout"], "app/src/androidTest houses instrumented tests that execute on Android hardware, split into three packages."),
  fact("F167", "§4.2", "core", ["M13"], ["uia.pom", "uia.packages"], "The androidTest package databases holds database connection and query logic."),
  fact("F168", "§4.2", "core", ["M13"], ["uia.pom", "uia.packages"], "The androidTest package pageobjects holds the Page Object Model classes representing individual device screens."),
  fact("F169", "§4.2", "core", ["M13"], ["uia.pom", "uia.packages"], "The androidTest package testactions holds test classes and logical assertions that string page-object methods together."),
  fact("F170", "§4.2", "core", ["M13"], ["uia.pom", "uia.multidevice"], "Google designed UI Automator to communicate with only one Android device at a time."),
  fact("F171", "§4.2", "core", ["M13"], ["uia.pom", "uia.multidevice"], "Multi-device trick: screen definitions live in androidTest, the runner lives in test, and the runner targets methods sequentially across device handles (Device A / MFD runs Method X, focus shifts to Device B / CFD for Method Y, then loops back)."),
  fact("F172", "§4.3", "core", ["M13"], ["uia.pom"], "Every screen, pop-up or window has its own Java class (e.g. HomeScreen, LockScreen, NavigationBar, RegisterHomeScreen)."),
  fact("F173", "§4.3", "core", ["M13"], ["uia.pom"], "Every screen class extends BaseTest."),
  fact("F174", "§4.3", "supporting", ["M13"], ["uia.pom"], "BaseTest provides global setup, teardown and instance variables."),
  fact("F175", "§4.3", "core", ["M13"], ["uia.pom"], "Zone 1 of a screen class holds the Element Locators: declared UI elements unique to that view."),
  fact("F176", "§4.3", "core", ["M13"], ["uia.pom"], "Zone 2 of a screen class holds the Helper/Action Methods, where device-specific behaviours are abstracted."),
  fact("F177", "§4.3", "core", ["M13"], ["uia.pom", "uia.scroll"], "open(String appName) uses vertical scrolling on Flex devices and horizontal scrolling on Mini or Station devices."),
  fact("F178", "§4.3", "core", ["M13"], ["uia.pom", "uia.sync"], "waitForScreen() pauses execution threads until all UI elements finish rendering, so UI Automator never clicks unrendered buttons."),
  fact("F179", "§4.3", "core", ["M13"], ["uia.pom", "uia.sync"], "isScreenPresent() returns a boolean indicating whether that specific screen is currently in focus."),
  fact("F180", "§4.3", "core", ["M13"], ["uia.pom", "uia.sync"], "waitForScreen() and isScreenPresent() are mandatory on every screen class."),
  fact("F181", "§4.4", "supporting", ["M14"], ["uia.config", "uia.taxtest"], "The Tax test begins with a plain-text documentation header explaining the test's intent."),
  fact("F182", "§4.4", "core", ["M14"], ["uia.config", "uia.taxtest"], "Every test starts explicitly from HomeScreen, and a teardown routine forces the hardware back to HomeScreen at completion."),
  fact("F183", "§4.4", "core", ["M14"], ["uia.config", "uia.taxtest"], "Tax test Step 1 (MFD_O1): on the Merchant display, open the Register app, add \"Tax Item 5\" and click \"Review Order\"."),
  fact("F184", "§4.4", "core", ["M14"], ["uia.config", "uia.taxtest", "cards.callus"], "In Tax test Step 1 a backend call goes to Orchestrator, which routes to the Callers/Collos (Callus) microservice to load a simulated swipe card."),
  fact("F185", "§4.4", "core", ["M14"], ["uia.config", "uia.taxtest"], "Tax test Step 2 (CFD_O1): control shifts to the Customer display, which asserts subtotal, calculated tax and grand total."),
  fact("F186", "§4.4", "core", ["M14"], ["uia.config", "uia.taxtest"], "Tax test Step 3 (MFD_O2): control returns to the Merchant display to click \"Pay\" and \"Charge\"."),
  fact("F187", "§4.4", "core", ["M14"], ["uia.config", "uia.taxtest"], "Tax test Step 4: the payment prompt is finalised on the Customer display."),
  fact("F188", "§4.5", "core", ["M14"], ["uia.config"], "When running locally from a laptop, engineers configure config.properties manually."),
  fact("F189", "§4.5", "core", ["M11", "M14"], ["jenkins", "uia.config"], "During CI runs Jenkins injects the config.properties values dynamically."),
  fact("F190", "§4.5", "core", ["M14"], ["uia.config"], "runType is set to tethered for multi-device testing setups."),
  fact("F191", "§4.5", "core", ["M14"], ["uia.config"], "merchantFacingDeviceIp is the local network IP of the MFD terminal."),
  fact("F192", "§4.5", "core", ["M14"], ["uia.config"], "customerFacingDeviceIp is the local network IP of the CFD terminal."),
  fact("F193", "§4.5", "core", ["M14", "M16"], ["uia.config"], "On a Station Duo, merchantFacingDeviceIp and customerFacingDeviceIp are set to the exact same IP address."),
  fact("F194", "§4.5", "supporting", ["M14"], ["uia.config"], "serial is the hardware serial number of the primary terminal."),
  fact("F195", "§4.5", "core", ["M14"], ["uia.config"], "deviceType is the target form factor (Mini, Flex, Station) and governs layout/scroll logic."),
  fact("F196", "§4.5", "core", ["M14"], ["uia.config"], "theme is locked strictly to avocado; legacy theme toggles are deprecated."),
  fact("F197", "§4.5", "core", ["M14"], ["uia.config"], "kernelType is locked strictly to CPA (Core Payments Application), which replaces the legacy SPA (Secure Processor Application)."),
  fact("F198", "§4.5", "core", ["M14"], ["uia.config", "adb.port"], "portNumber is locked to 5444."),
  fact("F199", "§4.5", "core", ["M12", "M14"], ["adb.port", "uia.config"], "Standard ADB defaults to port 5555."),
  fact("F200", "§4.5", "core", ["M14"], ["uia.config", "adb.port"], "Using 5555 caused severe office port collisions in which automated scripts connected to and controlled coworkers' desk devices."),
  fact("F201", "§4.5", "supporting", ["M14"], ["uia.config"], "Additional config.properties keys include device unlock passcodes, backend testing environment targets and the active robot's registration name."),
  fact("F202", "§5", "core", ["M15"], ["pigeon", "pigeon.lstr"], "LSTR has dedicated runners for REST, Android, Windows and iOS."),
  fact("F203", "§5", "supporting", ["M11", "M15"], ["jenkins", "pigeon.lstr"], "The iOS test runner is rarely touched, although iOS Go testing is active."),
  fact("F204", "§5", "core", ["M15"], ["pigeon", "pigeon.abstraction"], "High-level commands (such as \"card swipe\") are abstracted by the runner into platform-specific SDK payment requests or physical robot actions."),
  fact("F205", "§5", "core", ["M15"], ["pigeon", "pigeon.json"], "A Pigeon JSON test specifies the test name, connection type, supported platforms and an array of test actions."),
  fact("F206", "§5", "supporting", ["M15"], ["pigeon", "pigeon.json"], "Versatile Pigeon tests can target 4 to 5 platforms at once."),
  fact("F207", "§5", "supporting", ["M15"], ["pigeon", "pigeon.json"], "Pigeon test actions create requests, pass parameters and store output variables."),
  fact("F208", "§5", "core", ["M15"], ["pigeon", "pigeon.nolint"], "Pigeon has no JSON linter, so missing commas or brackets must be hunted down manually."),
  fact("F209", "§5", "supporting", ["M15"], ["pigeon", "pigeon.nolint"], "Engineers survive the missing linter by copy-pasting working JSON blocks rather than writing syntax from scratch."),
  fact("F210", "§5", "core", ["M15"], ["pigeon", "jenkins.logs"], "A Jenkins log failure at \"select print\" means that action was the last step attempted before the runner timed out waiting for a printer payload."),
  fact("F211", "§5", "core", ["M15"], ["pigeon", "jenkins.logs"], "The usual root cause of a \"select print\" failure is outdated screen coordinates that made the robot arm miss the print button."),
  fact("F212", "§5", "core", ["M16"], ["duo.ocr", "pigeon.gimp"], "For Pigeon screen comparisons, engineers open a screenshot in GIMP, draw a bounding box around the target text and copy the coordinates into the JSON block."),
  fact("F213", "§5", "core", ["M09"], ["orca.screens", "receipt.qr"], "Adding a \"scan for receipt\" QR code feature shifted buttons down by a few millimetres."),
  fact("F214", "§5", "core", ["M09"], ["orca.screens", "receipt.qr", "people.roles"], "The QR shift broke ruler-measured coordinates across the lab for 48 hours until {{jared}} merged a coordinate PR."),
  fact("F215", "§5", "core", ["M09"], ["orca.screens", "receipt.maps"], "The QR feature introduced a conditional 5th menu option on the receipt screen."),
  fact("F216", "§5", "core", ["M09"], ["orca.screens", "receipt.maps"], "Orca must maintain separate coordinate maps for 4-option and 5-option receipt screens across every device profile."),
  fact("F217", "§6.1", "core", ["M09"], ["orca.screens", "bots.types"], "ADB bots are purely programmatic: they cannot physically touch the screen or enter PINs."),
  fact("F218", "§6.1", "core", ["M09"], ["orca.screens", "bots.types"], "ADB bots are restricted to merchant configurations that bypass PIN security."),
  fact("F219", "§6.1", "core", ["M09"], ["orca.screens", "bots.types"], "Physical/interactive bots are equipped with mechanical touch probes."),
  fact("F220", "§6.1", "core", ["M09"], ["orca.screens", "bots.types", "bots.pin"], "Physical bots are required for Canadian payment workflows, which mandate physical PIN entry."),
  fact("F221", "§6.1", "core", ["M09", "M16"], ["orca.screens", "bots.types"], "Physical bots are required for ADB-blind displays."),
  fact("F222", "§6.1", "supporting", ["M17"], ["infra.ai", "bots.pin"], "Gen 2 Software PIN Bypass: the team is partnering with the Core OS Team on a software framework that bypasses physical robotics for Secure Touch PIN entry."),
  fact("F223", "§6.1", "supporting", ["M17"], ["infra.ai", "bots.pin"], "Under Gen 2, physical robotics are reserved exclusively for non-negotiable hardware interactions such as card dipping."),
  fact("F224", "§6.2", "core", ["M10", "M18"], ["cards", "cards.philosophy"], "Your team standardises on a single reliable Visa profile to verify transaction pipelines."),
  fact("F225", "§6.2", "core", ["M10", "M18"], ["cards", "cards.philosophy"], "Your team adds Canadian Interac for regional flows."),
  fact("F226", "§6.2", "supporting", ["M18"], ["teams.history", "cards.philosophy"], "The PayCore Team runs exhaustive back-to-back card-matrix validations (Visa, Discover, AmEx)."),
  fact("F227", "§6.3", "core", ["M03"], ["power.rails", "power.fuses"], "Power chain: 120V AC wall power enters a Mean Well transformer, drops to a central 24V DC rail, and step-down regulators split it into 12V DC (NUCs) and 5V DC 10A (Pis), protected by inline fuses."),
  fact("F228", "§6.3", "core", ["M03"], ["power.rails", "power.18v"], "LabSim devices draw an irregular 18V."),
  fact("F229", "§6.3", "core", ["M03"], ["power.rails", "power.18v"], "LabSim terminals and the expensive Collis probes bypass the custom DC rails entirely and plug into commercial AC power strips to prevent frying components."),
  fact("F230", "§6.4", "core", ["M01"], ["lab.orientation", "hw.lockout"], "The global LabSim control dashboard locks out external users while tests are active."),
  fact("F231", "§6.4", "core", ["M04"], ["robots.mechanics", "hw.motion"], "Manually moving a robot arm breaks its magnetic lock and turns the top status banner yellow."),
  fact("F232", "§6.4", "core", ["M04"], ["robots.mechanics", "hw.motion"], "Park All drives the stepper motors back to the physical limit switches at (0,0), clearing errors and turning the status banner green."),
  fact("F233", "IMG-T", "supporting", ["M01"], ["lab.orientation", "hw.tablet"], "The status tablet header shows the robot's human-readable name (e.g. WALL-E), the LabSim logo, \"Status: OK\" and \"Brainbox v6\"."),
  fact("F234", "IMG-T", "supporting", ["M04"], ["robots.mechanics", "hw.tablet"], "The status tablet has three tabs: Robot, Robot Control and Motion Control."),
  fact("F235", "IMG-T", "core", ["M04"], ["robots.mechanics", "hw.tablet"], "The Motion Control tab has button groups Steppers (Enable / Disable), Park (Park All / XY / X / Y), Dip (In / Out), Tap (In / Out), Phone (Forward / Back / Push Power Button) and Solenoid (Down / Up / Lower / Raise)."),
  fact("F236", "IMG-T", "supporting", ["M01"], ["lab.orientation", "hw.tablet"], "The touch-robot POWER panel has two green LEDs and two toggle switches labelled MAIN and MOTOR."),
  fact("F237", "IMG-R", "supporting", ["M02"], ["devices", "hw.devices"], "Tethered test-bed screens are labelled with rig, role and environment (e.g. MEGATRON MFD DEV1, OPTIMUS CFD STG)."),
  fact("F238", "IMG-R", "supporting", ["M02"], ["devices", "hw.devices"], "Black USB \"SmartStripe Probe\" dongles with green LEDs sit between the tethered screens."),
  fact("F239", "IMG-R", "supporting", ["M02"], ["devices", "hw.devices"], "Below the tethered screens, black 3D-printed docks hold white LabSim connectivity hubs (Ethernet, USB, power) labelled per device (e.g. MEGATRON MFD)."),
  fact("F240", "IMG-G", "supporting", ["M04"], ["robots.mechanics", "hw.rigbom"], "Gantry anatomy: 2020 aluminium extrusion rails, a NEMA-17 stepper with a GT2 pulley, V-slot wheels and a carriage carrying a blue push-pull solenoid pointed at the screen."),
  fact("F241", "IMG-G", "supporting", ["M04"], ["robots.mechanics", "hw.rigbom"], "A black rotating dip arm (sector gear marked 63) carries a flat white ribbon card (the Collis probe card insert) into the device's chip slot."),
  fact("F242", "IMG-G", "trivia", ["M04"], ["robots.mechanics", "hw.rigbom"], "The Flex sits in an angled black 3D-printed cradle, with the grey UL Transaction Security (Collis) probe box on the shelf beside it."),
  fact("F243", "IMG-V", "supporting", ["M04"], ["robots.mechanics", "hw.rigbom"], "Solenoid tap cycle: the gantry moves the head over the target button, the plunger drops to tap, lifts, moves and taps again."),
  fact("F244", "IMG-T", "trivia", ["M01"], ["lab.orientation", "hw.rigbom"], "Touch-robot enclosures sit in racks whose rails are marked with numbered rack units (e.g. 29 to 40)."),
  fact("F245", "IMG-T", "trivia", ["M01"], ["lab.orientation", "hw.tablet"], "A side panel lettered SETI beside WALL-E's tablet carries USB ports for the Minix box / Raspberry Pi."),
]);

/** S01–S20 — sim-only illustrative details. Never tested as real-world truth. */
export const ILLUSTRATIVE_FACTS: Fact[] = resolvePeople([
  simFact("S01", ["orca.robot"], "Orca's pool holds 42 rigs named after famous robots (the reference says \"40+\"); 12 of them are physically modelled in the 3D lab. Gort is a repository, not a rig."),
  simFact("S02", ["arch.infra", "tools.terminal"], "Host map: GPU blade 10.42.1.5; Orca orca.lab.local → 10.42.1.10:8080 (MySQL schema orca, port 3306); Jenkins 10.42.1.11:8080; Ollama 10.42.1.12:11434 (vision model llava); Robot Pis 10.42.10.<n> (REST :8000, MJPEG :8081/stream.mjpg); Callus boxes 10.42.20.<n>:9000; LabSim devices 10.42.30.<n> (ADB 5444); your workstation 10.42.50.17; coworker desk devices 10.42.60.<n> (ADB 5555)."),
  simFact("S03", ["orca.devicetype"], "Device Type enum strings STATION_2018, STATION_2, STATION_DUO, STATION_DUO_2, STATION_DUO_3, MINI_2, MINI_3, MINI_4, FLEX_1, FLEX_2, FLEX_3, FLEX_4, FLEX_POCKET, COMPACT; the shared Flex 3/4/Pocket profile is called FLEX_GEN3; config.properties deviceType uses the family (Mini, Flex, Station)."),
  simFact("S04", ["people.roles", "uia.history"], "\"The presenter\" who created uia-remote is called {{morgan}} in the game."),
  simFact("S05", ["orca.robot"], "The rig roster, device assignments, IP addresses and starting statuses of the 12 modelled rigs are invented for the sim."),
  simFact("S06", ["orca.xytouch", "orca.urls"], "REST paths: Pi health GET http://10.42.10.<n>:8000/health → 200 {\"status\":\"ok\"}; Orca POST /api/xy_touch with body {\"robot\",\"screen\",\"button\"}; Orca POST /api/card/{swipe|dip|tap} with body {\"robot\",\"profile\"}; Pi URL mappings /adb, /dip, /tap, /swipe."),
  simFact("S07", ["jenkins.envvars"], "Jenkins job names, the parameter names ROBOT_NAME, DEVICE_TYPE, MERCHANT, CARD_PROFILE and the console env-block keys RUN_TYPE, PORT_NUMBER, THEME, KERNEL_TYPE, APP_ID, APP_SECRET, API_KEY."),
  simFact("S08", ["cards.diptap", "cards.swipe"], "Card profile names, the Visa test Track Data string, the Gort paths cards/emv/*.json and cards/nfc/*.json, the scheduled task name GortCardSync and the Windows path C:\\gort\\cards\\…."),
  simFact("S09", ["orca.merchant"], "Merchant names (AUTO-US-NOPIN-01/02, GO-SDK-US-01, PAYCORE-STANDALONE-01, WESTERS-CA-01) and their App ID / API Key values."),
  simFact("S10", ["orca.screens", "receipt.maps"], "Screen names (TENDER_CASH_DISCOUNT, PIN_ENTRY, RECEIPT_OPTIONS_4, RECEIPT_OPTIONS_5) and every millimetre value; the receipt QR shift is modelled as 3.0 mm."),
  simFact("S11", ["uia.taxtest"], "Tax Item 5 costs $10.00 at 8.25 % tax → tax $0.83, total $10.83."),
  simFact("S12", ["uia.config"], "The config.properties key names unlockPasscode, backendEnv and robotName, and serial numbers of the form SIM-…."),
  simFact("S13", ["hw.motion", "hw.lockout"], "Tablet overlay \"TEST IN PROGRESS — CONTROLS LOCKED\"; yellow banner text \"Status: LOCK RELEASED — PARK REQUIRED\"; only Park All clears the error (Park XY / X / Y home just those axes and leave the banner yellow)."),
  simFact("S14", ["hw.pi", "tools.terminal"], "The Pi service name robot-controller, the Wine binary path, the df figures and the Pi prompt pi@wall-e:~ $."),
  simFact("S15", ["vision.ollama"], "The Ollama prompt/response and the receipt numbers ($42.00, 18 %, $7.56 vs $7.65)."),
  simFact("S16", ["arch.repos"], "GitHub org labsim-lab; Gort top-level folders cards/, config/, go-sdk/, suites/; Pigeon folders runners/{rest,android,windows,ios}, tests/, tests/_templates/."),
  simFact("S17", ["hw.tablet"], "The function of the tablet's Phone group (drives a phone carriage Forward/Back and a power-button pusher for mobile-runner tests). The reference photo shows the buttons but not their purpose."),
  simFact("S18", ["lab.orientation"], "The wording of the Lab Safety Card handed out in Module 1."),
  simFact("S19", ["adb.port"], "How port 5555 reached a coworker's device in the sim: the runner's connect to the lab device on 5555 is refused and it falls back to the first device the workstation's ADB server already knows. The reference only says 5555 caused collisions in which scripts connected to and controlled coworkers' desk devices."),
  simFact("S20", ["lab.orientation"], "The seeded faults used by lessons: Rack B fuse, EVE Pi unplug, JONNY-5 typo, BUMBLEBEE Offset Y 1.5, OPTIMUS empty MFD/CFD, missing API Key, Pigeon missing comma, MINI_3 receipt coordinates, DEVICE_TYPE=flex_3."),
]);
