/**
 * Flashcards for the Field Manual's Leitner spaced repetition (Cur §4, FC001–FC159).
 * Generated from docs/design/10-curriculum.md (front/back verbatim). `moduleId` = the card's deck module
 * (deck.M##, the earliest module that teaches any of its facts); `tags` = that module's default tag + the
 * fine tags of the card's facts. `typedAnswer` enables the optional typed-answer mode (Cur §4.0) for cards
 * whose back reduces to a single token; graded with the fill-in rules.
 */
import type { Flashcard } from './schema';
import { resolvePeople } from './people';

function card(
  id: string,
  moduleId: string,
  factIds: string[],
  tags: string[],
  front: string,
  back: string,
  extra?: Pick<Flashcard, 'typedAnswer' | 'typedCaseSensitive'>,
): Flashcard {
  return { id, deck: `deck.${moduleId}`, moduleId, factIds, tags, front, back, ...extra };
}

export const FLASHCARDS: Flashcard[] = resolvePeople([
  card("FC001", "M01", ["F089"], ["lab.orientation", "hw.tablet"], "What is mounted on the front of every touch robot?", "A front-mounted status tablet (the robot's dashboard)."),
  card("FC002", "M01", ["F233"], ["lab.orientation", "hw.tablet"], "What does WALL-E's tablet header show?", "Robot name (WALL-E), LabSim logo, \"Status: OK\", \"Brainbox v6\"."),
  card("FC003", "M04", ["F234"], ["robots.mechanics", "hw.tablet"], "Name the status tablet's three tabs.", "Robot · Robot Control · Motion Control."),
  card("FC004", "M04", ["F235"], ["robots.mechanics", "hw.tablet"], "Motion Control button groups?", "Steppers (Enable/Disable) · Park (Park All/XY/X/Y) · Dip (In/Out) · Tap (In/Out) · Phone (Forward/Back/Push Power Button) · Solenoid (Down/Up/Lower/Raise)."),
  card("FC005", "M01", ["F236"], ["lab.orientation", "hw.tablet"], "What's on a touch robot's POWER panel?", "Two green LEDs and two toggles: MAIN and MOTOR."),
  card("FC006", "M01", ["F115"], ["lab.orientation", "orca.robot"], "How many rigs does Orca's Robot entity track?", "40+ rigs (and their status flags)."),
  card("FC007", "M01", ["F230"], ["lab.orientation", "hw.lockout"], "What happens to the control dashboard while a test is active?", "It locks out external users."),
  card("FC008", "M01", ["F072", "F073"], ["lab.orientation", "hw.print3d"], "Who makes the black shelf fixtures, and how are they designed?", "Prusa and Bambu Lab 3D printers; drafted in CAD from simple geometric shapes."),
  card("FC009", "M02", ["F054"], ["devices", "hw.devices"], "MFD / CFD?", "Merchant Facing Device / Customer Facing Device."),
  card("FC010", "M02", ["F055"], ["devices", "hw.devices"], "Station series targets?", "Station 2018, Station 2, Station Duo (Duo 1, Duo 2, upcoming Duo 3)."),
  card("FC011", "M02", ["F056"], ["devices", "hw.devices"], "Mini series targets?", "Mini 2, Mini 3, upcoming Mini 4."),
  card("FC012", "M02", ["F058"], ["devices", "hw.devices"], "Flex series targets?", "Flex 1, Flex 2, Flex 3, Flex 4, Flex Pocket."),
  card("FC013", "M02", ["F059", "F060"], ["devices", "hw.devices"], "Which devices share one testing profile, and what's different?", "Flex 3, Flex 4, Flex Pocket. The Pocket omits the printer block."),
  card("FC014", "M02", ["F057"], ["devices", "hw.devices"], "Hot-swap for a printerless Station Duo 2?", "Mini 3.", { typedAnswer: ["Mini 3"] }),
  card("FC015", "M02", ["F061"], ["devices", "hw.devices"], "Which terminal is for Canada / Westers test beds?", "LabSim Compact.", { typedAnswer: ["LabSim Compact", "Compact"] }),
  card("FC016", "M02", ["F062"], ["devices", "hw.devices"], "Which devices are upcoming?", "Station Duo 3 and Mini 4."),
  card("FC017", "M02", ["F237"], ["devices", "hw.devices"], "What do the tethered test-bed labels encode?", "Rig · role · environment, e.g. MEGATRON MFD DEV1, OPTIMUS CFD STG."),
  card("FC018", "M02", ["F238", "F239"], ["devices", "hw.devices"], "What sits between and below the tethered screens?", "Between: USB \"SmartStripe Probe\" dongles (green LEDs). Below: 3D-printed docks with LabSim connectivity hubs (Ethernet, USB, power)."),
  card("FC019", "M03", ["F074"], ["power.rails"], "What does the Mean Well do?", "Converts 120V AC wall power to a central 24V DC rail."),
  card("FC020", "M03", ["F085"], ["power.rails"], "What powers the Intel NUCs?", "12V DC from a step-down regulator.", { typedAnswer: ["12V DC", "12V", "12 V DC"] }),
  card("FC021", "M03", ["F086"], ["power.rails"], "What powers the Raspberry Pis?", "5V DC, 10A from a step-down regulator.", { typedAnswer: ["5V DC, 10A", "5V 10A", "5 V DC 10 A"] }),
  card("FC022", "M03", ["F087"], ["power.rails", "power.fuses"], "What protects the 12V and 5V lines?", "Inline fuses.", { typedAnswer: ["inline fuses", "inline fuse"] }),
  card("FC023", "M03", ["F227"], ["power.rails", "power.fuses"], "Full power chain?", "120V AC → Mean Well → 24V DC rail → step-down regulators → 12V (NUCs) and 5V 10A (Pis), with inline fuses."),
  card("FC024", "M03", ["F228"], ["power.rails", "power.18v"], "What do LabSim devices draw?", "An irregular 18V.", { typedAnswer: ["18V", "18 V", "irregular 18V"] }),
  card("FC025", "M03", ["F229"], ["power.rails", "power.18v"], "Where do LabSim terminals and Collis probes get power?", "Commercial AC power strips. Never the custom DC rails (prevents frying)."),
  card("FC026", "M04", ["F240"], ["robots.mechanics", "hw.rigbom"], "Gantry parts?", "2020 aluminium extrusion, NEMA-17 stepper + GT2 pulley, V-slot wheels, carriage with a blue push-pull solenoid."),
  card("FC027", "M04", ["F079"], ["robots.mechanics", "hw.rigbom"], "Stepper precision?", "Sub-millimetre.", { typedAnswer: ["sub-millimetre", "sub-millimeter", "sub-mm"] }),
  card("FC028", "M04", ["F080"], ["robots.mechanics", "hw.rigbom"], "What taps the screen?", "A remote-firing solenoid; its plunger drops."),
  card("FC029", "M04", ["F082"], ["robots.mechanics", "hw.rigbom", "hw.motion"], "What sets the (0,0) origin?", "Physical limit switches.", { typedAnswer: ["limit switches", "physical limit switches"] }),
  card("FC030", "M04", ["F083", "F084"], ["robots.mechanics", "hw.rigbom"], "Motor controller boards?", "Custom 25-pin PCBs, printed in Hong Kong."),
  card("FC031", "M04", ["F241"], ["robots.mechanics", "hw.rigbom"], "How does the card get into the chip slot?", "A rotating dip arm (sector gear \"63\") carries a flat white ribbon card (Collis insert)."),
  card("FC032", "M04", ["F231"], ["robots.mechanics", "hw.motion"], "What happens if you push a robot arm by hand?", "The magnetic lock breaks and the top status banner turns yellow."),
  card("FC033", "M04", ["F232"], ["robots.mechanics", "hw.motion"], "What does Park All do?", "Drives the steppers to the limit switches at (0,0), clears errors, banner turns green."),
  card("FC034", "M04", ["F090", "F091"], ["robots.mechanics", "hw.rigbom"], "Rails and wiring per touch robot?", "10 ft cut aluminium rails; ~130 ft of wiring."),
  card("FC035", "M04", ["F092", "F093"], ["robots.mechanics", "hw.rigbom"], "Solder points and hardware per touch robot?", "~300 manual solder points; 200+ nuts and bolts, 2.5 mm and 5 mm."),
  card("FC036", "M04", ["F088"], ["robots.mechanics", "hw.rigbom", "vision.camera"], "Source of camera streams and OCR screenshots?", "The rig webcams."),
  card("FC037", "M05", ["F064"], ["pi.controller", "hw.pi"], "What is the Robot Controller?", "A Raspberry Pi, one per shelf (the \"Robot Pi\")."),
  card("FC038", "M05", ["F063"], ["pi.controller", "hw.pi"], "Cost of a lab Pi?", "About $50.", { typedAnswer: ["$50", "50"] }),
  card("FC039", "M05", ["F065"], ["pi.controller", "hw.pi"], "Robot Pi duties?", "ADB routing, camera streams, stepper motors, solenoids, Wine card-programming emulation."),
  card("FC040", "M05", ["F019", "F020"], ["pi.controller", "hw.pi"], "Pi OS and why?", "Linux, to isolate hardware control loops from corporate Windows machines."),
  card("FC041", "M05", ["F021"], ["pi.controller", "cards.wine"], "What does Wine do on the Pi?", "Emulates the Windows-only card-programming software layers."),
  card("FC042", "M05", ["F066"], ["pi.controller", "hw.nuc"], "What are the NUCs and Minix boxes?", "Local Windows execution machines in the lab."),
  card("FC043", "M05", ["F067", "F068"], ["pi.controller", "hw.nuc"], "Why did hardware control leave the NUCs?", "corporate security-monitoring packages exhausted their disks, so control moved to Raspberry Pis."),
  card("FC044", "M06", ["F036"], ["orca.status", "arch.roles"], "Orca = ?", "Orchestrator.", { typedAnswer: ["Orchestrator"] }),
  card("FC045", "M06", ["F098"], ["orca.status", "arch.roles"], "Controller vs Executor?", "Orca = Controller. Jenkins = Executor."),
  card("FC046", "M06", ["F037", "F002"], ["orca.status", "arch.stack"], "What is Orca built as?", "An on-premise Spring Boot monolith (Java)."),
  card("FC047", "M06", ["F003", "F004"], ["orca.status", "arch.stack"], "What did JHipster do for Orca?", "Scaffolded it via an interactive questionnaire, generating the frontend UI, Spring Boot REST endpoints and MySQL schemas."),
  card("FC048", "M06", ["F013", "F014"], ["orca.status", "arch.stack"], "Orca's database, and what's in it?", "MySQL: hardware states, merchant profiles, screen-coordinate tables (robots, devices, screens, card profiles, merchants)."),
  card("FC049", "M06", ["F023"], ["orca.status", "arch.stack", "arch.infra"], "Where does Orca run today?", "A local on-premise lab VM (on the GPU blade)."),
  card("FC050", "M06", ["F099"], ["orca.status", "orca.healthcheck"], "Orca health-check cadence?", "Every 5 minutes, a synchronized background thread pings every Pi's Robot Controller."),
  card("FC051", "M06", ["F100"], ["orca.status"], "The 5 robot statuses?", "Available, Unavailable, Offline, Connection Failed, Reserved."),
  card("FC052", "M06", ["F101"], ["orca.status"], "Available?", "Online, healthy, open to general pipeline checkouts."),
  card("FC053", "M06", ["F102"], ["orca.status", "orca.status.unavailable"], "Unavailable: how do you use it?", "Only by passing the robot's exact unique name in the job parameters."),
  card("FC054", "M06", ["F103"], ["orca.status", "orca.status.unavailable"], "Why Unavailable?", "Isolates specialised rigs (e.g. PayCore standalone) so general tests don't overwrite their merchant profiles."),
  card("FC055", "M06", ["F104"], ["orca.status", "orca.status.unavailable"], "After a named job on an Unavailable robot finishes?", "Orca automatically resets it to Unavailable."),
  card("FC056", "M06", ["F105", "F106"], ["orca.status", "orca.status.offline", "orca.healthcheck"], "Offline?", "Manual placeholder while building a rig or assembling data profiles; health checks are skipped."),
  card("FC057", "M06", ["F107", "F108"], ["orca.status", "orca.status.connfailed", "orca.healthcheck"], "Connection Failed: trigger and effect?", "5-minute REST ping drops or returns non-200; robot is blocked from checkouts."),
  card("FC058", "M06", ["F109"], ["orca.status", "orca.status.connfailed", "orca.notes"], "Where are Connection Failed details?", "Orca's Notes section: exact endpoint attempted and error text."),
  card("FC059", "M06", ["F110", "F111"], ["orca.status", "orca.status.connfailed", "people.roles"], "Typical Connection Failed causes and escalation?", "Crashed Pi board or Minix box running Callus offline. Escalate to {{jared}}."),
  card("FC060", "M06", ["F112", "F113"], ["orca.status", "orca.status.reserved"], "Reserved?", "Set manually when testing locally from your workstation; blocks Jenkins pipelines and health-check overrides."),
  card("FC061", "M06", ["F094", "F095"], ["orca.status", "arch.flow", "jenkins.checkout"], "What does Jenkins do in the flow?", "Triggers the pipeline, injects env vars into the test runner, checks out a robot from Orca."),
  card("FC062", "M06", ["F096"], ["orca.status", "arch.flow", "orca.xytouch"], "How does the runner request taps and cards?", "REST calls to Orca: xy_touch and card swipe/dip/tap."),
  card("FC063", "M06", ["F097"], ["orca.status", "arch.flow", "cards.callus"], "Card emulation chain?", "Windows/Minix box running Callus → ribbon cable → Collis probe → LabSim card reader."),
  card("FC064", "M07", ["F114"], ["orca.entities", "arch.stack"], "How many core Orca schemas?", "7 (JHipster entities).", { typedAnswer: ["7", "seven"] }),
  card("FC065", "M06", ["F116"], ["orca.status", "orca.robot", "people.roles"], "Who built the robot-list filter UI?", "{{tate}}.", { typedAnswer: ["{{tate}}"] }),
  card("FC066", "M07", ["F117", "F118"], ["orca.entities", "orca.names", "hw.tablet"], "Name vs Human Readable Name?", "Name = system identifier. Human Readable Name = display string pushed to the status tablet."),
  card("FC067", "M07", ["F119", "F120"], ["orca.entities", "orca.device"], "Why is Device separate from Robot?", "Hardware upgrades (e.g. Flex 1 → Flex 2) leave legacy configs intact for quick rollback."),
  card("FC068", "M07", ["F121"], ["orca.entities", "orca.devicetype"], "Device Type stores?", "Device dimensions, layout metrics, internal string definitions (an enum)."),
  card("FC069", "M07", ["F122"], ["orca.entities", "orca.devicetype", "jenkins.envvars"], "Why are Jenkins env vars ALL CAPS?", "They must match the Device Type enum strings."),
  card("FC070", "M07", ["F123"], ["orca.entities", "orca.urls"], "Robot ADB Service URL routes to?", "The Pi controller."),
  card("FC071", "M07", ["F124"], ["orca.entities", "orca.urls", "vision.camera"], "Camera Stream URL scope?", "Dedicated per Pi, or shared across 4 rigs."),
  card("FC072", "M07", ["F125"], ["orca.entities", "orca.urls"], "Hardware-specific URLs per robot?", "Dip, Tap, Swipe."),
  card("FC073", "M07", ["F126", "F128"], ["orca.entities", "orca.tethered"], "When is a rig tethered in Orca?", "When the MFD field is populated (USB Tethered Device Configuration: MFD/CFD relations)."),
  card("FC074", "M07", ["F127"], ["orca.entities", "orca.tethered"], "Examples of tethered/nested setups?", "Station 2 tethered to a Mini 2; nested Mini 3 rigs."),
  card("FC075", "M07", ["F129", "F130"], ["orca.entities", "orca.offsets", "people.roles"], "Offsets?", "Legacy mm adjustments for imprecise limit switches; mostly deprecated since {{jared}} calibrated to true (0,0)."),
  card("FC076", "M08", ["F131"], ["orca.capabilities"], "What does Robot Capabilities do?", "Controls how Orca matches pipeline requests to physical hardware."),
  card("FC077", "M08", ["F132", "F133"], ["orca.capabilities", "people.roles"], "Dynamic JSON lookups?", "SDK frameworks (overseen by {{david}}); capabilities are JSON metadata in each test definition, parsed at runtime."),
  card("FC078", "M08", ["F134"], ["orca.capabilities"], "Non-dynamic lookups?", "Traditional UI Automator suites; capabilities hardcoded in the pipeline script."),
  card("FC079", "M08", ["F135"], ["orca.capabilities"], "Which scripts use both lookup styles?", "Contact Canada scripts on Westers test beds."),
  card("FC080", "M08", ["F137"], ["orca.capabilities", "orca.merchant"], "Can't see all Merchant Config fields?", "UI table display limits: click Edit on the row."),
  card("FC081", "M08", ["F138", "F139"], ["orca.capabilities", "orca.merchant", "people.roles", "go.sdk"], "{{tate}}'s Merchant Config additions and why?", "App ID, App Secret, API Key, exported as runtime env vars for the Go SDK."),
  card("FC082", "M08", ["F046", "F047"], ["orca.capabilities", "laz.oobe"], "Laz Automation?", "Zero-touch OOBE provisioning: de-provision, wipe caches, step the setup wizard, swap merchants mid-suite."),
  card("FC083", "M08", ["F051"], ["orca.capabilities", "ubi.routing"], "Ubi Platform?", "Internal routing platform used when jobs dynamically switch merchant configs."),
  card("FC084", "M08", ["F008", "F009"], ["orca.capabilities", "go.sdk"], "Go SDK support and testing?", "Custom extensions in Orca; tested through Pigeon and mobile runners."),
  card("FC085", "M09", ["F141"], ["orca.screens"], "Screens entity?", "Discrete UI layouts within a transaction flow per device architecture (e.g. cash-discount tender prompt)."),
  card("FC086", "M09", ["F142"], ["orca.screens"], "Screen Locations entity?", "Exact button placements as relative X/Y in millimetres."),
  card("FC087", "M09", ["F143", "F144"], ["orca.screens", "orca.xytouch"], "How does xy_touch work?", "Script sends screen name + button string; Orca looks up mm coordinates; Pi fires an ADB touch or a physical probe tap."),
  card("FC088", "M09", ["F217", "F218"], ["orca.screens", "bots.types"], "ADB bots: limits?", "Purely programmatic: no physical touch, no PINs. Only PIN-bypass merchant configs."),
  card("FC089", "M09", ["F219", "F220", "F221"], ["orca.screens", "bots.types", "bots.pin"], "When do you need a physical bot?", "Canadian payment flows (physical PIN entry) and ADB-blind displays. They have mechanical touch probes."),
  card("FC090", "M09", ["F213", "F214"], ["orca.screens", "receipt.qr", "people.roles"], "The receipt QR incident?", "\"Scan for receipt\" shifted buttons down a few mm, breaking ruler-measured coordinates for 48 hours until {{jared}} merged a coordinate PR."),
  card("FC091", "M09", ["F215", "F216"], ["orca.screens", "receipt.maps"], "Lasting effect of the QR feature?", "A conditional 5th option, so Orca keeps separate 4-option and 5-option receipt maps per device profile."),
  card("FC092", "M10", ["F145", "F146"], ["cards", "cards.swipe"], "Swipe profiles?", "Raw Track Data text in MySQL, extracted with a hardware card-reader utility."),
  card("FC093", "M10", ["F147"], ["cards", "cards.diptap"], "Dip and Tap profiles?", "File paths to card definitions in Gort."),
  card("FC094", "M10", ["F148", "F149"], ["cards", "cards.callus"], "How do Gort card files get used?", "A scheduled job clones them onto Windows boxes; during a run Callus maps the path and loads the virtual card."),
  card("FC095", "M10", ["F048", "F049"], ["cards", "cards.callus"], "Callus aliases and host?", "\"Callers\" / \"Collos\". Runs on local Windows/Minix boxes."),
  card("FC096", "M10", ["F050"], ["cards", "cards.callus"], "What does Callus do?", "Reads card-profile paths from Gort and drives the Collis probes."),
  card("FC097", "M10", ["F069", "F070"], ["cards", "hw.collis"], "Collis probes?", "High-cost proprietary card emulators (UL Transaction Security) on rear ribbon cables."),
  card("FC098", "M10", ["F071"], ["cards", "hw.collis"], "What can a Collis probe simulate?", "Mag-stripe swipe, EMV chip dip, contactless NFC tap."),
  card("FC099", "M10", ["F034", "F035"], ["cards", "arch.repos", "cards.diptap"], "Gort?", "Core monorepo: testing ecosystem, configuration modules, Dip/Tap virtual card definitions."),
  card("FC100", "M10", ["F224", "F225"], ["cards", "cards.philosophy"], "Your team's card philosophy?", "One reliable Visa profile, plus Canadian Interac for regional flows."),
  card("FC101", "M18", ["F226"], ["teams.history", "cards.philosophy"], "PayCore's card philosophy?", "Exhaustive back-to-back matrices: Visa, Discover, AmEx."),
  card("FC102", "M11", ["F015", "F016"], ["jenkins", "jenkins.envvars", "arch.roles"], "Jenkins?", "The Executor: triggers pipelines and injects runtime env vars."),
  card("FC103", "M11", ["F017"], ["jenkins", "jenkins.folders"], "How are legacy Jenkins jobs organised?", "By platform: Java jobs separate from iOS jobs."),
  card("FC104", "M11", ["F189"], ["jenkins", "uia.config"], "Who sets config values in CI?", "Jenkins injects them dynamically."),
  card("FC105", "M12", ["F024", "F025"], ["adb.port", "adb.usage"], "What is ADB used for?", "Inspecting XML UI hierarchies, locating elements, dispatching programmatic touch events."),
  card("FC106", "M12", ["F026", "F198"], ["adb.port", "uia.config"], "Lab ADB port?", "5444 (portNumber=5444).", { typedAnswer: ["5444"] }),
  card("FC107", "M12", ["F199", "F200"], ["adb.port", "uia.config"], "Why not 5555?", "It's the ADB default and caused collisions: scripts controlled coworkers' desk devices."),
  card("FC108", "M13", ["F005", "F006", "F007"], ["uia.pom", "uia.v23"], "uia-remote's automation engine?", "Android UI Automator 2.3, for native dual-screen element tracking."),
  card("FC109", "M06", ["F001"], ["orca.status", "arch.stack"], "Primary language for Orca and uia-remote?", "Java (Oracle Java)."),
  card("FC110", "M13", ["F027", "F028"], ["uia.pom", "tools.intellij"], "IntelliJ IDEA's role?", "Primary IDE: import repos, configure local properties, run test suites."),
  card("FC111", "M13", ["F018"], ["uia.pom", "arch.repos", "tools.github"], "Where are the repos hosted?", "GitHub: Gort, uia-remote, pigeon (branches and PRs)."),
  card("FC112", "M13", ["F159"], ["uia.pom", "uia.history", "people.roles"], "Why was uia-remote created?", "No framework could automate native tethered setups (Station-to-Mini, Mini-to-Mini, Station Duo)."),
  card("FC113", "M13", ["F163", "F010"], ["uia.pom", "uia.layout"], "uia-remote layout?", "Standard Android/Maven structure under app/src/."),
  card("FC114", "M13", ["F164"], ["uia.pom", "uia.layout"], "app/src/main?", "Production/application registration code. QA never modifies it."),
  card("FC115", "M13", ["F165"], ["uia.pom", "uia.layout"], "app/src/test?", "Local unit tests + the multi-device execution runner."),
  card("FC116", "M13", ["F166"], ["uia.pom", "uia.layout"], "app/src/androidTest?", "Instrumented tests on Android hardware: databases, pageobjects, testactions."),
  card("FC117", "M13", ["F167", "F168", "F169"], ["uia.pom", "uia.packages"], "The three androidTest packages?", "databases (DB logic) · pageobjects (POM screen classes) · testactions (tests + assertions)."),
  card("FC118", "M13", ["F170", "F171"], ["uia.pom", "uia.multidevice"], "How does uia-remote drive two devices?", "UIA talks to one device at a time, so the runner (test) hops between device handles: MFD runs X, CFD runs Y, loop."),
  card("FC119", "M13", ["F172", "F173"], ["uia.pom"], "Screen class rule?", "Every screen, pop-up or window gets its own Java class extending BaseTest."),
  card("FC120", "M13", ["F174"], ["uia.pom"], "What does BaseTest provide?", "Global setup, teardown, instance variables."),
  card("FC121", "M13", ["F175", "F176"], ["uia.pom"], "Zone 1 vs Zone 2?", "Zone 1: element locators. Zone 2: helper/action methods (device-specific behaviour)."),
  card("FC122", "M13", ["F177"], ["uia.pom", "uia.scroll"], "open(String appName) scrolling?", "Flex: vertical. Mini/Station: horizontal."),
  card("FC123", "M13", ["F178", "F179", "F180"], ["uia.pom", "uia.sync"], "Mandatory screen methods?", "waitForScreen() (wait for render) and isScreenPresent() (boolean: in focus?)."),
  card("FC124", "M14", ["F182"], ["uia.config", "uia.taxtest"], "Test safe state?", "Start from HomeScreen; teardown forces back to HomeScreen."),
  card("FC125", "M14", ["F183", "F184"], ["uia.config", "uia.taxtest", "cards.callus"], "Tax test Step 1 (MFD_O1)?", "Open Register, add \"Tax Item 5\", click \"Review Order\"; Orca routes to Callus to load a simulated swipe card."),
  card("FC126", "M14", ["F185"], ["uia.config", "uia.taxtest"], "Tax test Step 2 (CFD_O1)?", "On the Customer display, assert subtotal, calculated tax, grand total."),
  card("FC127", "M14", ["F186", "F187"], ["uia.config", "uia.taxtest"], "Tax test Steps 3 and 4?", "MFD_O2: click \"Pay\" and \"Charge\". Step 4: payment prompt finalised on the Customer display."),
  card("FC128", "M14", ["F188"], ["uia.config"], "Local runs: who sets config.properties?", "You, manually."),
  card("FC129", "M14", ["F190"], ["uia.config"], "runType for multi-device?", "tethered", { typedAnswer: ["tethered"], typedCaseSensitive: true }),
  card("FC130", "M14", ["F191", "F192", "F193"], ["uia.config"], "MFD/CFD IP keys, and the Duo rule?", "merchantFacingDeviceIp / customerFacingDeviceIp. On a Station Duo both are the same IP."),
  card("FC131", "M14", ["F194", "F195"], ["uia.config"], "serial and deviceType?", "serial = primary terminal's hardware serial. deviceType = Mini / Flex / Station (layout/scroll logic)."),
  card("FC132", "M14", ["F196"], ["uia.config"], "theme?", "Locked to avocado (legacy toggles deprecated).", { typedAnswer: ["avocado"], typedCaseSensitive: true }),
  card("FC133", "M14", ["F197"], ["uia.config"], "kernelType?", "Locked to CPA (Core Payments Application), replacing SPA (Secure Processor Application).", { typedAnswer: ["CPA"], typedCaseSensitive: true }),
  card("FC134", "M14", ["F201"], ["uia.config"], "Extra config keys?", "Device unlock passcodes, backend testing environment targets, active robot's registration name."),
  card("FC135", "M15", ["F041", "F043", "F042"], ["pigeon", "pigeon.lstr"], "Pigeon?", "Legacy repo (aka LSTR) evolved from Lester; name puns on \"pidgin language\"."),
  card("FC136", "M15", ["F044", "F202"], ["pigeon", "pigeon.lstr"], "LSTR and its runners?", "Language Specific Test Runner: REST, Android, Windows, iOS."),
  card("FC137", "M11", ["F203"], ["jenkins", "pigeon.lstr"], "Which runner is rarely touched?", "iOS, though iOS Go testing is active."),
  card("FC138", "M15", ["F012", "F205"], ["pigeon", "pigeon.json"], "Pigeon test anatomy?", "Raw JSON: test name, connection type, supported platforms, array of test actions."),
  card("FC139", "M15", ["F204"], ["pigeon", "pigeon.abstraction"], "How does Pigeon handle \"card swipe\"?", "Runner abstracts it into an SDK payment request or a physical robot action per platform."),
  card("FC140", "M15", ["F206", "F207"], ["pigeon", "pigeon.json"], "Pigeon platforms and actions?", "4 to 5 platforms at once; actions create requests, pass parameters, store outputs."),
  card("FC141", "M15", ["F208", "F209"], ["pigeon", "pigeon.nolint"], "Pigeon's JSON pain?", "No linter: hunt missing commas/brackets by hand; copy-paste known-good blocks."),
  card("FC142", "M15", ["F210", "F211"], ["pigeon", "jenkins.logs"], "Log says failed at \"select print\"?", "Last step before the printer-payload timeout. Usually stale coordinates made the arm miss Print."),
  card("FC143", "M16", ["F212", "F030"], ["duo.ocr", "pigeon.gimp"], "GIMP's job?", "Open screenshot, draw bounding box around text, copy exact coordinates (into Pigeon JSON / screen compare)."),
  card("FC144", "M16", ["F150", "F151", "F152"], ["duo.ocr", "orca.screencompare", "uia.v23"], "The Station Duo problem?", "One terminal, two displays; only the MFD is on ADB. Legacy UIA was blind to the CFD."),
  card("FC145", "M16", ["F153", "F154", "F029"], ["duo.ocr", "orca.screencompare", "vision.tesseract", "vision.camera"], "The OCR workaround?", "Stores CFD bounding box + expected text; Pi captures webcam shot, crops, runs Tesseract, returns boolean."),
  card("FC146", "M16", ["F155"], ["duo.ocr", "orca.screencompare"], "Why is OCR brittle?", "A 10-pixel shift, a capitalisation change or a typo breaks it."),
  card("FC147", "M16", ["F156"], ["duo.ocr", "orca.screencompare", "uia.v23"], "Why is OCR being phased out?", "UI Automator 2.3 natively supports dual-screen element tracking."),
  card("FC148", "M17", ["F075", "F076", "F077"], ["infra.ai", "arch.infra"], "The GPU blade?", "4 NVIDIA GPUs (two exposed, two underneath) in a shelf-mounted blade that replaced a legacy tower."),
  card("FC149", "M17", ["F078"], ["infra.ai", "arch.infra"], "What does the blade host?", "VMs, Orca, Jenkins and Ollama."),
  card("FC150", "M17", ["F031", "F032"], ["infra.ai", "vision.ollama"], "Ollama?", "Local LLM runner on the GPU blade; PoC vision checks of webcam streams for receipt layouts and tip math."),
  card("FC151", "M17", ["F033"], ["infra.ai", "tools.claude"], "Claude?", "Evaluated in corporate AI initiatives for repository optimisation and automated test generation."),
  card("FC152", "M17", ["F022"], ["infra.ai", "arch.infra"], "Orca's planned migration?", "Containerise with Docker, move to Google Cloud Platform."),
  card("FC153", "M17", ["F222", "F223"], ["infra.ai", "bots.pin"], "Gen 2 Software PIN Bypass?", "With the Core OS Team: software Secure Touch PIN entry; robots reserved for non-negotiables like card dipping."),
  card("FC154", "M18", ["F157", "F158"], ["teams.history", "uia.history"], "Semi and Sedi teams?", "Semi built third-party POS SDKs and remote pay display apps; Sedi (QA) tested them with Lester."),
  card("FC155", "M18", ["F052", "F053"], ["teams.history", "semi.paydisplay"], "USB Pay Display / Secure Network Pay Display?", "Semi Team apps linking MFDs and CFDs over USB or the local network."),
  card("FC156", "M18", ["F160", "F161"], ["teams.history", "uia.history"], "IPX?", "Integrated Payment Experience: uia-remote tests Register, Orders, Authorizations, Sale, Transactions, Setup."),
  card("FC157", "M18", ["F162"], ["teams.history", "uia.history"], "PayCore and uia-remote?", "PayCore adopted it for apps like LabSim Dining.", { typedAnswer: ["LabSim Dining"] }),
  card("FC158", "M08", ["F140"], ["orca.capabilities", "orca.merchant", "laz.oobe"], "Merchant Config + Laz?", "They work together for dynamic OOBE merchant switching."),
  card("FC159", "M08", ["F011"], ["orca.capabilities", "arch.stack"], "Format for Orca runtime capability lookups?", "JSON.", { typedAnswer: ["JSON"] }),
]);
