/**
 * Academy module metadata, M01–M18 (Cur §2). Titles, mentors, prerequisites, facts covered, objectives,
 * durations and checkpoint items are transcribed from docs/design/10-curriculum.md; `summary` is a short
 * menu blurb written for the module card. `unlockXp` = 0: Academy modules unlock by prerequisites
 * (Cur §2.1); the progression system may override. Lesson scripts live in src/missions/academy/.
 */
import type { ModuleMeta } from './schema';
import { resolvePeople } from './people';

export const MODULES: ModuleMeta[] = resolvePeople<ModuleMeta[]>([
  {
    id: "M01",
    title: "Welcome to the Lab: Orientation & Safety",
    mentor: "morgan",
    summary: "Your first walk through the LabSim automation lab: meet the touch robots and their status tablets, learn why you never fight a running robot, and find where the black fixtures come from.",
    objectives: [
      "Name the front-mounted status tablet and read its header (robot name, Status: OK, Brainbox v6).",
      "State that Orca's Robot entity tracks a pool of 40+ rigs, each named after a famous robot.",
      "Explain why the control dashboard is locked while a test is active, and never fight a running robot.",
      "Identify the POWER panel's MAIN and MOTOR toggles and the rack-unit numbering on the rails.",
      "Say where the black fixtures come from (Prusa / Bambu Lab printers, CAD from simple shapes).",
    ],
    prerequisites: [],
    factIds: ["F072", "F073", "F089", "F115", "F230", "F233", "F236", "F244", "F245"],
    tags: ["lab.orientation"],
    estMinutes: 12,
    estMinutesRange: [10, 12],
    checkpointId: "CP-M01.1",
    checkpointTitle: "Lab Basics",
    checkpointQuestionIds: ["Q001", "Q002", "Q003", "Q004", "Q005"],
    deck: "deck.M01",
    unlocks: ["M02, M03", "Field Manual chapter \"Lab Basics\"", "flashcard deck deck.M01"],
    setup: "Player spawns at loc.entrance. WALL-E is running scripted Jenkins build Java/uia-remote-regression-flex #4120 (tablet locked). All other rigs idle.",
    unlockXp: 0,
  },
  {
    id: "M02",
    title: "Know Your terminals: Device Families",
    mentor: "morgan",
    cameos: ["jared"],
    summary: "Sort every LabSim target device into its family, decode MFD and CFD on the tethered test beds, and learn the profile and hot-swap shortcuts that save hours.",
    objectives: [
      "Sort every LabSim target device into the Station, Mini, Flex and Compact families, including upcoming models.",
      "Expand MFD and CFD and recognise them on tethered test-bed labels (rig · role · environment).",
      "State that Flex 3, Flex 4 and Flex Pocket share one testing profile and the Pocket has no printer block.",
      "Explain the Mini 3 hot-swap for the printerless Station Duo 2 and the Compact's Canadian / Westers role.",
    ],
    prerequisites: ["M01"],
    factIds: ["F054", "F055", "F056", "F057", "F058", "F059", "F060", "F061", "F062", "F237", "F238", "F239"],
    tags: ["devices"],
    estMinutes: 12,
    estMinutesRange: [12, 12],
    checkpointId: "CP-M02.1",
    checkpointTitle: "Device Families",
    checkpointQuestionIds: ["Q012", "Q013", "Q014", "Q015", "Q017"],
    deck: "deck.M02",
    unlocks: ["M04 (with M03)", "deck deck.M02"],
    setup: "Device library shelf loc.device-library holds one of every device plus two sealed boxes labelled \"STATION DUO 3 — UPCOMING\" and \"MINI 4 — UPCOMING\".",
    unlockXp: 0,
  },
  {
    id: "M03",
    title: "Power Distribution: Don't Fry the terminals",
    mentor: "jared",
    summary: "Trace power from the 120 V wall through the Mean Well and the 24 V rail to the 12 V NUC and 5 V 10 A Pi lines, fix a blown inline fuse, and learn why terminals and Collis probes live on AC strips.",
    objectives: [
      "Trace the power chain 120V AC → Mean Well → 24V DC rail → step-down regulators → 12V (NUCs) / 5V 10A (Pis), with inline fuses.",
      "Diagnose and replace a blown inline fuse.",
      "Explain the 18V exception: LabSim terminals and Collis probes bypass the DC rails and use commercial AC power strips.",
    ],
    prerequisites: ["M01"],
    factIds: ["F074", "F085", "F086", "F087", "F227", "F228", "F229"],
    tags: ["power.rails"],
    estMinutes: 12,
    estMinutesRange: [12, 12],
    checkpointId: "CP-M03.1",
    checkpointTitle: "Power",
    checkpointQuestionIds: ["Q028", "Q030", "Q031", "Q033", "Q035"],
    deck: "deck.M03",
    unlocks: ["M04 (with M02)", "Arcade incidents INC-FUSE-5V, INC-WRONG-OUTLET", "deck deck.M03"],
    setup: "Rack B's 5V inline fuse prop.fuse-5v-b is blown: the JOHNNY-5/BAYMAX/SETI/ROSIE Pis show no LEDs. A new Flex 4 power brick prop.flex4-psu-brick and a spare Collis probe prop.collis-probe-spare lie unplugged on loc.power-wall's bench.",
    unlockXp: 0,
  },
  {
    id: "M04",
    title: "Touch Robot Mechanics & the Status Tablet",
    mentor: "jared",
    summary: "Open up a touch robot: gantry, steppers, solenoid, dip arm and limit switches. Drive every Motion Control group, break the magnetic lock on purpose and recover with Park All.",
    objectives: [
      "Name the gantry parts: 2020 extrusion rails, NEMA-17 stepper with GT2 pulley, V-slot wheels, carriage, blue push-pull solenoid, dip arm, limit switches, magnetic lock, webcam.",
      "Operate every Motion Control group on the tablet (Steppers, Park, Dip, Tap, Phone, Solenoid).",
      "Recover from a broken magnetic lock (yellow banner) with **Park All** (green banner, (0,0)).",
      "Quote the build numbers: 10 ft rails, 130 ft wiring, ~300 solder points, 200+ nuts and bolts (2.5 mm / 5 mm), 25-pin PCBs printed in Hong Kong.",
    ],
    prerequisites: ["M02", "M03"],
    factIds: ["F079", "F080", "F081", "F082", "F083", "F084", "F088", "F090", "F091", "F092", "F093", "F231", "F232", "F234", "F235", "F240", "F241", "F242", "F243"],
    tags: ["robots.mechanics"],
    estMinutes: 18,
    estMinutesRange: [18, 18],
    checkpointId: "CP-M04.1",
    checkpointTitle: "Touch Robot",
    checkpointQuestionIds: ["Q040", "Q041", "Q042", "Q043", "Q047"],
    deck: "deck.M04",
    unlocks: ["M05 (with M03), M09 (with M07)", "Arcade incident INC-MAGLOCK", "Arcade drill \"Park It!\"", "deck deck.M04"],
    setup: "WALL-E idle and Available (tablet unlocked). Enclosure door prop.walle.door closed. Bolt bins at loc.jared-bench.",
    unlockXp: 0,
  },
  {
    id: "M05",
    title: "The Robot Pi: Raspberry Pi, Linux & Wine",
    mentor: "jared",
    summary: "Meet the ~$50 Raspberry Pi that controls each shelf: SSH in, prove it runs Linux and Wine, hit its health endpoint, and learn why hardware control left the Windows NUCs.",
    objectives: [
      "Explain that a ~$50 Raspberry Pi is the Robot Controller on each shelf and list its duties (ADB routing, camera stream, steppers, solenoids, Wine card programming).",
      "Explain why hardware control moved off the Windows Intel NUCs (corporate monitoring packages filled the disks) onto Linux Pis.",
      "SSH into a Pi and verify its OS, its controller service, its disk, Wine and its health endpoint.",
    ],
    prerequisites: ["M03", "M04"],
    factIds: ["F019", "F020", "F021", "F063", "F064", "F065", "F066", "F067", "F068"],
    tags: ["pi.controller"],
    estMinutes: 14,
    estMinutesRange: [14, 14],
    checkpointId: "CP-M05.1",
    checkpointTitle: "Robot Pi",
    checkpointQuestionIds: ["Q063", "Q065", "Q067", "Q069", "Q071"],
    deck: "deck.M05",
    unlocks: ["M06, M12", "Terminal commands ssh, uname, df, ps, systemctl, curl", "deck deck.M05"],
    setup: "WALL-E's Pi 10.42.10.11 healthy. prop.nuc-03 on loc.callus-shelf shows a sticky note. Terminal app unlocked.",
    unlockXp: 0,
  },
  {
    id: "M06",
    title: "Orca Architecture & the Five Robot Statuses",
    mentor: "tate",
    cameos: ["jared"],
    summary: "How Orca (the Controller) and Jenkins (the Executor) fit together, and the five robot statuses: break a Pi, read the Notes, escalate to {{jared}}, and use Offline, Reserved and Unavailable correctly.",
    objectives: [
      "Draw the execution flow: Jenkins (Executor) → test runner → Orca (Controller) → Pi → device; Callus → Collis → card reader.",
      "Describe Orca's stack: on-prem Spring Boot monolith in Java, scaffolded by JHipster, MySQL-backed, running on a lab VM.",
      "Define all 5 statuses and who/what sets each; use {{tate}}'s filter UI.",
      "Handle a Connection Failed: read Notes (endpoint + error), escalate to {{jared}}, verify recovery.",
      "Use Offline, Reserved and Unavailable correctly, including the named-robot job parameter and the auto-reset.",
    ],
    prerequisites: ["M05"],
    factIds: ["F001", "F002", "F003", "F004", "F013", "F023", "F036", "F037", "F038", "F094", "F095", "F096", "F097", "F098", "F099", "F100", "F101", "F102", "F103", "F104", "F105", "F106", "F107", "F108", "F109", "F110", "F111", "F112", "F113", "F116"],
    tags: ["orca.status"],
    estMinutes: 22,
    estMinutesRange: [22, 22],
    checkpointId: "CP-M06.1",
    checkpointTitle: "Orca & Statuses",
    checkpointQuestionIds: ["Q078", "Q079", "Q084", "Q086", "Q088", "Q091", "Q101"],
    deck: "deck.M06",
    unlocks: ["M07, M11 (with M07)", "Arcade incident types INC-CONN-FAILED, INC-RESERVED-BLOCK, INC-UNAVAILABLE-NAMED", "deck deck.M06"],
    setup: "All rigs as in §0.4 roster. Orca app unlocked with the Robots page. Tutorial-only \"Force health check\" button visible in Orca's header (Academy and Free Play only). Jenkins app unlocked, showing only job Java/uia-remote-regression-flex.",
    unlockXp: 0,
  },
  {
    id: "M07",
    title: "Orca Entities: Robot, Device, Device Type, URLs, Tethering & Offsets",
    mentor: "tate",
    cameos: ["jared"],
    summary: "Orca's JHipster entities in practice: fix a Human Readable Name, upgrade a robot's hardware with a new Device, complete URL mappings, tether an MFD/CFD pair and retire a stale Offset.",
    objectives: [
      "List Orca's 7 core JHipster schemas and what MySQL stores.",
      "Distinguish Name (system identifier) from Human Readable Name (pushed to the tablet).",
      "Upgrade a robot's hardware by creating a new Device and relinking Robot Device, keeping the old one for rollback.",
      "Explain the Device Type enum and why Jenkins env vars must be ALL CAPS.",
      "Fill URL Mappings (ADB Service, Camera Stream, Dip, Tap, Swipe), configure MFD/CFD tethering, and explain Offsets' deprecation.",
    ],
    prerequisites: ["M06"],
    factIds: ["F014", "F114", "F115", "F117", "F118", "F119", "F120", "F121", "F122", "F123", "F124", "F125", "F126", "F127", "F128", "F129", "F130"],
    tags: ["orca.entities"],
    estMinutes: 20,
    estMinutesRange: [20, 20],
    checkpointId: "CP-M07.1",
    checkpointTitle: "Orca Entities",
    checkpointQuestionIds: ["Q119", "Q121", "Q122", "Q123", "Q127", "Q132"],
    deck: "deck.M07",
    unlocks: ["M08, M09 (with M04), M11 (with M06)", "Arcade incidents INC-HRN-TYPO, INC-DEVICE-UPGRADE, INC-TETHER-MISSING", "deck deck.M07"],
    setup: "JOHNNY-5's Human Readable Name is the typo JONNY-5 (tablet shows it). {{jared}} has physically swapped JOHNNY-5's Flex 1 for a Flex 2 (serial SIM-F2-000015). JOHNNY-5's Tap URL is blank. OPTIMUS's MFD field is empty (so pipelines treat it as standalone). BUMBLEBEE has legacy Offset Y = 1.5 mm causing low taps.",
    unlockXp: 0,
  },
  {
    id: "M08",
    title: "Capabilities, Merchant Config, Laz & Ubi",
    mentor: "david",
    cameos: ["tate"],
    summary: "How Orca matches tests to robots (dynamic JSON vs hardcoded capabilities), where Merchant Config hides its fields, the Go SDK credentials, and Laz's zero-touch OOBE merchant swap via Ubi.",
    objectives: [
      "Explain the Robot Capabilities entity and the two lookup styles: dynamic JSON (SDK frameworks, in the test definition, parsed at runtime) vs non-dynamic (hardcoded in the pipeline script); both are used for Contact Canada on Westers beds.",
      "Open hidden Merchant Config fields with **Edit**, and set App ID / App Secret / API Key for Go SDK pipelines.",
      "Run Laz Automation's zero-touch OOBE merchant swap and recognise the Ubi Platform routing step.",
    ],
    prerequisites: ["M07"],
    factIds: ["F008", "F009", "F011", "F046", "F047", "F051", "F131", "F132", "F133", "F134", "F135", "F136", "F137", "F138", "F139", "F140"],
    tags: ["orca.capabilities"],
    estMinutes: 18,
    estMinutesRange: [18, 18],
    checkpointId: "CP-M08.1",
    checkpointTitle: "Capabilities & Merchants",
    checkpointQuestionIds: ["Q144", "Q145", "Q146", "Q151", "Q153", "Q158"],
    deck: "deck.M08",
    unlocks: ["M10", "Arcade incidents INC-MERCHANT-KEY, INC-CAPABILITY-MISMATCH", "deck deck.M08"],
    setup: "Merchant Config row GO-SDK-US-01 has a blank **API Key**. Gort test definition go-sdk/tests/sale_receipt.json lacks a printer capability (so Orca may match ROSIE / Flex Pocket). DATA is on merchant AUTO-US-NOPIN-01.",
    unlockXp: 0,
  },
  {
    id: "M09",
    title: "Screens, Screen Locations & xy_touch (ADB Bots vs Physical Bots)",
    mentor: "jared",
    summary: "Screens, Screen Locations in millimetres and xy_touch; when a tap is an ADB touch and when it is a solenoid; why Canada needs physical bots; and the receipt QR regression that broke the lab for 48 hours.",
    objectives: [
      "Explain the Screens entity (layouts in a transaction flow per device architecture) and Screen Locations (button X/Y in mm).",
      "Call xy_touch with a screen name and button string and predict whether the Pi fires an ADB touch or a physical probe tap.",
      "Choose ADB bots vs physical bots correctly (PIN entry, Canadian flows, ADB-blind displays).",
      "Recover from a layout shift: measure, create a separate 5-option map, and land the coordinate PR.",
    ],
    prerequisites: ["M04", "M07"],
    factIds: ["F082", "F096", "F141", "F142", "F143", "F144", "F213", "F214", "F215", "F216", "F217", "F218", "F219", "F220", "F221"],
    tags: ["orca.screens"],
    estMinutes: 22,
    estMinutesRange: [22, 22],
    checkpointId: "CP-M09.1",
    checkpointTitle: "Coordinates & Bots",
    checkpointQuestionIds: ["Q167", "Q168", "Q170", "Q172", "Q174", "Q180", "Q184"],
    deck: "deck.M09",
    unlocks: ["M15 (with M13)", "Arcade incidents INC-COORD-DRIFT, INC-PIN-ON-ADB-BOT", "deck deck.M09"],
    setup: "EVE (FLEX_4) has received the \"scan for receipt\" firmware: its receipt screen now shows 5 options and all buttons sit 3.0 mm lower. Orca still has only RECEIPT_OPTIONS_4 for FLEX_4. A ruler prop.ruler sits on Rack A.",
    unlockXp: 0,
  },
  {
    id: "M10",
    title: "Card Profiles: Gort, Callus & Collis",
    mentor: "jared",
    cameos: ["david"],
    summary: "Card profiles end to end: raw Track Data for swipes, Gort file paths for dips and taps, the scheduled clone, Callus on the Windows/Minix boxes and the Collis probes, plus the team's card philosophy.",
    objectives: [
      "Explain Collis probes (UL Transaction Security): expensive card emulators on rear ribbon cables that do swipe, dip and tap.",
      "Explain Callus (aka Callers / Collos) on Windows/Minix boxes: it reads Gort card paths and drives the probes.",
      "Distinguish swipe profiles (raw Track Data in MySQL, from a card-reader utility) from dip/tap profiles (file paths into Gort, cloned to Windows boxes by a scheduled job).",
      "Pick card profiles the team's way: one reliable Visa, plus Interac for Canada.",
    ],
    prerequisites: ["M08"],
    factIds: ["F034", "F035", "F048", "F049", "F050", "F069", "F070", "F071", "F097", "F145", "F146", "F147", "F148", "F149", "F224", "F225"],
    tags: ["cards"],
    estMinutes: 18,
    estMinutesRange: [18, 18],
    checkpointId: "CP-M10.1",
    checkpointTitle: "Cards",
    checkpointQuestionIds: ["Q189", "Q190", "Q193", "Q196", "Q200", "Q205", "Q207"],
    deck: "deck.M10",
    unlocks: ["— (required for M18)", "Arcade incidents INC-CALLUS-DOWN, INC-CARD-PATH", "deck deck.M10"],
    setup: "MINIX-01 (10.42.20.1, Callus on :9000) serves Rack A. Scheduled task GortCardSync is configured. Card profiles as in §0.4.",
    unlockXp: 0,
  },
  {
    id: "M11",
    title: "Jenkins: The Executor",
    mentor: "tate",
    summary: "Jenkins as the Executor: legacy Java vs iOS views, the ALL-CAPS Device Type rule, the injected environment block and named builds on Unavailable robots.",
    objectives: [
      "Describe Jenkins as the Executor: it triggers pipelines, injects runtime env vars and checks out robots from Orca.",
      "Navigate the legacy platform split (Java jobs vs iOS jobs).",
      "Fix the lower-case enum failure and read the injected environment in a console log.",
    ],
    prerequisites: ["M06", "M07"],
    factIds: ["F015", "F016", "F017", "F094", "F095", "F102", "F122", "F189", "F203"],
    tags: ["jenkins"],
    estMinutes: 12,
    estMinutesRange: [12, 12],
    checkpointId: "CP-M11.1",
    checkpointTitle: "Jenkins",
    checkpointQuestionIds: ["Q214", "Q215", "Q216", "Q217", "Q220"],
    deck: "deck.M11",
    unlocks: ["— (required for M18)", "Arcade incident INC-ENV-CASE", "deck deck.M11"],
    setup: "Jenkins job Java/uia-remote-regression-flex has a saved parameter DEVICE_TYPE=flex_3 (lower case).",
    unlockXp: 0,
  },
  {
    id: "M12",
    title: "ADB on Port 5444",
    mentor: "morgan",
    summary: "Talk to a LabSim without touching it: connect on port 5444, dump the XML UI hierarchy, find an element and tap it — and see what happens on the default port 5555.",
    objectives: [
      "Connect to a lab device over ADB on port 5444 and list devices.",
      "Dump and read the XML UI hierarchy to locate an element's bounds.",
      "Dispatch a programmatic tap with input tap.",
      "Recognise 5555 as the standard ADB default and the refused connection it produces in the lab.",
    ],
    prerequisites: ["M05"],
    factIds: ["F024", "F025", "F026", "F199"],
    tags: ["adb.port"],
    estMinutes: 12,
    estMinutesRange: [12, 12],
    checkpointId: "CP-M12.1",
    checkpointTitle: "ADB",
    checkpointQuestionIds: ["Q225", "Q226", "Q227", "Q228", "Q231"],
    deck: "deck.M12",
    unlocks: ["M13", "Arcade drill \"ADB Speedrun\"", "deck deck.M12"],
    setup: "TARS (FLEX_4, 10.42.30.32) on HomeScreen. Terminal has adb.",
    unlockXp: 0,
  },
  {
    id: "M13",
    title: "uia-remote: Structure & the Page Object Model",
    mentor: "morgan",
    summary: "uia-remote from the inside: clone it into IntelliJ IDEA, learn the app/src layout and androidTest packages, read and fix page objects, and order the multi-device runner's calls.",
    objectives: [
      "Clone uia-remote from GitHub into IntelliJ IDEA and navigate app/src/{main,test,androidTest} (Maven-style layout).",
      "Place files correctly: androidTest packages databases, pageobjects, testactions; runner in test; never touch main.",
      "Read a screen class: extends BaseTest, Zone 1 locators, Zone 2 helpers, mandatory waitForScreen() / isScreenPresent().",
      "Fix open(String appName) scroll direction (Flex vertical; Mini/Station horizontal).",
      "Explain the multi-device runner trick (UI Automator talks to one device at a time).",
    ],
    prerequisites: ["M12"],
    factIds: ["F001", "F005", "F006", "F010", "F018", "F027", "F028", "F039", "F040", "F159", "F163", "F164", "F165", "F166", "F167", "F168", "F169", "F170", "F171", "F172", "F173", "F174", "F175", "F176", "F177", "F178", "F179", "F180"],
    tags: ["uia.pom"],
    estMinutes: 22,
    estMinutesRange: [22, 22],
    checkpointId: "CP-M13.1",
    checkpointTitle: "uia-remote & POM",
    checkpointQuestionIds: ["Q233", "Q234", "Q240", "Q241", "Q243", "Q248", "Q257", "Q261"],
    deck: "deck.M13",
    unlocks: ["M14, M15", "Arcade drills \"Where Does It Go?\", \"POM Doctor\"", "deck deck.M13"],
    setup: "GitHub org labsim-lab with repos gort, uia-remote, pigeon. HomeScreen.open() has a seeded bug (Flex branch scrolls horizontally). ReceiptScreen.java lacks the mandatory methods.",
    unlockXp: 0,
  },
  {
    id: "M14",
    title: "config.properties & the Tethered Tax Test",
    mentor: "morgan",
    cameos: ["riley"],
    summary: "Configure config.properties for a tethered run (and learn the hard way why portNumber is 5444), reserve the rig, then run and narrate the Tax test across MFD and CFD.",
    objectives: [
      "Configure config.properties for a local tethered run: runType, MFD/CFD IPs (same IP on a Station Duo), serial, deviceType, theme, kernelType, portNumber, extra keys.",
      "Explain the 5444 lock (5555 default caused coworker-device collisions) and the avocado / CPA locks.",
      "Reserve the rig, run the Tax test and narrate MFD_O1 → CFD_O1 → MFD_O2 → Step 4, including the Orca→Callus swipe load and the HomeScreen safe state.",
    ],
    prerequisites: ["M13"],
    factIds: ["F054", "F181", "F182", "F183", "F184", "F185", "F186", "F187", "F188", "F189", "F190", "F191", "F192", "F193", "F194", "F195", "F196", "F197", "F198", "F199", "F200", "F201"],
    tags: ["uia.config"],
    estMinutes: 22,
    estMinutesRange: [22, 22],
    checkpointId: "CP-M14.1",
    checkpointTitle: "Config & Tax Test",
    checkpointQuestionIds: ["Q275", "Q276", "Q279", "Q284", "Q286", "Q288", "Q290", "Q296"],
    deck: "deck.M14",
    unlocks: ["M16", "Arcade incidents INC-PORT-COLLISION, INC-CONFIG-LOCKS, INC-DUO-SAME-IP", "deck deck.M14"],
    setup: "The cloned uia-remote has the broken config.properties below. A coworker's desk Flex (10.42.60.4, ADB on 5555) is already known to the workstation's ADB server. MEGATRON (STATION_2 MFD 10.42.30.21 + MINI_2 CFD 10.42.30.22, env DEV1) is Available.",
    unlockXp: 0,
  },
  {
    id: "M15",
    title: "Pigeon (LSTR) & Legacy JSON",
    mentor: "morgan",
    cameos: ["jared"],
    summary: "The legacy Pigeon repo: Lester's heir and its Language Specific Test Runner, raw JSON tests with no linter, and the misleading \"select print\" failure.",
    objectives: [
      "Explain Pigeon's lineage (Lester → Pigeon, the \"pidgin\" pun) and LSTR = Language Specific Test Runner with REST, Android, Windows and iOS runners.",
      "Read a Pigeon JSON test: name, connection type, supported platforms (4–5 at once), actions (create requests, pass parameters, store outputs).",
      "Survive the missing JSON linter: find a missing comma or paste a known-good block.",
      "Decode a misleading \"select print\" failure as a printer-payload timeout caused by stale coordinates.",
    ],
    prerequisites: ["M09", "M13"],
    factIds: ["F009", "F012", "F041", "F042", "F043", "F044", "F045", "F202", "F203", "F204", "F205", "F206", "F207", "F208", "F209", "F210", "F211"],
    tags: ["pigeon"],
    estMinutes: 18,
    estMinutesRange: [18, 18],
    checkpointId: "CP-M15.1",
    checkpointTitle: "Pigeon",
    checkpointQuestionIds: ["Q308", "Q309", "Q311", "Q312", "Q316", "Q320", "Q322"],
    deck: "deck.M15",
    unlocks: ["M16", "Arcade drills \"Comma Hunt\", \"Log Detective\"", "deck deck.M15"],
    setup: "pigeon/tests/sale/swipe_sale_print.json is missing a comma after line 22. BUMBLEBEE (MINI_3) has outdated receipt coordinates; {{jared}}'s PR gort#418 Update MINI_3 receipt coordinates is open.",
    unlockXp: 0,
  },
  {
    id: "M16",
    title: "Seeing the Second Screen: Station Duo, OCR, GIMP & UIA 2.3",
    mentor: "morgan",
    summary: "The Station Duo's customer screen is blind to ADB: build a Screen Compare OCR check with GIMP and Tesseract, watch it break, then replace it with a UI Automator 2.3 assertion.",
    objectives: [
      "Explain the dual-screen problem: on a Station Duo only the primary MFD is exposed to ADB; legacy UI Automator is blind to the CFD (an ADB-blind display).",
      "Build a Screen Compare Image (bounding box from GIMP + expected text), and describe capture → crop → Tesseract → boolean.",
      "Show why it is brittle (10-pixel shift, capitalisation, typo) and why it is being phased out for UI Automator 2.3's native dual-screen tracking.",
      "Configure a Station Duo: MFD IP = CFD IP.",
    ],
    prerequisites: ["M14", "M15"],
    factIds: ["F006", "F007", "F029", "F030", "F088", "F150", "F151", "F152", "F153", "F154", "F155", "F156", "F193", "F212", "F221"],
    tags: ["duo.ocr"],
    estMinutes: 20,
    estMinutesRange: [20, 20],
    checkpointId: "CP-M16.1",
    checkpointTitle: "Second Screen",
    checkpointQuestionIds: ["Q331", "Q333", "Q335", "Q337", "Q339", "Q343"],
    deck: "deck.M16",
    unlocks: ["M17", "Arcade incidents INC-OCR-BRITTLE, INC-DUO-BLIND", "deck deck.M16"],
    setup: "R2-D2 (STATION_DUO, 10.42.30.14) mid-sale showing totals on its CFD. R2-D2's webcam (http://10.42.10.14:8081/stream.mjpg) is aimed at the CFD. Tutorial toggle \"CFD layout v2\" available in Orca's Screen Compare test panel.",
    unlockXp: 0,
  },
  {
    id: "M17",
    title: "AI, Infrastructure & the Roadmap",
    mentor: "jared",
    cameos: ["david"],
    summary: "The 4-GPU server blade and what it hosts, Ollama's vision proof of concept, Claude's evaluation for test generation, and the roadmap from on-prem VM to Docker/GCP and Gen 2 PIN bypass.",
    objectives: [
      "Describe the shelf-mounted 4× NVIDIA GPU blade (2 exposed, 2 underneath) that replaced a tower and hosts the VMs (Orca, Jenkins) and Ollama.",
      "Use Ollama's vision PoC to check a receipt layout and its tip math; explain that it is a proof of concept.",
      "Explain Claude's evaluation (repo optimisation, automated test generation) and review an AI-generated PR.",
      "Place roadmap items: Orca from on-prem VM to Docker/GCP; NUC → Pi (done); Gen 2 Software PIN Bypass with Core OS.",
    ],
    prerequisites: ["M16"],
    factIds: ["F013", "F018", "F022", "F023", "F031", "F032", "F033", "F066", "F068", "F075", "F076", "F077", "F078", "F222", "F223"],
    tags: ["infra.ai"],
    estMinutes: 16,
    estMinutesRange: [16, 16],
    checkpointId: "CP-M17.1",
    checkpointTitle: "Infra & AI",
    checkpointQuestionIds: ["Q351", "Q354", "Q355", "Q358", "Q359"],
    deck: "deck.M17",
    unlocks: ["M18", "deck deck.M17"],
    setup: "GPU blade prop.gpu-blade on loc.server-shelf (GPUs 1–2 visible on top, 3–4 underneath). Retired tower prop.legacy-tower on the floor. Ollama at 10.42.1.12:11434 with model llava. GitHub PR uia-remote#212 [AI eval] Generated tests for ReceiptScreen open.",
    unlockXp: 0,
  },
  {
    id: "M18",
    title: "Teams, History & the Capstone Shift",
    mentor: "morgan",
    cameos: ["jared", "tate"],
    summary: "The team history from Semi and Sedi to uia-remote, IPX and PayCore, the two card philosophies, and a no-hints capstone shift that pulls the whole Academy together.",
    objectives: [
      "Tell the team history: Semi Team (POS SDKs, USB Pay Display, Secure Network Pay Display), Sedi QA Team (Lester), {{morgan}}'s uia-remote, adoption by IPX and PayCore.",
      "Contrast the team's card philosophy (single Visa + Interac) with PayCore's full matrix.",
      "Run a mixed incident shift end to end with no hints.",
    ],
    prerequisites: ["M01", "M02", "M03", "M04", "M05", "M06", "M07", "M08", "M09", "M10", "M11", "M12", "M13", "M14", "M15", "M16", "M17"],
    factIds: ["F042", "F043", "F052", "F053", "F103", "F110", "F157", "F158", "F159", "F160", "F161", "F162", "F224", "F225", "F226"],
    tags: ["teams.history"],
    estMinutes: 25,
    estMinutesRange: [25, 25],
    checkpointId: "CP-M18.1",
    checkpointTitle: "Teams & History",
    checkpointQuestionIds: ["Q369", "Q370", "Q373", "Q375", "Q377"],
    deck: "deck.M18",
    unlocks: ["Certification exams (Section 5)", "Arcade \"Full Shift\" mode", "deck deck.M18"],
    setup: "History wall frames. For the capstone: BUMBLEBEE's Minix box (MINIX-01) Callus service is down; SETI's arm gets bumped by a coworker; job Java/uia-remote-regression-mini has DEVICE_TYPE=mini_3.",
    unlockXp: 0,
  },
]);

/** Lookup by id ("M07"). */
export const MODULES_BY_ID: Record<string, ModuleMeta> = Object.fromEntries(MODULES.map((m) => [m.id, m]));

/** Recommended order (Cur §2.1). */
export const MODULE_ORDER: string[] = MODULES.map((m) => m.id);

/** Modules whose prerequisites are all in `completed` (and that are not themselves completed). */
export function availableModules(completed: Iterable<string>): ModuleMeta[] {
  const done = new Set(completed);
  return MODULES.filter((m) => !done.has(m.id) && m.prerequisites.every((p) => done.has(p)));
}
